(() => {
  "use strict";
  if (document.getElementById("worldz-guide-button")) return;
  const host=location.hostname.toLowerCase(), path=location.pathname.toLowerCase();
  const forced=String(window.WORLDZ_GUIDE_CONTEXT||"").toLowerCase();
  const type=["hq","launch","donate","crypto"].includes(forced)?forced:(host==="worldzhq.com"?"hq":(host==="worldzlaunch.com"||host.includes("launchpad.cryptoworldz.xyz"))?"launch":host.includes("donateworldz.com")?"donate":"crypto");
  const base={
    hq:{title:"🌐 WORLDZHQ — START HERE",payload:"guide_hq",intro:"WorldzHQ is the front door to the whole Worldz ecosystem.",steps:["Choose what you actually came here to do.","Crypto or token building → CryptoWorldz / WorldzLaunch.","Direct support and causes → DonateWorldz.","If you are unsure, ask DipShit and describe your goal."],next:"https://cryptoworldz.xyz/",nextLabel:"🪙 OPEN CRYPTOWORLDZ"},
    launch:{title:"🚀 WORLDZLAUNCH — START HERE",payload:"guide_launch",intro:"You do not need to understand every advanced control before you start.",steps:["Choose a chain or start with the simple token builder.","Enter the token basics.","Read the plain-English explanation before advanced settings.","Use proof/review screens before any irreversible action."],next:"/create-your-own-money/",nextLabel:"💡 CREATE YOUR OWN MONEY"},
    crypto:{title:"🪙 CRYPTOWORLDZ — START HERE",payload:"guide_crypto",intro:"Pick one job. You do not need to learn the entire ecosystem first.",steps:["Join Worldz → open Command Centre.","Create a token → open WorldzLaunch.","Raid / earn Legend Points → Ronald Raider.","Confused anywhere → ask DipShit."],next:"https://cryptobotz.cryptoworldz.xyz/miniapp/",nextLabel:"🧠 OPEN COMMAND CENTRE"},
    donate:{title:"💜 DONATEWORLDZ — START HERE",payload:"guide_donate",intro:"Choose the person or purpose you want to support. Direct support stays separate from crypto activity.",steps:["Open the support pathway you care about.","Read who or what the pathway supports.","Use the listed payment route only when you are comfortable.","Ask DipShit if you are unsure where a button leads."],next:"/",nextLabel:"💜 VIEW SUPPORT PATHWAYS"}
  };
  const cfg=Object.assign({},base[type]);
  if(type==="launch"&&path.includes("/mint/")){cfg.title="🪙 WORLDZMINT — WHAT DO I DO?";cfg.intro="Minting creates the token itself. Start with the basics; signing stays in your wallet.";cfg.steps=["Connect your public wallet.","Enter name, symbol, supply and metadata.","Review the summary.","Approve only wallet actions you understand."];}
  else if(type==="launch"&&path.includes("create-your-own-money")){cfg.title="💡 CREATE YOUR OWN MONEY — START HERE";cfg.intro="Your idea → your token → your community. Creating a token does not automatically make it valuable, liquid or legal tender.";cfg.steps=["Choose beginner mode if this is new.","Describe the token idea.","Choose chain and supply.","WorldzLaunch explains the technical choices before launch."];}else if(type==="launch"&&path.includes("launch-calculators")){cfg.title="🧮 WORLDZ LAUNCH CALCULATORS";cfg.intro="Use live math before money moves.";cfg.steps=["Convert your real budget to spendable SOL.","Read the exact DAMM v2 LP pair requirement.","Compare BUY vs LP vs HYBRID.","Model starting price and market cap.","Account for distribution and multichain supply."];cfg.next="/chatgpt-token-design/";cfg.nextLabel="🤖 DESIGN WITH CHATGPT";}else if(type==="launch"&&path.includes("chatgpt-token-design")){cfg.title="🤖 CHATGPT TOKEN DESIGN";cfg.intro="Turn the idea into a structured plan before minting.";cfg.steps=["Describe purpose and audience.","Add supply, budget and preferred chain.","Choose cross-chain targets.","Run the design through the five calculators before signing anything."];cfg.next="/launch-calculators/";cfg.nextLabel="🧮 RUN THE 5 CALCULATORS";}
  else if(type==="launch"&&(path.includes("trust")||path.includes("proof")||path.includes("ready"))){cfg.title="✅ WORLDZ PROOF — WHAT AM I LOOKING AT?";cfg.intro="These screens separate what is proven from what is only planned or configured.";cfg.steps=["Green / verified = evidence passed.","Amber / gated = execution is still blocked.","Check addresses and transaction evidence before trusting a claim.","Ask DipShit to explain any proof field."];}
  const style=document.createElement("style");style.textContent="#worldz-guide-button{position:fixed;right:16px;bottom:16px;z-index:2147483000;border:1px solid #b788ff99;border-radius:999px;padding:12px 16px;background:linear-gradient(135deg,#6f2cff,#156dff);color:#fff;font:900 14px/1 system-ui,sans-serif;box-shadow:0 10px 34px #0009,0 0 24px #8c4cff55;cursor:pointer}#worldz-guide-panel{position:fixed;right:16px;bottom:72px;z-index:2147483000;width:min(390px,calc(100vw - 32px));max-height:min(72vh,640px);overflow:auto;padding:18px;border:1px solid #a97cff66;border-radius:22px;background:linear-gradient(165deg,#12091ff7,#080512f7);color:#fff;box-shadow:0 20px 60px #000c;font:15px/1.5 system-ui,sans-serif}#worldz-guide-panel[hidden]{display:none!important}#worldz-guide-panel h2{font-size:20px;margin:0 34px 8px 0}#worldz-guide-panel p{color:#d9d1e8;margin:.45rem 0}#worldz-guide-panel ol{padding-left:22px;margin:12px 0}#worldz-guide-panel li{margin:7px 0}.worldz-guide-actions{display:grid;gap:8px;margin-top:14px}.worldz-guide-actions a{display:block;text-align:center;text-decoration:none;padding:11px 12px;border-radius:12px;font-weight:900;color:#fff;background:#7b39e8}.worldz-guide-actions a.worldz-dip{background:#0c73c9}.worldz-guide-close{position:absolute;right:12px;top:10px;border:0;background:transparent;color:#fff;font-size:24px;cursor:pointer}.worldz-guide-note{font-size:12px;color:#aaa0ba!important}@media(max-width:520px){#worldz-guide-button{right:10px;bottom:10px}#worldz-guide-panel{right:10px;bottom:66px;width:calc(100vw - 20px)}}";document.head.appendChild(style);
  const button=document.createElement("button");button.id="worldz-guide-button";button.type="button";button.textContent="❓ START HERE";
  const panel=document.createElement("aside");panel.id="worldz-guide-panel";panel.hidden=true;panel.innerHTML="<button class=\"worldz-guide-close\" type=\"button\" aria-label=\"Close\">×</button><h2>"+cfg.title+"</h2><p>"+cfg.intro+"</p><ol>"+cfg.steps.map(function(s){return \"<li>\"+s+\"</li>\";}).join(\"\")+"</ol><div class=\"worldz-guide-actions\"><a href=\""+cfg.next+"\">"+cfg.nextLabel+"</a><a class=\"worldz-dip\" href=\"https://t.me/DipShitBossBot?start="+cfg.payload+"\" target=\"_blank\" rel=\"noopener\">💙 ASK DIPSHIT</a></div><p class=\"worldz-guide-note\">DipShit is a guide and troubleshooter. Never send him—or anyone—a seed phrase, private key or password.</p>";
  button.addEventListener("click",function(){panel.hidden=!panel.hidden;button.setAttribute("aria-expanded",String(!panel.hidden));});panel.querySelector(".worldz-guide-close").addEventListener("click",function(){panel.hidden=true;button.setAttribute("aria-expanded","false");});document.body.append(panel,button);
})();
