import {BrowserProvider,ContractFactory,getAddress,isAddress,formatUnits} from 'https://esm.sh/ethers@6.15.0?bundle';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const NETWORKS={
 'ethereum-sepolia':{name:'Ethereum Sepolia',chainId:11155111,hex:'0xaa36a7',rpc:'https://ethereum-sepolia-rpc.publicnode.com',explorer:'https://sepolia.etherscan.io',currency:'ETH'},
 'base-sepolia':{name:'Base Sepolia',chainId:84532,hex:'0x14a34',rpc:'https://sepolia.base.org',explorer:'https://sepolia.basescan.org',currency:'ETH'},
 'robinhood-testnet':{name:'Robinhood Chain Testnet',chainId:46630,hex:'0xb626',rpc:'https://rpc.testnet.chain.robinhood.com',explorer:'https://explorer.testnet.chain.robinhood.com',currency:'ETH'},
 'bsc-testnet':{name:'BNB Smart Chain Testnet',chainId:97,hex:'0x61',rpc:'https://bsc-testnet-dataseed.bnbchain.org',explorer:'https://testnet.bscscan.com',currency:'tBNB'},
 'hyperevm-testnet':{name:'HyperEVM Testnet',chainId:998,hex:'0x3e6',rpc:'https://rpc.hyperliquid-testnet.xyz/evm',explorer:'https://testnet.purrsec.com',currency:'HYPE'}
};
const SOURCE=`// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;
contract WorldzFixedSupplyToken {
 string public name; string public symbol; uint8 public constant decimals=18; uint256 public totalSupply;
 mapping(address=>uint256) public balanceOf; mapping(address=>mapping(address=>uint256)) public allowance;
 event Transfer(address indexed from,address indexed to,uint256 value); event Approval(address indexed owner,address indexed spender,uint256 value);
 constructor(string memory n,string memory s,uint256 whole,address[5] memory r,uint16[5] memory b){
  require(bytes(n).length>=2&&bytes(n).length<=32,"name");require(bytes(s).length>=2&&bytes(s).length<=10,"symbol");
  require(whole>=1000&&whole<=1_000_000_000_000,"supply");require(b[0]<=500,"creator");require(b[1]>=2500&&b[1]<=6000,"liquidity");require(b[2]>=2000,"community");require(b[3]<=1500,"treasury");
  uint256 sum;for(uint i=0;i<5;i++){require(r[i]!=address(0),"zero");sum+=b[i];for(uint j=0;j<i;j++)require(r[i]!=r[j],"duplicate");}require(sum==10000,"bps");
  name=n;symbol=s;totalSupply=whole*1e18;uint256 allocated;
  for(uint i=0;i<4;i++){uint256 a=totalSupply*b[i]/10000;allocated+=a;balanceOf[r[i]]=a;emit Transfer(address(0),r[i],a);}
  uint256 last=totalSupply-allocated;balanceOf[r[4]]=last;emit Transfer(address(0),r[4],last);
 }
 function transfer(address to,uint256 a) external returns(bool){_t(msg.sender,to,a);return true;}
 function approve(address sp,uint256 a) external returns(bool){allowance[msg.sender][sp]=a;emit Approval(msg.sender,sp,a);return true;}
 function transferFrom(address f,address to,uint256 a) external returns(bool){uint256 x=allowance[f][msg.sender];require(x>=a,"allowance");if(x!=type(uint256).max){allowance[f][msg.sender]=x-a;emit Approval(f,msg.sender,x-a);}_t(f,to,a);return true;}
 function _t(address f,address to,uint256 a) internal{require(to!=address(0),"zero");uint256 b=balanceOf[f];require(b>=a,"balance");unchecked{balanceOf[f]=b-a;}balanceOf[to]+=a;emit Transfer(f,to,a);}
}`;
let abi,bytecode,provider,signer,wallet='',compiled=false,checked=false;\nconst requestedNetwork=new URLSearchParams(location.search).get('network');\nif(requestedNetwork&&NETWORKS[requestedNetwork]) $('#network').value=requestedNetwork;
function status(id,t,c=''){const e=$(id);e.textContent=t;e.className='status'+(c?' '+c:'');}
function net(){return NETWORKS[$('#network').value];}
function alloc(){const o={};$$('.allocation').forEach(x=>o[x.dataset.key]=Number(x.value));return o;}
function vals(){return{name:$('#name').value.trim(),symbol:$('#symbol').value.trim().toUpperCase(),supply:$('#supply').value.trim(),fee:Number($('#fee').value),a:alloc(),r:[$('#creator-wallet').value.trim(),$('#liquidity-wallet').value.trim(),$('#community-wallet').value.trim(),$('#treasury-wallet').value.trim(),$('#growth-wallet').value.trim()]};}
async function compile(){status('#compile-status','Loading Solidity compiler…','warn');try{const m=await import('https://esm.sh/solc@0.8.30?bundle'),solc=m.default||m;const input={language:'Solidity',sources:{'WorldzFixedSupplyToken.sol':{content:SOURCE}},settings:{optimizer:{enabled:true,runs:200},outputSelection:{'*':{'*':['abi','evm.bytecode.object']}}}};const out=JSON.parse(solc.compile(JSON.stringify(input)));const errs=(out.errors||[]).filter(x=>x.severity==='error');if(errs.length)throw new Error(errs.map(x=>x.formattedMessage).join('\n'));const c=out.contracts['WorldzFixedSupplyToken.sol'].WorldzFixedSupplyToken;abi=c.abi;bytecode='0x'+c.evm.bytecode.object;compiled=true;status('#compile-status','FIXED-SUPPLY TEMPLATE COMPILED ✅\nNo post-genesis mint function. No freeze switch.','good');preflight();}catch(e){compiled=false;status('#compile-status','COMPILE FAILED\n'+(e.message||e),'bad');}}
async function switchNet(){if(!window.ethereum)throw new Error('No EIP-1193 EVM wallet detected.');const n=net();let current=await window.ethereum.request({method:'eth_chainId'});if(current.toLowerCase()!==n.hex){try{await window.ethereum.request({method:'wallet_switchEthereumChain',params:[{chainId:n.hex}]});}catch(e){if(e?.code!==4902)throw e;await window.ethereum.request({method:'wallet_addEthereumChain',params:[{chainId:n.hex,chainName:n.name,nativeCurrency:{name:n.currency,symbol:n.currency,decimals:18},rpcUrls:[n.rpc],blockExplorerUrls:[n.explorer]}]});}}}
async function connect(){try{await window.ethereum.request({method:'eth_requestAccounts'});await switchNet();provider=new BrowserProvider(window.ethereum);signer=await provider.getSigner();wallet=await signer.getAddress();$('#creator-wallet').value=wallet;$('#wallet').textContent=wallet.slice(0,6)+'…'+wallet.slice(-4);$('#wallet').classList.add('connected');status('#status',net().name+' WALLET CONNECTED ✅\n'+wallet+'\nNo transaction requested.','good');preflight();}catch(e){status('#status','WALLET CONNECTION FAILED\n'+(e.shortMessage||e.message||e),'bad');}}
function preflight(){const v=vals(),e=[];if(!compiled)e.push('Compile template.');if(!wallet)e.push('Connect EVM wallet.');if(v.name.length<2||v.name.length>32)e.push('Name must be 2–32 characters.');if(!/^[A-Z0-9_$]{2,10}$/.test(v.symbol))e.push('Ticker must be 2–10 letters/numbers/$/_.');if(!/^\d+$/.test(v.supply)||BigInt(v.supply)<1000n||BigInt(v.supply)>1000000000000n)e.push('Invalid fixed supply.');if(!Number.isFinite(v.fee)||v.fee<.5||v.fee>3)e.push('Fee must be 0.50%–3.00%.');const total=Object.values(v.a).reduce((a,b)=>a+b,0);if(Math.abs(total-100)>.001)e.push('Allocations must total 100%.');if(v.a.creator>5)e.push('Creator >5%.');if(v.a.liquidity<25||v.a.liquidity>60)e.push('Liquidity must be 25–60%.');if(v.a.community<20)e.push('Community must be ≥20%.');if(v.a.treasury>15)e.push('Treasury must be ≤15%.');const norm=[];for(const x of v.r){if(!isAddress(x)){e.push('All five destination addresses must be valid EVM addresses.');break;}norm.push(getAddress(x));}if(norm.length===5&&new Set(norm.map(x=>x.toLowerCase())).size!==5)e.push('Five destinations must be distinct.');if(wallet&&norm.length===5&&norm[0].toLowerCase()!==wallet.toLowerCase())e.push('Creator must match connected wallet.');checked=!e.length;$('#deploy').disabled=!checked;status('#status',e.length?'EVM PREFLIGHT BLOCKED\n• '+e.join('\n• '):'EVM PREFLIGHT PASS ✅\n'+net().name+'\nFixed supply • direct disclosed allocation • no mint/freeze switch\nToken deployment only; market launch proof remains separate.','good');return checked;}
async function deploy(){if(!preflight())return;$('#deploy').disabled=true;try{await switchNet();provider=new BrowserProvider(window.ethereum);signer=await provider.getSigner();const v=vals(),r=v.r.map(getAddress),bps=[v.a.creator,v.a.liquidity,v.a.community,v.a.treasury,v.a.growth].map(x=>Math.round(x*100));const f=new ContractFactory(abi,bytecode,signer);const req=await f.getDeployTransaction(v.name,v.symbol,BigInt(v.supply),r,bps);const gas=await provider.estimateGas({...req,from:wallet});status('#status','SIMULATION / GAS ESTIMATE PASS ✅\nGas: '+gas+'\nApprove deployment in wallet.','warn');const c=await f.deploy(v.name,v.symbol,BigInt(v.supply),r,bps);const tx=c.deploymentTransaction()?.hash||'';await c.waitForDeployment();const a=await c.getAddress(),s=await c.totalSupply();if(s!==BigInt(v.supply)*10n**18n)throw new Error('Supply proof mismatch.');status('#proof','TOKEN DEPLOYED ✅\nNetwork: '+net().name+'\nContract: '+a+'\nTransaction: '+tx+'\nSupply: '+formatUnits(s,18)+'\nExplorer: '+net().explorer+'/address/'+a,'good');status('#status','DEPLOYMENT VERIFIED ✅\nWorldz market-launch verification is still separate.','good');}catch(e){status('#status','DEPLOYMENT FAILED\n'+(e.shortMessage||e.message||e),'bad');}finally{$('#deploy').disabled=!checked;}}
$('#wallet').onclick=connect;$('#compile').onclick=compile;$('#check').onclick=preflight;$('#deploy').onclick=deploy;$('#network').onchange=async()=>{checked=false;$('#deploy').disabled=true;if(wallet){try{await switchNet();await connect();}catch(e){status('#status','NETWORK SWITCH FAILED\n'+(e.message||e),'bad');}}};$$('input').forEach(x=>x.addEventListener('input',()=>{$('#deploy').disabled=true;checked=false;}));