import {isInstalled,getAddress,getNetwork,submitTransaction} from 'https://esm.sh/@gemwallet/api@3.7.0?bundle';
const $=s=>document.querySelector(s);
let wallet='',network='';
const state={defaultRipple:false,noFreeze:false,trust:false,issued:false,amm:false};
function status(t,c=''){const e=$('#status');e.textContent=t;e.className='status'+(c?' '+c:'');}
function validAddr(s){return /^r[1-9A-HJ-NP-Za-km-z]{24,34}$/.test(String(s||''));}
function values(){return{issuer:$('#issuer').value.trim(),hot:$('#hot').value.trim(),currency:$('#currency').value.trim().toUpperCase(),supply:$('#supply').value.trim(),tokenLiquidity:$('#token-liquidity').value.trim(),xrpLiquidity:$('#xrp-liquidity').value.trim(),ammFee:Number($('#amm-fee').value)};}
function feeUnits(p){return Math.round(Number(p)*1000);}
function drops(x){const n=Number(x);if(!Number.isFinite(n)||n<=0)throw new Error('XRP liquidity must be greater than zero.');return String(Math.round(n*1_000_000));}
async function connect(){try{const ins=await isInstalled();if(!ins?.result?.isInstalled)throw new Error('GemWallet extension is not installed.');const [a,n]=await Promise.all([getAddress(),getNetwork()]);wallet=a?.result?.address||'';network=n?.result?.network||'';if(!validAddr(wallet))throw new Error('GemWallet returned no XRPL classic address.');if(String(network).toLowerCase()!=='testnet')throw new Error('Switch GemWallet to XRPL Testnet first.');if(!$('#issuer').value)$('#issuer').value=wallet;$('#connect').textContent=wallet.slice(0,6)+'…'+wallet.slice(-5);$('#connect').classList.add('connected');status('GEMWALLET CONNECTED ✅\n'+wallet+'\nNetwork: '+network+'\nNo transaction requested.','good');preflight();}catch(e){status('XRPL WALLET CONNECTION FAILED\n'+(e.message||e),'bad');}}
function preflight(){const v=values(),e=[];if(!wallet)e.push('Connect GemWallet.');if(String(network).toLowerCase()!=='testnet')e.push('GemWallet must be on Testnet.');if(!validAddr(v.issuer))e.push('Issuer address is invalid.');if(!validAddr(v.hot))e.push('Hot wallet address is invalid.');if(v.issuer&&v.hot&&v.issuer===v.hot)e.push('Issuer and hot wallet must be different accounts.');if(!/^[A-Z0-9]{3}$/.test(v.currency)||v.currency==='XRP')e.push('Use a 3-character token code other than XRP.');for(const [label,x] of [['Supply',v.supply],['Token liquidity',v.tokenLiquidity]]){if(!/^\d+(\.\d+)?$/.test(x)||Number(x)<=0)e.push(label+' must be positive.');}if(Number(v.tokenLiquidity)>=Number(v.supply))e.push('AMM token liquidity must be less than total supply.');if(!Number.isFinite(v.ammFee)||v.ammFee<0||v.ammFee>1)e.push('XRPL AMM fee must be 0%–1%.');const ok=!e.length;['#default-ripple','#no-freeze','#trust','#issue','#amm'].forEach(id=>$(id).disabled=!ok);status(e.length?'XRPL PREFLIGHT BLOCKED\n• '+e.join('\n• '):'XRPL PREFLIGHT PASS ✅\nIssuer: '+v.issuer+'\nHot wallet: '+v.hot+'\nCurrency: '+v.currency+'\nSupply: '+v.supply+'\nAMM fee: '+v.ammFee+'%\n\nFollow the account-switch instructions before each approval.','good');return ok;}
async function send(tx,label){if(!preflight())throw new Error('Preflight blocked.');const out=await submitTransaction({transaction:tx});if(out?.type==='reject'||!out?.result?.hash)throw new Error(label+' was rejected or returned no transaction hash.');const hash=out.result.hash;$('#proof').textContent=label+' ✅\nTransaction: '+hash;$('#proof').className='status good';return hash;}
async function ensureAccount(expected,label){await connect();if(wallet!==expected)throw new Error('Switch GemWallet to the '+label+' account '+expected+' and reconnect.');}
$('#connect').onclick=connect;$('#check').onclick=preflight;
$('#default-ripple').onclick=async()=>{try{const v=values();await ensureAccount(v.issuer,'issuer');await send({TransactionType:'AccountSet',Account:v.issuer,SetFlag:8},'Default Ripple enabled');state.defaultRipple=true;}catch(e){status(e.message||e,'bad');}};
$('#no-freeze').onclick=async()=>{try{const v=values();await ensureAccount(v.issuer,'issuer');await send({TransactionType:'AccountSet',Account:v.issuer,SetFlag:6},'No Freeze permanently enabled');state.noFreeze=true;}catch(e){status(e.message||e,'bad');}};
$('#trust').onclick=async()=>{try{const v=values();await ensureAccount(v.hot,'hot');await send({TransactionType:'TrustSet',Account:v.hot,LimitAmount:{currency:v.currency,issuer:v.issuer,value:v.supply}},'Hot-wallet trust line created');state.trust=true;}catch(e){status(e.message||e,'bad');}};
$('#issue').onclick=async()=>{try{const v=values();await ensureAccount(v.issuer,'issuer');await send({TransactionType:'Payment',Account:v.issuer,Destination:v.hot,Amount:{currency:v.currency,issuer:v.issuer,value:v.supply}},'Token supply issued');state.issued=true;}catch(e){status(e.message||e,'bad');}};
$('#amm').onclick=async()=>{try{const v=values();await ensureAccount(v.hot,'hot');await send({TransactionType:'AMMCreate',Account:v.hot,Amount:{currency:v.currency,issuer:v.issuer,value:v.tokenLiquidity},Amount2:drops(v.xrpLiquidity),TradingFee:feeUnits(v.ammFee)},'XRPL Token/XRP AMM created');state.amm=true;}catch(e){status(e.message||e,'bad');}};
['#hot','#currency','#supply','#token-liquidity','#xrp-liquidity','#amm-fee'].forEach(id=>$(id).addEventListener('input',()=>{['#default-ripple','#no-freeze','#trust','#issue','#amm'].forEach(x=>$(x).disabled=true);}));