#!/usr/bin/env python3
from pathlib import Path
import json

ROOT = Path(__file__).resolve().parents[1]
PAD = ROOT / "impactbased.oneworldz.com"
CRYPTO = ROOT / "cryptoworldz.xyz"
BUILD = "2026-09-07-worldzpad-flash-direct-v1"


def replace(path: Path, old: str, new: str, required: bool = True) -> None:
    text = path.read_text(encoding="utf-8")
    if old not in text:
        if required:
            raise RuntimeError(f"WorldzPad flash patch anchor missing in {path}: {old[:90]!r}")
        return
    path.write_text(text.replace(old, new), encoding="utf-8")


# Foundation surfaces are generated by apply_worldzpad.py first. This layer deliberately
# patches the generated output so the production baseline can keep regenerating safely.
home = PAD / "index.html"
replace(home, "● Foundation live", "● Flash Direct Launch profile ready")
replace(home, "◆ On-chain execution gated", "◆ ZED launch contract armed")
replace(
    home,
    "Every fee-enabled launch reserves a visible impact route with at least one designated charity allocation.",
    "Impact/charity routing remains available as an optional transparent route; it is not required for a WorldzPad launch.",
)
replace(
    home,
    '<div class="route"><span>Mandatory route</span><b>Charity / Impact</b></div>',
    '<div class="route"><span>Optional route</span><b>Charity / Impact</b></div>',
)
replace(home, "LP addition • Buyback • Burn • Treasury • Dev • Team • Marketing • Community • Named wallets • Additional causes.",
        "Charity / Impact • LP addition • Buyback • Burn • Treasury • Dev • Team • Marketing • Community • Named wallets • Additional causes.")
replace(home, '<div class="card launch"><div class="num">#001</div><div><strong>Worldz • $WLDZ</strong><span>Flagship WorldzPad launch. Solana-first design.</span></div><span class="badge gated">DESIGN / COMPLIANCE</span></div>',
        '<div class="card launch"><div class="num">#001</div><div><strong>Worldz • $WLDZ</strong><span>100M fixed supply • Dev-owned genesis • 1% / 1M WLDZ initial LP allocation • Dev-funded ~A$200-equivalent SOL • flash-style virtual liquidity • no bonding curve • SOL fee rewards.</span></div><span class="badge live">CONTRACT READY</span></div>')
replace(home, '<div class="card launch"><div class="num">#002</div><div><strong>Reserved</strong><span>Identity to be selected before minting.</span></div><span class="badge">RESERVED</span></div>',
        '<div class="card launch"><div class="num">#002</div><div><strong>REVIVE • $RVIV</strong><span>Locked WorldzPad launch identity • vanity mint prefix target RVIV…</span></div><span class="badge">LOCKED</span></div>')
replace(home, '<div class="card launch"><div class="num">#003</div><div><strong>Phenix • $PHENIX</strong><span>Future finance and currency infrastructure.</span></div><span class="badge">FUTURE</span></div>',
        '<div class="card launch"><div class="num">#003</div><div><strong>PHENIX • $PNEX</strong><span>Locked WorldzPad launch identity • vanity mint prefix target PNEX…</span></div><span class="badge">LOCKED</span></div>')
replace(home,
        'Public design and simulation can be deployed now. Token minting, swaps, custody, fee withdrawal and automated distribution remain disabled until legal classification, AUSTRAC/ASIC requirements, smart-contract review, wallet authority review and production security tests are completed.',
        'The WorldzPad Flash Direct launch contract is enabled in this repository. ZED receives a machine-readable launch manifest. This public repo contains no private signing material and does not contain the separate Command Centre runtime, so mainnet signing remains an explicit operator action through the external runtime/DEX adapter rather than a hidden website action.')

# Fee Builder: SOL holder rewards remain the required route. Charity/impact is optional.
fee = PAD / "fee-builder" / "index.html"
replace(fee, "Charity / Impact (% of project fee bucket)", "Charity / Impact — optional (% of project fee bucket)")
replace(fee, 'id="charity" type="number" min="0" max="100" step="0.25" value="20"',
             'id="charity" type="number" min="0" max="100" step="0.25" value="0"')
replace(fee, 'id="treasury" type="number" min="0" max="100" step="0.25" value="25"',
             'id="treasury" type="number" min="0" max="100" step="0.25" value="45"')
replace(fee, "SOL Rewards and Charity are mandatory launch routes. WorldzPad validates the distribution before deployment; the project bucket must total exactly 100%.",
             "SOL holder rewards are the mandatory fee route. Charity / Impact is optional. The project distribution bucket must total exactly 100%.")
replace(fee, "const ok=Math.abs(sum-100)<.0001&&n('rewards')>0&&n('charity')>0;", "const ok=Math.abs(sum-100)<.0001&&n('rewards')>0;")
replace(fee, "Configuration must equal 100% with Rewards + Charity above zero", "Configuration must equal 100% with SOL Rewards above zero")

# Launch registry page.
launches = PAD / "launches" / "index.html"
replace(launches, "A launch number does not mean a token is live. Each project advances only when its technical, disclosure, legal, liquidity and security gates are complete.",
        "WorldzPad launch identities and machine-readable launch profiles. Mainnet transactions are signed only by the authorised operator through an external runtime/DEX adapter.")
replace(launches, '<div class="card launch"><div class="num">#001</div><div><strong>Worldz • $WLDZ</strong><span>Flagship Solana-first token and complete WorldzPad demonstration.</span></div><span class="badge gated">NOT MINTED HERE</span></div>',
        '<div class="card launch"><div class="num">#001</div><div><strong>WORLDZ • $WLDZ</strong><span>Flash Direct profile: 100M supply • 1M WLDZ initial LP • Dev-funded ~A$200-equivalent SOL • virtual liquidity clearly separated from real liquidity • no bonding curve • SOL holder rewards.</span></div><span class="badge live">READY</span></div>')
replace(launches, '<div class="card launch"><div class="num">#002</div><div><strong>Reserved</strong><span>Name and ticker intentionally not locked yet.</span></div><span class="badge">RESERVED</span></div>',
        '<div class="card launch"><div class="num">#002</div><div><strong>REVIVE • $RVIV</strong><span>Locked identity. Launch economics may inherit the WorldzPad Flash Direct template when approved by the operator.</span></div><span class="badge">LOCKED</span></div>')
replace(launches, '<div class="card launch"><div class="num">#003</div><div><strong>Phenix • $PHENIX</strong><span>Future global-finance / currency infrastructure concept.</span></div><span class="badge">FUTURE</span></div>',
        '<div class="card launch"><div class="num">#003</div><div><strong>PHENIX • $PNEX</strong><span>Locked identity. Vanity mint prefix target PNEX…</span></div><span class="badge">LOCKED</span></div>')

# Remove personal-benefit wording from the public compliance page; retain the general accounting firewall.
compliance = PAD / "compliance" / "index.html"
replace(compliance,
        "Personal DSP or financially managed funds, business/project money, protocol treasury funds, charity funds and third-party investment must remain separately identifiable. Any personal funding path should be confirmed in writing with the relevant financial manager and Services Australia before assuming it is available for token liquidity or a business investment.",
        "Personal funds, project money, protocol treasury funds, charity funds and third-party investment must remain separately identifiable and accurately recorded. Dev-funded liquidity must be identified as Dev funds rather than customer or charity money.")

# ZED public bridge reflects the executable contract boundary without pretending this repo owns the bot runtime.
zed = CRYPTO / "worldzpad" / "index.html"
replace(zed, "The public integration boundary for WorldzPad. It exposes the launch system to CryptoWorldz without pretending the separate Command Centre runtime has been modified by this repository.",
        "ZED's public WorldzPad launch boundary. The Flash Direct launch contract is machine-readable and ready for the separate Command Centre runtime to consume without embedding private signing material in this public repository.")
replace(zed, "Mandatory impact route and public cause accounting.", "Optional impact/charity route and public cause accounting when enabled.")
replace(zed,
        "Runtime status: this GitHub repository controls the public CryptoWorldz/WorldzPad surfaces and deployment. The separate Command Centre runtime is linked but its source is not present in this connected repository, so no claim is made that its internal code was changed by this release.",
        "Runtime status: LAUNCH CONTRACT READY. This repository publishes the ZED command manifest and WorldzPad configuration. The separate Command Centre runtime source/private signer is not in this repository; mainnet signing therefore remains external and explicit.")
replace(zed, "</section><section class=\"section\"><div class=\"warning\">Runtime status:",
        "</section><section class=\"section\"><div class=\"good\"><strong>#001 WLDZ Flash Direct</strong><br>100M fixed supply • 1% / 1M WLDZ initial LP • Dev-funded ~A$200-equivalent SOL • virtual liquidity • no bonding curve • 0.50–4.00% fee • WorldzPad 10% of collected fees • SOL holder rewards.</div></section><section class=\"section\"><div class=\"warning\">Runtime status:", required=False)

# Machine-readable rules shared by WorldzPad and the ZED bridge.
rules = {
    "version": "1.1-flash-direct",
    "network": "solana",
    "operator": {
        "authorizedDeployer": "JayJayTeamDev",
        "deploymentAuthority": "sole_authorized_deployer_under_worldzpad"
    },
    "execution": {
        "commandProfileEnabled": True,
        "mainnetAutoExecutionFromPublicRepo": False,
        "privateSigningMaterialInRepository": False,
        "commandCentreRuntimeSourceInRepository": False,
        "signingMode": "explicit_external_runtime_operator_action"
    },
    "launchMode": {
        "id": "flash_direct_virtual_liquidity",
        "bondingCurve": False,
        "graduationRequired": False,
        "instantDexMarket": True,
        "virtualLiquidityMustBeSeparatedFromRealLiquidity": True,
        "realValueDisclosureRequired": True
    },
    "feePolicy": {
        "minPercent": 0.50,
        "maxPercent": 4.00,
        "incrementPercent": 0.25,
        "protocolShareOfCollectedFeesPercent": 10,
        "protocolShareOfTokenSupplyPercent": 0,
        "mandatoryRoutes": ["sol_holder_rewards"],
        "optionalRoutes": ["charity_impact", "lp_addition", "buyback", "burn", "treasury", "dev", "team", "marketing", "community", "named_wallet"],
        "rewardCadences": ["hourly", "6_hours", "daily", "weekly", "monthly", "yearly"],
        "guaranteedReturn": False,
        "guaranteedApy": False
    },
    "launchRegistry": [
        {
            "number": 1,
            "name": "WORLDZ",
            "ticker": "WLDZ",
            "status": "command_contract_ready",
            "vanityMintPrefixTarget": "WLDZ",
            "totalSupply": 100000000,
            "decimals": 9,
            "genesisDevOwnershipPercent": 100,
            "initialLpTokenPercent": 1,
            "initialLpTokenAmount": 1000000,
            "devSelfLpAudTarget": 200,
            "devSelfLpSolAmount": "resolve_at_execution_time_from_AUD_target",
            "presale": False,
            "customerCustody": False,
            "holderSolRewards": True,
            "rewardSource": "configured_collected_token_fee_revenue",
            "buyerRiskDisclosureRequired": True
        },
        {"number": 2, "name": "REVIVE", "ticker": "RVIV", "status": "identity_locked", "vanityMintPrefixTarget": "RVIV"},
        {"number": 3, "name": "PHENIX", "ticker": "PNEX", "status": "identity_locked", "vanityMintPrefixTarget": "PNEX"}
    ]
}

for target in [PAD / "worldzpad.rules.json", PAD / "worldzpad.launch-contract.json", CRYPTO / "worldzpad" / "worldzpad.launch-contract.json"]:
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(json.dumps(rules, indent=2) + "\n", encoding="utf-8")

# Operator-facing launch console is intentionally declarative: it exposes the exact contract
# ZED should consume and does not attempt to sign from a public webpage.
console_dir = PAD / "launch-console"
console_dir.mkdir(parents=True, exist_ok=True)
console_html = f'''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>WorldzPad Flash Direct™</title><meta name="description" content="WorldzPad Flash Direct launch contract for ZED Command Centre."><link rel="stylesheet" href="/worldzpad.css"></head><body data-oneworldz-build="{BUILD}"><nav class="nav"><a href="/">WorldzPad</a><a class="brand" href="/launch-console/">Launch Console</a><a href="/fee-builder/">Fee Builder</a><a href="/real-value/">Real Value</a><a href="https://cryptoworldz.xyz/worldzpad/">ZED Bridge</a></nav><main class="shell"><section class="hero"><p class="eyebrow">ZED Command Contract</p><h1>FLASH <span>DIRECT™</span></h1><p class="lead">Instant DEX launch architecture with virtual liquidity plus real Dev-funded LP. No bonding curve. No presale. No hidden custody.</p><div class="badges"><span class="badge live">● CONTRACT READY</span><span class="badge">#001 WLDZ</span><span class="badge">Sole deployer: JayJayTeamDev</span></div></section><section class="section"><h2>#001 WORLDZ $WLDZ</h2><div class="grid"><div class="card"><strong>Supply</strong><div class="kpi">100M</div><p>Fixed genesis supply. Dev-owned at creation.</p></div><div class="card"><strong>Initial LP allocation</strong><div class="kpi">1%</div><p>1,000,000 WLDZ plus Dev-funded ~A$200-equivalent SOL target.</p></div><div class="card"><strong>Launch technology</strong><div class="kpi">FLASH</div><p>Virtual-liquidity direct DEX profile. Bonding curve: NO. Graduation: NO.</p></div></div></section><section class="section"><h2>Fee engine</h2><div class="grid two"><div class="card"><div class="route"><span>WorldzPad fee range</span><b>0.50–4.00%</b></div><div class="route"><span>Step</span><b>0.25%</b></div><div class="route"><span>WorldzPad share</span><b>10% of collected fees</b></div><div class="route"><span>Holder route</span><b>SOL rewards</b></div></div><div class="card"><strong>ImpactBased</strong><p>Charity / Impact remains available but is optional for this launch profile.</p><strong>Risk</strong><p>No guaranteed return, APY or price. Virtual liquidity must never be displayed as real withdrawable liquidity.</p></div></div></section><section class="section"><div class="good"><strong>ZED integration state</strong><br>Machine-readable contract published at <span class="mono">/worldzpad.launch-contract.json</span>. This repository does not store the private signer or separate Command Centre runtime; it therefore cannot silently mint or sign mainnet transactions.</div></section></main><footer class="footer">WorldzPad™ • ZED • AUTO • G.R.A.C.E. • Real Value™</footer></body></html>'''
(console_dir / "index.html").write_text(console_html, encoding="utf-8")

# Add Launch Console to all WorldzPad navs after generation.
for page in PAD.rglob("index.html"):
    text = page.read_text(encoding="utf-8")
    if "/launch-console/" not in text and "</nav>" in text:
        text = text.replace("</nav>", '<a href="/launch-console/">Launch Console</a></nav>', 1)
        page.write_text(text, encoding="utf-8")

# Build-time invariants: a stale mandatory-charity or stale ticker must fail the deployment.
checks = {
    "home WLDZ ready": "CONTRACT READY" in home.read_text(encoding="utf-8"),
    "RVIV locked": "$RVIV" in home.read_text(encoding="utf-8"),
    "PNEX locked": "$PNEX" in home.read_text(encoding="utf-8"),
    "charity optional": "Charity / Impact — optional" in fee.read_text(encoding="utf-8"),
    "no bonding curve": rules["launchMode"]["bondingCurve"] is False,
    "100M supply": rules["launchRegistry"][0]["totalSupply"] == 100000000,
    "1M LP": rules["launchRegistry"][0]["initialLpTokenAmount"] == 1000000,
    "10pct fee share": rules["feePolicy"]["protocolShareOfCollectedFeesPercent"] == 10,
    "4pct hard cap": rules["feePolicy"]["maxPercent"] == 4.00,
}
failed = [name for name, ok in checks.items() if not ok]
if failed:
    raise RuntimeError("WORLDZPAD_FLASH_CONTRACT=FAIL " + ", ".join(failed))
print("WORLDZPAD_FLASH_CONTRACT=PASS launch=001 ticker=WLDZ supply=100000000 lp=1000000 bonding_curve=0 protocol_fee_share=10 runtime_signer=external")
