-- REXSECURE ULTIMATE™ confidence, evidence and appeals layer.
-- Production migration version: 20261003221922
-- Additive: existing SecureGuard enforcement and historical events remain unchanged.

create table if not exists public.secureguard_intel_sources (
  source_key text primary key,
  display_name text not null,
  source_type text not null
    check (source_type in ('provider','worldz_adjudication','admin_report','behavior','pattern','identity')),
  base_weight integer not null
    check (base_weight between 0 and 100),
  max_auto_action text not null default 'watch'
    check (max_auto_action in ('observe','watch','quarantine','local_block','network_block')),
  requires_corroboration boolean not null default true,
  freshness_hours integer
    check (freshness_hours is null or freshness_hours between 1 and 87600),
  attribution text not null default '',
  enabled boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

insert into public.secureguard_intel_sources
  (source_key,display_name,source_type,base_weight,max_auto_action,requires_corroboration,freshness_hours,attribution)
values
  ('worldz_owner_adjudication','Worldz Security Adjudication','worldz_adjudication',100,'network_block',false,null,'Human-reviewed Worldz security decision'),
  ('cas','Combot Anti-Spam (CAS)','provider',85,'quarantine',true,168,'Powered by CAS • https://cas.chat'),
  ('worldz_admin_report','Worldz Admin Evidence Report','admin_report',45,'watch',true,720,'Human-submitted evidence; not a verdict'),
  ('pattern_match','REX Pattern Guard Match','pattern',55,'quarantine',true,168,'Local message-pattern evidence'),
  ('identity_match','REX Identity Guard Match','identity',35,'watch',true,24,'Identity similarity signal; Telegram ID remains authoritative'),
  ('local_behavior','REX Local Behaviour Signal','behavior',30,'watch',true,24,'Flood/link/local behaviour telemetry')
on conflict (source_key) do update set
  display_name=excluded.display_name,
  source_type=excluded.source_type,
  base_weight=excluded.base_weight,
  max_auto_action=excluded.max_auto_action,
  requires_corroboration=excluded.requires_corroboration,
  freshness_hours=excluded.freshness_hours,
  attribution=excluded.attribution,
  enabled=true,
  updated_at=now();

create table if not exists public.secureguard_evidence (
  id bigint generated by default as identity primary key,
  subject_telegram_id bigint not null check (subject_telegram_id > 0),
  source_key text not null references public.secureguard_intel_sources(source_key) on update cascade on delete restrict,
  source_reference text,
  signal_type text not null default 'risk_signal',
  severity integer not null default 50 check (severity between 0 and 100),
  source_confidence integer not null default 50 check (source_confidence between 0 and 100),
  evidence_url text,
  evidence text not null default '',
  metadata jsonb not null default '{}'::jsonb,
  status text not null default 'active' check (status in ('active','dismissed','expired')),
  observed_at timestamptz not null default now(),
  expires_at timestamptz,
  created_by_telegram_id bigint,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists secureguard_evidence_subject_active_idx
  on public.secureguard_evidence(subject_telegram_id,status,observed_at desc);
create index if not exists secureguard_evidence_source_idx
  on public.secureguard_evidence(source_key,status,observed_at desc);

create table if not exists public.secureguard_appeals (
  id bigint generated by default as identity primary key,
  subject_telegram_id bigint not null check (subject_telegram_id > 0),
  appellant_telegram_id bigint not null check (appellant_telegram_id > 0),
  chat_id bigint,
  reason text not null,
  evidence_url text,
  evidence text not null default '',
  status text not null default 'pending'
    check (status in ('pending','under_review','granted','denied','withdrawn')),
  reviewer_telegram_id bigint,
  review_note text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  resolved_at timestamptz
);
create unique index if not exists secureguard_appeals_one_active_subject_idx
  on public.secureguard_appeals(subject_telegram_id)
  where status in ('pending','under_review');
create index if not exists secureguard_appeals_status_idx
  on public.secureguard_appeals(status,created_at asc);

create table if not exists public.secureguard_assessments (
  id bigint generated by default as identity primary key,
  subject_telegram_id bigint not null check (subject_telegram_id > 0),
  risk_score integer not null check (risk_score between 0 and 100),
  risk_band text not null
    check (risk_band in ('clear','watch','quarantine','block_candidate','blocked')),
  recommended_action text not null
    check (recommended_action in ('allow','watch','quarantine','local_block','network_block')),
  source_count integer not null default 0 check (source_count >= 0),
  independent_source_count integer not null default 0 check (independent_source_count >= 0),
  active_appeal boolean not null default false,
  rationale jsonb not null default '{}'::jsonb,
  assessed_at timestamptz not null default now()
);
create index if not exists secureguard_assessments_subject_idx
  on public.secureguard_assessments(subject_telegram_id,assessed_at desc);

alter table public.secureguard_intel_sources enable row level security;
alter table public.secureguard_evidence enable row level security;
alter table public.secureguard_appeals enable row level security;
alter table public.secureguard_assessments enable row level security;

revoke all on public.secureguard_intel_sources, public.secureguard_evidence,
  public.secureguard_appeals, public.secureguard_assessments
from public, authenticated;

grant select,insert,update,delete on public.secureguard_intel_sources,
  public.secureguard_evidence, public.secureguard_appeals, public.secureguard_assessments
to service_role;

grant select,insert,update,delete on public.secureguard_intel_sources,
  public.secureguard_evidence, public.secureguard_appeals, public.secureguard_assessments
to anon;

grant usage,select on sequence
  public.secureguard_evidence_id_seq,
  public.secureguard_appeals_id_seq,
  public.secureguard_assessments_id_seq
to service_role, anon;

drop policy if exists "zed_runtime_bridge" on public.secureguard_intel_sources;
create policy "zed_runtime_bridge" on public.secureguard_intel_sources
for all to anon
using (public.zed_runtime_authorized())
with check (public.zed_runtime_authorized());

drop policy if exists "zed_runtime_bridge" on public.secureguard_evidence;
create policy "zed_runtime_bridge" on public.secureguard_evidence
for all to anon
using (public.zed_runtime_authorized())
with check (public.zed_runtime_authorized());

drop policy if exists "zed_runtime_bridge" on public.secureguard_appeals;
create policy "zed_runtime_bridge" on public.secureguard_appeals
for all to anon
using (public.zed_runtime_authorized())
with check (public.zed_runtime_authorized());

drop policy if exists "zed_runtime_bridge" on public.secureguard_assessments;
create policy "zed_runtime_bridge" on public.secureguard_assessments
for all to anon
using (public.zed_runtime_authorized())
with check (public.zed_runtime_authorized());

comment on table public.secureguard_intel_sources is
'REXSECURE source policy registry. Source presence alone is never a verdict.';
comment on table public.secureguard_evidence is
'REXSECURE subject-level evidence. Evidence is scored and can be dismissed/expired without deleting history.';
comment on table public.secureguard_appeals is
'REXSECURE appeal queue. A pending appeal freezes escalation to permanent network block.';
comment on table public.secureguard_assessments is
'REXSECURE explainable risk snapshots. Scores recommend actions; permanent network blocks require human adjudication.';
