create table if not exists public.raaiiidd_creator_requests (
  id bigint generated by default as identity primary key,
  grace_post_id uuid not null unique references public.grace_posts(id) on delete cascade,
  creator_telegram_id bigint not null,
  desired_reward_points integer not null default 10 check (desired_reward_points between 0 and 100),
  target_url text,
  status text not null default 'pending' check (status in ('pending','approved','rejected')),
  mission_id bigint references public.missions(id) on delete set null,
  review_note text,
  reviewed_by bigint,
  reviewed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists raaiiidd_creator_requests_status_created_idx on public.raaiiidd_creator_requests(status, created_at);
create index if not exists raaiiidd_creator_requests_creator_idx on public.raaiiidd_creator_requests(creator_telegram_id, created_at desc);
create index if not exists raaiiidd_creator_requests_mission_idx on public.raaiiidd_creator_requests(mission_id) where mission_id is not null;
alter table public.raaiiidd_creator_requests enable row level security;
revoke all on table public.raaiiidd_creator_requests from anon, authenticated;
grant all on table public.raaiiidd_creator_requests to service_role;
grant usage, select on sequence public.raaiiidd_creator_requests_id_seq to service_role;

create table if not exists public.real_world_hero_applications (
  id bigint generated by default as identity primary key,
  telegram_id bigint not null,
  display_name text not null check (char_length(display_name) between 2 and 120),
  story text not null check (char_length(story) between 20 and 3000),
  evidence_url text not null,
  status text not null default 'pending' check (status in ('pending','approved','rejected')),
  review_note text,
  reviewed_by bigint,
  reviewed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists real_world_hero_applications_status_created_idx on public.real_world_hero_applications(status, created_at);
create index if not exists real_world_hero_applications_member_idx on public.real_world_hero_applications(telegram_id, created_at desc);
alter table public.real_world_hero_applications enable row level security;
revoke all on table public.real_world_hero_applications from anon, authenticated;
grant all on table public.real_world_hero_applications to service_role;
grant usage, select on sequence public.real_world_hero_applications_id_seq to service_role;

create table if not exists public.real_world_heroes (
  id bigint generated by default as identity primary key,
  application_id bigint unique references public.real_world_hero_applications(id) on delete set null,
  telegram_id bigint,
  slug text not null unique,
  display_name text not null,
  summary text not null,
  status text not null default 'published' check (status in ('published','hidden')),
  approved_by bigint,
  approved_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists real_world_heroes_status_approved_idx on public.real_world_heroes(status, approved_at desc);
alter table public.real_world_heroes enable row level security;
revoke all on table public.real_world_heroes from anon, authenticated;
grant all on table public.real_world_heroes to service_role;
grant usage, select on sequence public.real_world_heroes_id_seq to service_role;

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('raaiiidd-drafts', 'raaiiidd-drafts', false, 5242880, array['image/webp','image/png','image/jpeg'])
on conflict (id) do update set public = excluded.public, file_size_limit = excluded.file_size_limit, allowed_mime_types = excluded.allowed_mime_types;
