create table if not exists public.project_wallets (
  purpose text primary key check (purpose in ('dev','investment','treasury','rewards')),
  label text not null,
  network text not null default 'solana' check (network = 'solana'),
  public_address text check (public_address is null or char_length(public_address) between 32 and 44),
  wallet_type text not null check (wallet_type in ('owner','multisig')),
  control_policy text not null,
  status text not null default 'planned' check (status in ('planned','active','disabled')),
  contribution_enabled boolean not null default false,
  accepted_assets text[] not null default array['USDC','SOL']::text[],
  notes text not null default '',
  updated_by bigint,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists project_wallets_unique_address
  on public.project_wallets(public_address)
  where public_address is not null;

insert into public.project_wallets (
  purpose, label, wallet_type, control_policy, contribution_enabled, accepted_assets, notes
) values
  ('dev', 'CryptoWorldz Dev & Launch Wallet', 'owner', 'Owner-controlled. Launch preparation only. No private key is stored by Zed.', true, array['USDC','SOL']::text[], 'For approved launch costs and development support.'),
  ('investment', 'JayJayTeamDev Owner Investment Wallet', 'owner', 'Single transparent buy-only wallet. No subwallet rotation or randomised activity.', false, array['USDC']::text[], 'USDC-funded owner investment DCA. AUD $100 weekly funding ceiling.'),
  ('treasury', 'CryptoWorldz Treasury Multisig', 'multisig', 'Planned Squads 2-of-3 vault for JayJayTeamDev, Stepper and Remedy.', true, array['USDC','SOL']::text[], 'Use the Squads Vault address, never the multisig account address.'),
  ('rewards', 'CryptoWorldz Reward Wallet', 'owner', 'Separate owner-controlled reward settlement wallet. Manual payouts only.', true, array['USDC','SOL']::text[], 'USDC is the default reward asset; members may choose equal-value SOL.')
on conflict (purpose) do update set
  label = excluded.label,
  wallet_type = excluded.wallet_type,
  control_policy = excluded.control_policy,
  contribution_enabled = excluded.contribution_enabled,
  accepted_assets = excluded.accepted_assets,
  notes = excluded.notes,
  updated_at = now();

create table if not exists public.project_wallet_contributions (
  id bigint generated by default as identity primary key,
  purpose text not null references public.project_wallets(purpose) on update cascade on delete restrict,
  telegram_id bigint not null,
  asset text not null check (asset in ('USDC','SOL')),
  amount numeric(30,9) not null check (amount > 0),
  transaction_signature text not null unique check (char_length(transaction_signature) between 40 and 100),
  recipient_address text not null check (char_length(recipient_address) between 32 and 44),
  sender_address text,
  slot bigint,
  block_time timestamptz,
  status text not null default 'verified' check (status in ('verified','rejected')),
  created_at timestamptz not null default now()
);

create index if not exists project_wallet_contributions_member_idx
  on public.project_wallet_contributions(telegram_id, created_at desc);
create index if not exists project_wallet_contributions_purpose_idx
  on public.project_wallet_contributions(purpose, created_at desc);

create table if not exists public.investment_funding_settings (
  id text primary key default 'global' check (id = 'global'),
  network text not null default 'solana' check (network = 'solana'),
  funding_asset text not null default 'USDC' check (funding_asset = 'USDC'),
  weekly_target_aud_cents integer not null default 10000 check (weekly_target_aud_cents between 0 and 10000),
  timezone text not null default 'Australia/Sydney',
  auto_transfer_enabled boolean not null default false check (auto_transfer_enabled = false),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

insert into public.investment_funding_settings(id)
values ('global')
on conflict (id) do update set
  weekly_target_aud_cents = 10000,
  funding_asset = 'USDC',
  auto_transfer_enabled = false,
  updated_at = now();

create table if not exists public.investment_funding_deposits (
  id bigint generated by default as identity primary key,
  funding_week_start date not null,
  aud_value_cents integer not null check (aud_value_cents > 0),
  usdc_amount numeric(30,6) not null check (usdc_amount > 0),
  transaction_signature text not null unique check (char_length(transaction_signature) between 40 and 100),
  recorded_by bigint not null,
  status text not null default 'recorded' check (status in ('recorded','verified','rejected')),
  created_at timestamptz not null default now()
);

create index if not exists investment_funding_week_idx
  on public.investment_funding_deposits(funding_week_start, created_at desc);

alter table public.auto_dca_settings
  add column if not exists allowed_input_currency text not null default 'USDC' check (allowed_input_currency = 'USDC'),
  add column if not exists max_buys_per_day integer not null default 6 check (max_buys_per_day between 1 and 6),
  add column if not exists amount_presets jsonb not null default '[2,3,5,7,10,15]'::jsonb check (jsonb_typeof(amount_presets) = 'array'),
  add column if not exists weekly_budget_aud_cents integer not null default 10000 check (weekly_budget_aud_cents between 0 and 10000),
  add column if not exists buy_only boolean not null default true check (buy_only = true),
  add column if not exists multiwallet_enabled boolean not null default false check (multiwallet_enabled = false),
  add column if not exists randomized_execution boolean not null default false check (randomized_execution = false);

update public.auto_dca_settings
set enabled = false,
    paused = true,
    emergency_stop = true,
    execution_enabled = false,
    max_order_amount = 15,
    max_daily_amount = 30,
    max_weekly_amount = 100,
    max_monthly_amount = 400,
    min_interval_minutes = 240,
    max_slippage_bps = 200,
    max_price_impact_bps = 300,
    allowed_input_currency = 'USDC',
    max_buys_per_day = 6,
    amount_presets = '[2,3,5,7,10,15]'::jsonb,
    weekly_budget_aud_cents = 10000,
    buy_only = true,
    multiwallet_enabled = false,
    randomized_execution = false,
    updated_at = now()
where id = 1;

create or replace function public.current_investment_week_start()
returns date
language sql
stable
as $$
  select date_trunc('week', timezone('Australia/Sydney', now()))::date
$$;

create or replace function public.record_investment_funding_deposit(
  p_aud_value_cents integer,
  p_usdc_amount numeric,
  p_transaction_signature text,
  p_recorded_by bigint
)
returns table(outcome text, weekly_recorded_aud_cents integer, weekly_remaining_aud_cents integer)
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_settings public.investment_funding_settings%rowtype;
  v_week date := public.current_investment_week_start();
  v_used integer;
begin
  select * into v_settings from public.investment_funding_settings where id = 'global' for update;
  select coalesce(sum(aud_value_cents), 0)::integer into v_used
  from public.investment_funding_deposits
  where funding_week_start = v_week and status in ('recorded','verified');

  if p_aud_value_cents is null or p_aud_value_cents <= 0 or p_usdc_amount is null or p_usdc_amount <= 0 then
    return query select 'invalid_amount'::text, v_used, greatest(v_settings.weekly_target_aud_cents - v_used, 0);
    return;
  end if;
  if exists (select 1 from public.investment_funding_deposits where transaction_signature = p_transaction_signature) then
    return query select 'duplicate_transaction'::text, v_used, greatest(v_settings.weekly_target_aud_cents - v_used, 0);
    return;
  end if;
  if v_used + p_aud_value_cents > v_settings.weekly_target_aud_cents then
    return query select 'weekly_target_exceeded'::text, v_used, greatest(v_settings.weekly_target_aud_cents - v_used, 0);
    return;
  end if;

  insert into public.investment_funding_deposits(
    funding_week_start, aud_value_cents, usdc_amount, transaction_signature, recorded_by
  ) values (v_week, p_aud_value_cents, p_usdc_amount, p_transaction_signature, p_recorded_by);
  v_used := v_used + p_aud_value_cents;
  return query select 'recorded'::text, v_used, greatest(v_settings.weekly_target_aud_cents - v_used, 0);
end;
$$;

create or replace function public.get_investment_funding_status()
returns table(
  funding_week_start date,
  funding_asset text,
  weekly_target_aud_cents integer,
  recorded_aud_cents integer,
  remaining_aud_cents integer,
  auto_transfer_enabled boolean
)
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_settings public.investment_funding_settings%rowtype;
  v_week date := public.current_investment_week_start();
  v_used integer;
begin
  select * into v_settings from public.investment_funding_settings where id = 'global';
  select coalesce(sum(d.aud_value_cents), 0)::integer into v_used
  from public.investment_funding_deposits d
  where d.funding_week_start = v_week and d.status in ('recorded','verified');
  return query select v_week, v_settings.funding_asset, v_settings.weekly_target_aud_cents,
    v_used, greatest(v_settings.weekly_target_aud_cents - v_used, 0), v_settings.auto_transfer_enabled;
end;
$$;

create or replace function public.claim_auto_dca_schedule(p_worker_id text)
returns setof public.auto_dca_schedules
language plpgsql
security definer
set search_path = ''
as $$
declare
  claimed public.auto_dca_schedules%rowtype;
  settings public.auto_dca_settings%rowtype;
  v_today_count integer := 0;
  v_today_spent numeric := 0;
  v_week_spent numeric := 0;
begin
  if p_worker_id is null or char_length(trim(p_worker_id)) < 3 then return; end if;

  select * into settings from public.auto_dca_settings where id = 1 for update;
  if not found or not settings.enabled or not settings.execution_enabled or settings.paused or settings.emergency_stop or settings.wallet_address is null then return; end if;
  if settings.multiwallet_enabled or settings.randomized_execution or not settings.buy_only then return; end if;

  select count(*)::integer, coalesce(sum(input_amount),0),
    coalesce(sum(input_amount) filter (where started_at >= date_trunc('week', now())),0)
  into v_today_count, v_today_spent, v_week_spent
  from public.auto_dca_executions
  where status = 'success'
    and started_at >= date_trunc('day', now());

  if v_today_count >= settings.max_buys_per_day or v_today_spent >= settings.max_daily_amount or v_week_spent >= settings.max_weekly_amount then return; end if;

  select * into claimed
  from public.auto_dca_schedules
  where status = 'active'
    and input_currency = settings.allowed_input_currency
    and amount_per_buy <= settings.max_order_amount
    and v_today_spent + amount_per_buy <= settings.max_daily_amount
    and v_week_spent + amount_per_buy <= settings.max_weekly_amount
    and completed_buys < order_count
    and next_run_at is not null and next_run_at <= now()
    and (locked_until is null or locked_until < now())
  order by next_run_at asc, created_at asc
  for update skip locked
  limit 1;
  if not found then return; end if;

  update public.auto_dca_schedules
  set locked_by = p_worker_id,
      locked_until = now() + interval '2 minutes',
      started_at = coalesce(started_at, now()),
      updated_at = now()
  where id = claimed.id
  returning * into claimed;
  return next claimed;
end;
$$;

alter table public.project_wallets enable row level security;
alter table public.project_wallet_contributions enable row level security;
alter table public.investment_funding_settings enable row level security;
alter table public.investment_funding_deposits enable row level security;

revoke all on table public.project_wallets from anon, authenticated;
revoke all on table public.project_wallet_contributions from anon, authenticated;
revoke all on table public.investment_funding_settings from anon, authenticated;
revoke all on table public.investment_funding_deposits from anon, authenticated;
revoke all on sequence public.project_wallet_contributions_id_seq from anon, authenticated;
revoke all on sequence public.investment_funding_deposits_id_seq from anon, authenticated;
revoke all on function public.record_investment_funding_deposit(integer,numeric,text,bigint) from public;
revoke all on function public.get_investment_funding_status() from public;
grant execute on function public.record_investment_funding_deposit(integer,numeric,text,bigint) to service_role;
grant execute on function public.get_investment_funding_status() to service_role;
grant execute on function public.claim_auto_dca_schedule(text) to service_role;
