-- Diamond Buy Auto SAFE LOCKED foundation.
-- Additive only: no existing Zed, user, wallet, mission, reward or governance data is changed.
-- This release deliberately cannot record an executed blockchain transaction.

create table if not exists public.auto_settings (
  id smallint primary key default 1 check (id = 1),
  mode text not null default 'safe_locked' check (mode = 'safe_locked'),
  execution_enabled boolean not null default false check (execution_enabled = false),
  signing_enabled boolean not null default false check (signing_enabled = false),
  paused boolean not null default true,
  emergency_stop boolean not null default true,
  manual_confirmation_required boolean not null default true check (manual_confirmation_required = true),
  max_order_amount numeric(30,9) not null default 0 check (max_order_amount >= 0),
  max_daily_amount numeric(30,9) not null default 0 check (max_daily_amount >= 0),
  max_weekly_amount numeric(30,9) not null default 0 check (max_weekly_amount >= 0),
  max_monthly_amount numeric(30,9) not null default 0 check (max_monthly_amount >= 0),
  min_interval_minutes integer not null default 60 check (min_interval_minutes >= 1),
  max_slippage_bps integer not null default 100 check (max_slippage_bps between 0 and 1000),
  max_price_impact_bps integer not null default 100 check (max_price_impact_bps between 0 and 1000),
  min_liquidity_usd numeric(30,2) not null default 0 check (min_liquidity_usd >= 0),
  updated_by bigint,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

insert into public.auto_settings (id)
values (1)
on conflict (id) do nothing;

create table if not exists public.auto_tokens (
  id bigint generated by default as identity primary key,
  network text not null check (network = 'solana'),
  token_mint text not null check (char_length(token_mint) between 32 and 44),
  symbol text not null check (char_length(symbol) between 1 and 20),
  display_name text not null check (char_length(display_name) between 1 and 120),
  status text not null default 'draft' check (status in ('draft','allowlisted','disabled')),
  approved_by bigint,
  approved_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (network, token_mint)
);

create table if not exists public.auto_schedules (
  id bigint generated by default as identity primary key,
  auto_token_id bigint not null references public.auto_tokens(id) on delete restrict,
  requested_by bigint not null,
  status text not null default 'simulation_only' check (status in ('draft','simulation_only','paused','cancelled')),
  currency text not null check (currency in ('SOL','USDC')),
  amount_per_order numeric(30,9) not null check (amount_per_order > 0),
  order_count integer not null check (order_count between 1 and 365),
  interval_minutes integer not null check (interval_minutes >= 1),
  slippage_bps integer not null check (slippage_bps between 0 and 1000),
  price_impact_bps integer not null check (price_impact_bps between 0 and 1000),
  execution_enabled boolean not null default false check (execution_enabled = false),
  starts_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.auto_simulation_runs (
  id bigint generated by default as identity primary key,
  requested_by bigint not null,
  network text,
  token_mint text,
  currency text,
  amount_per_order numeric(30,9),
  order_count integer,
  total_amount numeric(30,9),
  interval_minutes integer,
  slippage_bps integer,
  price_impact_bps integer,
  liquidity_usd numeric(30,2),
  accepted boolean not null default false,
  validation_errors jsonb not null default '[]'::jsonb,
  request_payload jsonb not null default '{}'::jsonb,
  result_payload jsonb not null default '{}'::jsonb,
  execution_attempted boolean not null default false check (execution_attempted = false),
  created_at timestamptz not null default now()
);

create table if not exists public.auto_transactions (
  id bigint generated by default as identity primary key,
  simulation_run_id bigint references public.auto_simulation_runs(id) on delete restrict,
  execution_status text not null default 'not_executed' check (execution_status in ('not_executed','cancelled')),
  transaction_signature text check (transaction_signature is null),
  signed_payload text check (signed_payload is null),
  private_key_reference text check (private_key_reference is null),
  created_at timestamptz not null default now()
);

create table if not exists public.auto_audit_log (
  id bigint generated by default as identity primary key,
  action text not null check (char_length(action) between 1 and 100),
  actor_telegram_id bigint,
  service_mode text not null default 'safe_locked' check (service_mode = 'safe_locked'),
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists auto_tokens_status_idx on public.auto_tokens(status, network);
create index if not exists auto_schedules_status_idx on public.auto_schedules(status, created_at desc);
create index if not exists auto_simulation_runs_requested_idx on public.auto_simulation_runs(requested_by, created_at desc);
create index if not exists auto_audit_log_created_idx on public.auto_audit_log(created_at desc);

alter table public.auto_settings enable row level security;
alter table public.auto_tokens enable row level security;
alter table public.auto_schedules enable row level security;
alter table public.auto_simulation_runs enable row level security;
alter table public.auto_transactions enable row level security;
alter table public.auto_audit_log enable row level security;

revoke all on table public.auto_settings from anon, authenticated;
revoke all on table public.auto_tokens from anon, authenticated;
revoke all on table public.auto_schedules from anon, authenticated;
revoke all on table public.auto_simulation_runs from anon, authenticated;
revoke all on table public.auto_transactions from anon, authenticated;
revoke all on table public.auto_audit_log from anon, authenticated;

revoke all on sequence public.auto_tokens_id_seq from anon, authenticated;
revoke all on sequence public.auto_schedules_id_seq from anon, authenticated;
revoke all on sequence public.auto_simulation_runs_id_seq from anon, authenticated;
revoke all on sequence public.auto_transactions_id_seq from anon, authenticated;
revoke all on sequence public.auto_audit_log_id_seq from anon, authenticated;

comment on table public.auto_settings is 'Owner-controlled Diamond Buy Auto settings. SAFE LOCKED MODE only; execution and signing are constrained false.';
comment on table public.auto_simulation_runs is 'Validated simulation records only. No transaction construction, signing, scheduling or submission.';
comment on table public.auto_transactions is 'Non-execution registry constrained to null signatures, null signed payloads and null private-key references.';
