-- Working Mini App operations. Additive and duplicate-safe; existing data is preserved.
alter table public.treasury_contributions add column if not exists sender_address text;
alter table public.treasury_contributions add column if not exists slot bigint;
alter table public.treasury_contributions add column if not exists block_time timestamptz;
alter table public.treasury_contributions add column if not exists verified_at timestamptz;

alter table public.reward_transactions drop constraint if exists reward_transactions_reward_type_check;
alter table public.reward_transactions add constraint reward_transactions_reward_type_check
  check (reward_type in ('mission','admin_adjustment','bonus','event','airdrop','governance','contribution')) not valid;
alter table public.reward_transactions validate constraint reward_transactions_reward_type_check;

create table if not exists public.partner_publications (
  id bigint generated by default as identity primary key,
  publication_type text not null check (publication_type in ('recap','announcement','partner_update')),
  title text not null,
  body text not null,
  source_url text,
  status text not null default 'draft' check (status in ('draft','approved','published','rejected')),
  created_by bigint not null,
  reviewed_by bigint,
  reviewed_at timestamptz,
  published_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists partner_publications_status_idx on public.partner_publications(status, created_at desc);
alter table public.partner_publications enable row level security;
revoke all on public.partner_publications from anon, authenticated;
grant all on public.partner_publications to service_role;

create or replace function public.record_verified_contribution(
  p_treasury_account_id bigint, p_telegram_id bigint, p_transaction_signature text,
  p_asset text, p_amount numeric, p_sender_address text, p_slot bigint,
  p_block_time timestamptz, p_points integer
) returns table(outcome text, contribution_id bigint, points_awarded integer, new_points integer)
language plpgsql security definer set search_path = '' as $$
declare v_id bigint; v_points integer;
begin
  if p_points < 0 or p_amount <= 0 then raise exception 'invalid contribution'; end if;
  if not exists (select 1 from public.users where telegram_id = p_telegram_id) then
    return query select 'unregistered'::text, null::bigint, 0, null::integer; return;
  end if;
  insert into public.treasury_contributions(treasury_account_id,transaction_signature,telegram_id,asset,amount,status,points_awarded,confirmed_by,confirmed_at,verified_at,sender_address,slot,block_time)
  values(p_treasury_account_id,p_transaction_signature,p_telegram_id,p_asset,p_amount,'confirmed',p_points,null,now(),now(),p_sender_address,p_slot,p_block_time)
  on conflict (transaction_signature) do nothing returning id into v_id;
  if v_id is null then return query select 'duplicate'::text, null::bigint, 0, null::integer; return; end if;
  if p_points > 0 then
    update public.users set points = coalesce(points,0) + p_points, updated_at = now() where telegram_id = p_telegram_id returning points into v_points;
    insert into public.reward_transactions(telegram_id,amount,reward_type,reason,created_at)
    values(p_telegram_id,p_points,'contribution',p_asset || ' Community Kitty contribution',now());
  else select points into v_points from public.users where telegram_id = p_telegram_id; end if;
  return query select 'recorded'::text, v_id, p_points, v_points;
end $$;
revoke all on function public.record_verified_contribution(bigint,bigint,text,text,numeric,text,bigint,timestamptz,integer) from public, anon, authenticated;
grant execute on function public.record_verified_contribution(bigint,bigint,text,text,numeric,text,bigint,timestamptz,integer) to service_role;
