-- REXSECURE ULTIMATE™ threat intelligence + network shield.
-- Additive. Designed to build on the existing REX SecureGuard foundation.

alter table public.zed_chat_settings
  add column if not exists secureguard_threat_intel_enabled boolean not null default true,
  add column if not exists secureguard_cas_enabled boolean not null default true,
  add column if not exists secureguard_network_shield_mode text not null default 'ban'
    check (secureguard_network_shield_mode in ('off','quarantine','ban')),
  add column if not exists secureguard_external_bots_mode text not null default 'remove'
    check (secureguard_external_bots_mode in ('allow','remove')),
  add column if not exists secureguard_pattern_guard_enabled boolean not null default true,
  add column if not exists secureguard_under_attack boolean not null default false;

create table if not exists public.secureguard_threat_profiles (
  telegram_id bigint primary key check (telegram_id > 0),
  status text not null default 'blocked'
    check (status in ('blocked','watch','cleared')),
  confidence integer not null default 100
    check (confidence between 0 and 100),
  source text not null default 'worldz_admin',
  reason text not null default '',
  evidence_url text,
  actor_telegram_id bigint,
  expires_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists secureguard_threat_profiles_status_idx
  on public.secureguard_threat_profiles(status, updated_at desc);

create table if not exists public.secureguard_reports (
  id bigint generated by default as identity primary key,
  chat_id bigint not null,
  reporter_telegram_id bigint not null,
  subject_telegram_id bigint not null,
  message_id bigint,
  reason text not null default '',
  evidence text not null default '',
  status text not null default 'pending'
    check (status in ('pending','confirmed','dismissed')),
  reviewed_by bigint,
  reviewed_at timestamptz,
  created_at timestamptz not null default now()
);
create index if not exists secureguard_reports_subject_idx
  on public.secureguard_reports(subject_telegram_id, status, created_at desc);

create table if not exists public.secureguard_spam_patterns (
  id bigint generated by default as identity primary key,
  chat_id bigint not null,
  fingerprint text not null,
  normalized_text text not null,
  reason text not null default '',
  source_telegram_id bigint,
  actor_telegram_id bigint,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(chat_id,fingerprint)
);
create index if not exists secureguard_spam_patterns_chat_idx
  on public.secureguard_spam_patterns(chat_id, active, updated_at desc);

alter table public.secureguard_threat_profiles enable row level security;
alter table public.secureguard_reports enable row level security;
alter table public.secureguard_spam_patterns enable row level security;

grant select, insert, update, delete on public.secureguard_threat_profiles, public.secureguard_reports, public.secureguard_spam_patterns to service_role;
grant usage, select on sequence public.secureguard_reports_id_seq, public.secureguard_spam_patterns_id_seq to service_role;

drop policy if exists "zed_runtime_bridge" on public.secureguard_threat_profiles;
create policy "zed_runtime_bridge" on public.secureguard_threat_profiles
for all to anon using (public.zed_runtime_authorized()) with check (public.zed_runtime_authorized());

drop policy if exists "zed_runtime_bridge" on public.secureguard_reports;
create policy "zed_runtime_bridge" on public.secureguard_reports
for all to anon using (public.zed_runtime_authorized()) with check (public.zed_runtime_authorized());

drop policy if exists "zed_runtime_bridge" on public.secureguard_spam_patterns;
create policy "zed_runtime_bridge" on public.secureguard_spam_patterns
for all to anon using (public.zed_runtime_authorized()) with check (public.zed_runtime_authorized());

grant select, insert, update, delete on public.secureguard_threat_profiles, public.secureguard_reports, public.secureguard_spam_patterns to anon;
grant usage, select on sequence public.secureguard_reports_id_seq, public.secureguard_spam_patterns_id_seq to anon;

revoke all on public.secureguard_threat_profiles, public.secureguard_reports, public.secureguard_spam_patterns from authenticated;
