alter table public.community_telegram_destinations
  add column if not exists broadcast_enabled boolean not null default false,
  add column if not exists broadcast_order integer not null default 100,
  add column if not exists broadcast_label text,
  add column if not exists broadcast_updated_by bigint,
  add column if not exists broadcast_updated_at timestamptz;

create index if not exists community_telegram_broadcast_targets_idx
  on public.community_telegram_destinations(broadcast_enabled, status, broadcast_order, project_slug)
  where broadcast_enabled = true;

create table if not exists public.worldzcast_posts (
  id uuid primary key default gen_random_uuid(),
  created_by bigint not null,
  status text not null default 'draft'
    check (status in ('draft','sending','completed','cancelled','failed')),
  body text not null default '' check (char_length(body) <= 8000),
  media_kind text not null default 'none' check (media_kind in ('none','photo')),
  telegram_file_id text,
  telegram_file_unique_id text,
  source_chat_id bigint,
  source_thread_id bigint not null default 0,
  target_count integer not null default 0 check (target_count >= 0),
  sent_count integer not null default 0 check (sent_count >= 0),
  failed_count integer not null default 0 check (failed_count >= 0),
  created_at timestamptz not null default now(),
  expires_at timestamptz not null default (now() + interval '30 minutes'),
  confirmed_at timestamptz,
  completed_at timestamptz,
  cancelled_at timestamptz,
  last_error text,
  check (media_kind = 'none' or telegram_file_id is not null)
);

create index if not exists worldzcast_posts_creator_idx
  on public.worldzcast_posts(created_by, created_at desc);
create index if not exists worldzcast_posts_status_idx
  on public.worldzcast_posts(status, created_at desc);

create table if not exists public.worldzcast_deliveries (
  id bigint generated by default as identity primary key,
  post_id uuid not null references public.worldzcast_posts(id) on delete cascade,
  destination_id bigint not null references public.community_telegram_destinations(id) on delete restrict,
  chat_id bigint not null,
  thread_id bigint not null default 0,
  status text not null default 'pending' check (status in ('pending','sent','failed')),
  telegram_message_id bigint,
  error_code text,
  created_at timestamptz not null default now(),
  sent_at timestamptz,
  unique (post_id, destination_id)
);

create index if not exists worldzcast_deliveries_post_idx
  on public.worldzcast_deliveries(post_id, status, created_at);

alter table public.worldzcast_posts enable row level security;
alter table public.worldzcast_deliveries enable row level security;

revoke all on table public.worldzcast_posts from anon, authenticated;
revoke all on table public.worldzcast_deliveries from anon, authenticated;
revoke all on sequence public.worldzcast_deliveries_id_seq from anon, authenticated;

comment on table public.worldzcast_posts is
  'Approval-controlled CryptoWorldz group and channel broadcast drafts. Telegram file IDs only; no private media storage.';
comment on table public.worldzcast_deliveries is
  'Per-destination WorldzCast delivery audit records.';
comment on column public.community_telegram_destinations.broadcast_enabled is
  'Owner-approved destination for WorldzCast. Disabled by default to prevent accidental posting.';
