create table if not exists public.reward_funding_settings (
  id text primary key default 'global',
  network text not null default 'solana' check (network = 'solana'),
  funding_asset text not null default 'USDC' check (funding_asset = 'USDC'),
  default_payout_asset text not null default 'USDC' check (default_payout_asset in ('USDC', 'SOL')),
  allowed_payout_assets text[] not null default array['USDC', 'SOL']::text[],
  weekly_target_aud_cents integer not null default 8000 check (weekly_target_aud_cents between 0 and 8000),
  weekly_target_points integer not null default 3000 check (weekly_target_points between 0 and 3000),
  timezone text not null default 'Australia/Sydney',
  sol_conversion_policy text not null default 'quote_at_payout' check (sol_conversion_policy = 'quote_at_payout'),
  auto_transfer_enabled boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint reward_funding_settings_singleton check (id = 'global'),
  constraint allowed_reward_assets check (
    allowed_payout_assets <@ array['USDC', 'SOL']::text[]
    and array_length(allowed_payout_assets, 1) >= 1
  )
);

insert into public.reward_funding_settings (
  id,
  network,
  funding_asset,
  default_payout_asset,
  allowed_payout_assets,
  weekly_target_aud_cents,
  weekly_target_points,
  timezone,
  sol_conversion_policy,
  auto_transfer_enabled,
  updated_at
) values (
  'global',
  'solana',
  'USDC',
  'USDC',
  array['USDC', 'SOL']::text[],
  8000,
  3000,
  'Australia/Sydney',
  'quote_at_payout',
  false,
  now()
)
on conflict (id) do update set
  network = excluded.network,
  funding_asset = excluded.funding_asset,
  default_payout_asset = excluded.default_payout_asset,
  allowed_payout_assets = excluded.allowed_payout_assets,
  weekly_target_aud_cents = excluded.weekly_target_aud_cents,
  weekly_target_points = excluded.weekly_target_points,
  timezone = excluded.timezone,
  sol_conversion_policy = excluded.sol_conversion_policy,
  auto_transfer_enabled = excluded.auto_transfer_enabled,
  updated_at = now();

create table if not exists public.reward_funding_schedule (
  day_of_week smallint primary key check (day_of_week between 1 and 7),
  day_label text not null,
  planned_aud_cents integer not null check (planned_aud_cents > 0),
  display_order smallint not null check (display_order > 0),
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

insert into public.reward_funding_schedule (
  day_of_week,
  day_label,
  planned_aud_cents,
  display_order,
  active,
  updated_at
) values
  (1, 'Monday', 4000, 1, true, now()),
  (2, 'Tuesday', 2000, 2, true, now()),
  (4, 'Thursday', 2000, 3, true, now())
on conflict (day_of_week) do update set
  day_label = excluded.day_label,
  planned_aud_cents = excluded.planned_aud_cents,
  display_order = excluded.display_order,
  active = excluded.active,
  updated_at = now();

create table if not exists public.member_reward_preferences (
  telegram_id bigint primary key,
  preferred_asset text not null default 'USDC' check (preferred_asset in ('USDC', 'SOL')),
  network text not null default 'solana' check (network = 'solana'),
  conversion_policy text not null default 'quote_at_payout' check (conversion_policy = 'quote_at_payout'),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.reward_funding_deposits (
  id bigint generated by default as identity primary key,
  reward_week_start date not null,
  recorded_day_of_week smallint not null check (recorded_day_of_week between 1 and 7),
  aud_value_cents integer not null check (aud_value_cents > 0),
  asset text not null default 'USDC' check (asset = 'USDC'),
  asset_amount numeric(20, 8) not null check (asset_amount > 0),
  transaction_signature text not null unique,
  status text not null default 'recorded' check (status in ('recorded', 'verified', 'void')),
  recorded_by bigint not null,
  created_at timestamptz not null default now(),
  verified_at timestamptz,
  updated_at timestamptz not null default now()
);

create index if not exists reward_funding_deposits_week_idx
  on public.reward_funding_deposits (reward_week_start, status, created_at);

alter table public.reward_funding_settings enable row level security;
alter table public.reward_funding_schedule enable row level security;
alter table public.member_reward_preferences enable row level security;
alter table public.reward_funding_deposits enable row level security;

create or replace function public.current_reward_week_start()
returns date
language sql
stable
set search_path = ''
as $$
  select (
    (now() at time zone 'Australia/Sydney')::date
    - (extract(isodow from now() at time zone 'Australia/Sydney')::integer - 1)
  )::date
$$;

create or replace function public.record_reward_funding_deposit(
  p_aud_value_cents integer,
  p_usdc_amount numeric,
  p_transaction_signature text,
  p_recorded_by bigint
)
returns table(
  outcome text,
  deposit_id bigint,
  weekly_recorded_aud_cents integer,
  weekly_remaining_aud_cents integer
)
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_settings public.reward_funding_settings%rowtype;
  v_week_start date := public.current_reward_week_start();
  v_day smallint := extract(isodow from now() at time zone 'Australia/Sydney')::smallint;
  v_used integer := 0;
  v_deposit_id bigint;
  v_signature text := trim(coalesce(p_transaction_signature, ''));
begin
  if p_aud_value_cents is null or p_aud_value_cents <= 0 then
    return query select 'invalid_aud_value'::text, null::bigint, 0, 0;
    return;
  end if;

  if p_usdc_amount is null or p_usdc_amount <= 0 then
    return query select 'invalid_usdc_amount'::text, null::bigint, 0, 0;
    return;
  end if;

  if v_signature !~ '^[1-9A-HJ-NP-Za-km-z]{40,100}$' then
    return query select 'invalid_transaction_signature'::text, null::bigint, 0, 0;
    return;
  end if;

  select * into v_settings
  from public.reward_funding_settings
  where id = 'global'
  for update;

  select coalesce(sum(aud_value_cents), 0)::integer into v_used
  from public.reward_funding_deposits
  where reward_week_start = v_week_start
    and status in ('recorded', 'verified');

  if v_used + p_aud_value_cents > v_settings.weekly_target_aud_cents then
    return query select
      'weekly_target_exceeded'::text,
      null::bigint,
      v_used,
      greatest(v_settings.weekly_target_aud_cents - v_used, 0);
    return;
  end if;

  begin
    insert into public.reward_funding_deposits (
      reward_week_start,
      recorded_day_of_week,
      aud_value_cents,
      asset,
      asset_amount,
      transaction_signature,
      status,
      recorded_by
    ) values (
      v_week_start,
      v_day,
      p_aud_value_cents,
      'USDC',
      p_usdc_amount,
      v_signature,
      'recorded',
      p_recorded_by
    )
    returning id into v_deposit_id;
  exception
    when unique_violation then
      return query select
        'duplicate_transaction'::text,
        null::bigint,
        v_used,
        greatest(v_settings.weekly_target_aud_cents - v_used, 0);
      return;
  end;

  v_used := v_used + p_aud_value_cents;
  return query select
    'recorded'::text,
    v_deposit_id,
    v_used,
    greatest(v_settings.weekly_target_aud_cents - v_used, 0);
end;
$$;

create or replace function public.get_reward_funding_status()
returns table(
  reward_week_start date,
  network text,
  funding_asset text,
  default_payout_asset text,
  allowed_payout_assets text[],
  weekly_target_aud_cents integer,
  weekly_target_points integer,
  recorded_aud_cents integer,
  remaining_aud_cents integer,
  timezone text,
  sol_conversion_policy text,
  auto_transfer_enabled boolean,
  funding_schedule jsonb
)
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_settings public.reward_funding_settings%rowtype;
  v_week_start date := public.current_reward_week_start();
  v_recorded integer := 0;
  v_schedule jsonb := '[]'::jsonb;
begin
  select * into v_settings
  from public.reward_funding_settings
  where id = 'global';

  select coalesce(sum(aud_value_cents), 0)::integer into v_recorded
  from public.reward_funding_deposits
  where reward_week_start = v_week_start
    and status in ('recorded', 'verified');

  select coalesce(
    jsonb_agg(
      jsonb_build_object(
        'day_of_week', day_of_week,
        'day_label', day_label,
        'planned_aud_cents', planned_aud_cents
      ) order by display_order
    ),
    '[]'::jsonb
  ) into v_schedule
  from public.reward_funding_schedule
  where active = true;

  return query select
    v_week_start,
    v_settings.network,
    v_settings.funding_asset,
    v_settings.default_payout_asset,
    v_settings.allowed_payout_assets,
    v_settings.weekly_target_aud_cents,
    v_settings.weekly_target_points,
    v_recorded,
    greatest(v_settings.weekly_target_aud_cents - v_recorded, 0),
    v_settings.timezone,
    v_settings.sol_conversion_policy,
    v_settings.auto_transfer_enabled,
    v_schedule;
end;
$$;

revoke all on function public.current_reward_week_start() from public;
revoke all on function public.record_reward_funding_deposit(integer, numeric, text, bigint) from public;
revoke all on function public.get_reward_funding_status() from public;
grant execute on function public.current_reward_week_start() to service_role;
grant execute on function public.record_reward_funding_deposit(integer, numeric, text, bigint) to service_role;
grant execute on function public.get_reward_funding_status() to service_role;
