-- Zed Bot 3.0 additive migration. No existing rows are deleted or overwritten.
alter table public.missions
  add column if not exists starts_at timestamptz,
  add column if not exists expires_at timestamptz,
  add column if not exists difficulty text not null default 'standard',
  add column if not exists max_submissions integer;

alter table public.missions drop constraint if exists missions_status_check;
alter table public.missions add constraint missions_status_check
  check (status in ('draft','active','open','paused','completed','closed','cancelled','expired')) not valid;
alter table public.missions validate constraint missions_status_check;
create unique index if not exists missions_target_url_unique_idx
  on public.missions (target_url) where target_url <> '';

create table if not exists public.bot_admins (
  id bigint generated by default as identity primary key,
  telegram_id bigint not null unique,
  role text not null default 'admin' check (role in ('owner','admin','moderator')),
  status text not null default 'active' check (status in ('active','disabled')),
  added_by bigint,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.reward_transactions (
  id bigint generated by default as identity primary key,
  telegram_id bigint not null,
  mission_id bigint references public.missions(id) on delete set null,
  submission_id bigint references public.mission_submissions(id) on delete set null,
  amount integer not null,
  reward_type text not null default 'mission' check (reward_type in ('mission','admin_adjustment','bonus','event','airdrop','governance')),
  reason text not null default '',
  awarded_by bigint,
  created_at timestamptz not null default now()
);
create unique index if not exists reward_transactions_submission_unique_idx
  on public.reward_transactions (submission_id) where submission_id is not null;
create index if not exists reward_transactions_period_idx on public.reward_transactions(created_at desc, telegram_id);

-- Backfill immutable history only when an equivalent legacy reward has not already been copied.
insert into public.reward_transactions (telegram_id, mission_id, amount, reward_type, reason, created_at)
select r.telegram_id, r.mission_id, r.points,
  case when r.reward_type = 'manual_adjustment' then 'admin_adjustment' else 'mission' end,
  coalesce(nullif(r.description,''), 'Legacy Zed reward'), r.created_at
from public.rewards r
where not exists (
  select 1 from public.reward_transactions t
  where t.telegram_id = r.telegram_id and t.amount = r.points and t.created_at = r.created_at
);

create table if not exists public.governance_proposals (
  id bigint generated by default as identity primary key,
  title text not null, description text not null default '', options jsonb not null default '[]'::jsonb,
  status text not null default 'draft', created_by bigint, starts_at timestamptz, ends_at timestamptz,
  created_at timestamptz not null default now()
);
create table if not exists public.governance_votes (
  id bigint generated by default as identity primary key,
  proposal_id bigint not null references public.governance_proposals(id) on delete cascade,
  telegram_id bigint not null, selected_option text not null, voting_power integer not null default 1,
  created_at timestamptz not null default now(), unique(proposal_id, telegram_id)
);
create table if not exists public.bot_assets (
  id bigint generated by default as identity primary key,
  asset_type text not null unique, telegram_file_id text, asset_url text, active boolean not null default true,
  created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
create table if not exists public.wallet_audit_log (
  id bigint generated by default as identity primary key,
  telegram_id bigint not null, old_wallet_masked text, new_wallet_masked text,
  changed_by bigint, created_at timestamptz not null default now()
);

alter table public.bot_admins enable row level security;
alter table public.reward_transactions enable row level security;
alter table public.governance_proposals enable row level security;
alter table public.governance_votes enable row level security;
alter table public.bot_assets enable row level security;
alter table public.wallet_audit_log enable row level security;
revoke all on public.bot_admins, public.reward_transactions, public.governance_proposals,
  public.governance_votes, public.bot_assets, public.wallet_audit_log from anon, authenticated;
grant all on public.bot_admins, public.reward_transactions, public.governance_proposals,
  public.governance_votes, public.bot_assets, public.wallet_audit_log to service_role;

-- Mirror future legacy reward writes into the canonical transaction ledger.
create or replace function public.mirror_legacy_reward_transaction() returns trigger
language plpgsql security definer set search_path = '' as $$
begin
  insert into public.reward_transactions(telegram_id, mission_id, amount, reward_type, reason, created_at)
  values (new.telegram_id, new.mission_id, new.points,
    case when new.reward_type = 'manual_adjustment' then 'admin_adjustment' else 'mission' end,
    coalesce(nullif(new.description,''), 'Zed reward'), new.created_at);
  return new;
end $$;
revoke all on function public.mirror_legacy_reward_transaction() from public, anon, authenticated;
grant execute on function public.mirror_legacy_reward_transaction() to service_role;
drop trigger if exists rewards_mirror_transaction on public.rewards;
create trigger rewards_mirror_transaction after insert on public.rewards
for each row execute function public.mirror_legacy_reward_transaction();
