-- ZED Auto Kitty Rewards.
-- ZED calculates proportional reward amounts from completed-week Legend Points.
-- Humans may approve the locked amount, but cannot edit the formula or payout amount.

create table if not exists public.reward_auto_settings (
  id text primary key default 'global' check (id = 'global'),
  enabled boolean not null default true,
  pool_percent numeric(5,2) not null default 10.00 check (pool_percent > 0 and pool_percent <= 50),
  minimum_kitty_usdc numeric(30,6) not null default 100.000000 check (minimum_kitty_usdc >= 0),
  minimum_batch_usdc numeric(30,6) not null default 1.000000 check (minimum_batch_usdc >= 0),
  timezone text not null default 'Australia/Sydney',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

insert into public.reward_auto_settings (
  id, enabled, pool_percent, minimum_kitty_usdc, minimum_batch_usdc, timezone
) values (
  'global', true, 10.00, 100.000000, 1.000000, 'Australia/Sydney'
)
on conflict (id) do nothing;

create table if not exists public.reward_auto_batches (
  id bigint generated by default as identity primary key,
  reward_week_start date not null unique,
  kitty_snapshot_usdc numeric(30,6) not null check (kitty_snapshot_usdc >= 0),
  available_kitty_usdc numeric(30,6) not null check (available_kitty_usdc >= 0),
  pool_percent numeric(5,2) not null check (pool_percent > 0 and pool_percent <= 50),
  pool_usdc numeric(30,6) not null check (pool_usdc >= 0),
  allocated_usdc numeric(30,6) not null default 0 check (allocated_usdc >= 0),
  points_total integer not null check (points_total > 0),
  queued_count integer not null default 0 check (queued_count >= 0),
  status text not null default 'waiting_approval'
    check (status in ('waiting_approval','partially_approved','approved','closed')),
  generated_by bigint,
  generated_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.reward_auto_queue (
  id bigint generated by default as identity primary key,
  batch_id bigint not null references public.reward_auto_batches(id) on delete restrict,
  telegram_id bigint not null,
  legend_points integer not null check (legend_points > 0),
  share_percent numeric(12,6) not null check (share_percent >= 0 and share_percent <= 100),
  usdc_amount numeric(30,6) not null check (usdc_amount > 0),
  preferred_asset text not null default 'USDC' check (preferred_asset in ('USDC','SOL')),
  wallet_address text,
  status text not null default 'pending_approval'
    check (status in ('pending_approval','wallet_required','approved','paid','cancelled')),
  approved_by bigint,
  approved_at timestamptz,
  payout_signature text,
  paid_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (batch_id, telegram_id)
);

create index if not exists reward_auto_queue_status_idx
  on public.reward_auto_queue(status, created_at);
create index if not exists reward_auto_queue_telegram_idx
  on public.reward_auto_queue(telegram_id, created_at desc);

alter table public.reward_auto_settings enable row level security;
alter table public.reward_auto_batches enable row level security;
alter table public.reward_auto_queue enable row level security;

revoke all on public.reward_auto_settings, public.reward_auto_batches, public.reward_auto_queue
  from anon, authenticated;
grant all on public.reward_auto_settings, public.reward_auto_batches, public.reward_auto_queue
  to service_role;

update public.project_wallets
set control_policy = 'ZED auto-calculates proportional rewards from completed-week Legend Points. Exact reward amounts are locked. Human approval is required before payout; ZED stores no private key.',
    notes = 'USDC is the Kitty accounting asset. Members may choose equal-value SOL. Reward amounts are calculated automatically; approvers cannot edit them.',
    updated_at = now()
where purpose = 'rewards';

insert into public.bot_admin_permissions
  (telegram_id, permission, enabled, set_by, updated_at)
values
  (7615025841, 'reward.approve', false, 8029135300, now()),
  (8604306923, 'reward.approve', false, 8029135300, now()),
  (5978625584, 'reward.approve', false, 8029135300, now())
on conflict (telegram_id, permission) do nothing;

create or replace function public.prepare_auto_reward_batch(
  p_kitty_usdc numeric,
  p_generated_by bigint default null
)
returns table(
  outcome text,
  batch_id bigint,
  reward_week_start date,
  kitty_usdc numeric,
  available_kitty_usdc numeric,
  pool_usdc numeric,
  allocated_usdc numeric,
  total_points integer,
  queued_count integer
)
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_settings public.reward_auto_settings%rowtype;
  v_week date := public.current_reward_week_start() - 7;
  v_existing public.reward_auto_batches%rowtype;
  v_batch_id bigint;
  v_reserved numeric(30,6) := 0;
  v_available numeric(30,6) := 0;
  v_pool numeric(30,6) := 0;
  v_allocated numeric(30,6) := 0;
  v_points integer := 0;
  v_count integer := 0;
  v_start timestamptz;
  v_end timestamptz;
begin
  select * into v_settings
  from public.reward_auto_settings
  where id = 'global'
  for update;

  if not found or not v_settings.enabled then
    return query select 'disabled'::text, null::bigint, v_week,
      greatest(coalesce(p_kitty_usdc, 0), 0), 0::numeric, 0::numeric, 0::numeric, 0, 0;
    return;
  end if;

  select * into v_existing
  from public.reward_auto_batches
  where reward_week_start = v_week;

  if found then
    return query select
      'existing'::text,
      v_existing.id,
      v_existing.reward_week_start,
      greatest(coalesce(p_kitty_usdc, 0), 0),
      v_existing.available_kitty_usdc,
      v_existing.pool_usdc,
      v_existing.allocated_usdc,
      v_existing.points_total,
      v_existing.queued_count;
    return;
  end if;

  if p_kitty_usdc is null or p_kitty_usdc < v_settings.minimum_kitty_usdc then
    return query select 'kitty_below_minimum'::text, null::bigint, v_week,
      greatest(coalesce(p_kitty_usdc, 0), 0), greatest(coalesce(p_kitty_usdc, 0), 0),
      0::numeric, 0::numeric, 0, 0;
    return;
  end if;

  select coalesce(sum(q.usdc_amount), 0)::numeric(30,6)
  into v_reserved
  from public.reward_auto_queue q
  where q.status in ('pending_approval','wallet_required','approved');

  v_available := greatest(trunc(p_kitty_usdc - v_reserved, 6), 0);

  if v_available < v_settings.minimum_kitty_usdc then
    return query select 'kitty_below_minimum'::text, null::bigint, v_week,
      p_kitty_usdc, v_available, 0::numeric, 0::numeric, 0, 0;
    return;
  end if;

  v_pool := trunc(v_available * v_settings.pool_percent / 100, 6);
  if v_pool < v_settings.minimum_batch_usdc then
    return query select 'pool_below_minimum'::text, null::bigint, v_week,
      p_kitty_usdc, v_available, v_pool, 0::numeric, 0, 0;
    return;
  end if;

  v_start := (v_week::timestamp at time zone v_settings.timezone);
  v_end := ((v_week + 7)::timestamp at time zone v_settings.timezone);

  select coalesce(sum(x.points), 0)::integer
  into v_points
  from (
    select r.telegram_id, sum(greatest(r.points, 0))::integer as points
    from public.rewards r
    where r.created_at >= v_start
      and r.created_at < v_end
      and r.points > 0
    group by r.telegram_id
  ) x;

  if v_points <= 0 then
    return query select 'no_points'::text, null::bigint, v_week,
      p_kitty_usdc, v_available, v_pool, 0::numeric, 0, 0;
    return;
  end if;

  insert into public.reward_auto_batches(
    reward_week_start, kitty_snapshot_usdc, available_kitty_usdc,
    pool_percent, pool_usdc, points_total, generated_by
  ) values (
    v_week, p_kitty_usdc, v_available,
    v_settings.pool_percent, v_pool, v_points, p_generated_by
  )
  returning id into v_batch_id;

  with earned as (
    select r.telegram_id, sum(greatest(r.points, 0))::integer as legend_points
    from public.rewards r
    where r.created_at >= v_start
      and r.created_at < v_end
      and r.points > 0
    group by r.telegram_id
  ),
  allocations as (
    select
      e.telegram_id,
      e.legend_points,
      round((e.legend_points::numeric / v_points::numeric) * 100, 6) as share_percent,
      trunc(v_pool * e.legend_points::numeric / v_points::numeric, 6) as usdc_amount,
      coalesce(p.preferred_asset, 'USDC') as preferred_asset,
      u.wallet as wallet_address
    from earned e
    join public.users u on u.telegram_id = e.telegram_id
    left join public.member_reward_preferences p on p.telegram_id = e.telegram_id
  )
  insert into public.reward_auto_queue(
    batch_id, telegram_id, legend_points, share_percent, usdc_amount,
    preferred_asset, wallet_address, status
  )
  select
    v_batch_id,
    a.telegram_id,
    a.legend_points,
    a.share_percent,
    a.usdc_amount,
    a.preferred_asset,
    a.wallet_address,
    case when a.wallet_address is null or trim(a.wallet_address) = ''
      then 'wallet_required' else 'pending_approval' end
  from allocations a
  where a.usdc_amount > 0;

  select coalesce(sum(usdc_amount), 0)::numeric(30,6), count(*)::integer
  into v_allocated, v_count
  from public.reward_auto_queue
  where batch_id = v_batch_id;

  if v_count = 0 then
    delete from public.reward_auto_batches where id = v_batch_id;
    return query select 'pool_below_minimum'::text, null::bigint, v_week,
      p_kitty_usdc, v_available, v_pool, 0::numeric, v_points, 0;
    return;
  end if;

  update public.reward_auto_batches
  set allocated_usdc = v_allocated,
      queued_count = v_count,
      updated_at = now()
  where id = v_batch_id;

  return query select 'created'::text, v_batch_id, v_week,
    p_kitty_usdc, v_available, v_pool, v_allocated, v_points, v_count;
end;
$$;

create or replace function public.get_auto_reward_queue(p_limit integer default 25)
returns table(
  queue_id bigint,
  batch_id bigint,
  reward_week_start date,
  telegram_id bigint,
  username text,
  first_name text,
  legend_points integer,
  share_percent numeric,
  usdc_amount numeric,
  preferred_asset text,
  wallet_address text,
  status text
)
language plpgsql
security definer
set search_path = ''
as $$
begin
  update public.reward_auto_queue q
  set wallet_address = u.wallet,
      status = 'pending_approval',
      updated_at = now()
  from public.users u
  where q.telegram_id = u.telegram_id
    and q.status = 'wallet_required'
    and u.wallet is not null
    and trim(u.wallet) <> '';

  return query
  select
    q.id,
    q.batch_id,
    b.reward_week_start,
    q.telegram_id,
    u.username,
    u.first_name,
    q.legend_points,
    q.share_percent,
    q.usdc_amount,
    q.preferred_asset,
    q.wallet_address,
    q.status
  from public.reward_auto_queue q
  join public.reward_auto_batches b on b.id = q.batch_id
  left join public.users u on u.telegram_id = q.telegram_id
  where q.status in ('pending_approval','wallet_required')
  order by b.reward_week_start asc, q.usdc_amount desc, q.id asc
  limit greatest(1, least(coalesce(p_limit, 25), 100));
end;
$$;

create or replace function public.approve_auto_reward(
  p_queue_id bigint,
  p_approved_by bigint
)
returns table(
  outcome text,
  queue_id bigint,
  telegram_id bigint,
  legend_points integer,
  usdc_amount numeric,
  preferred_asset text,
  wallet_address text
)
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_queue public.reward_auto_queue%rowtype;
  v_wallet text;
  v_asset text;
  v_pending integer;
begin
  select * into v_queue
  from public.reward_auto_queue
  where id = p_queue_id
  for update;

  if not found then
    return query select 'not_found'::text, p_queue_id, null::bigint, 0, 0::numeric, null::text, null::text;
    return;
  end if;

  if v_queue.status in ('approved','paid') then
    return query select 'already_approved'::text, v_queue.id, v_queue.telegram_id,
      v_queue.legend_points, v_queue.usdc_amount, v_queue.preferred_asset, v_queue.wallet_address;
    return;
  end if;

  if v_queue.status = 'cancelled' then
    return query select 'cancelled'::text, v_queue.id, v_queue.telegram_id,
      v_queue.legend_points, v_queue.usdc_amount, v_queue.preferred_asset, v_queue.wallet_address;
    return;
  end if;

  select u.wallet, coalesce(p.preferred_asset, 'USDC')
  into v_wallet, v_asset
  from public.users u
  left join public.member_reward_preferences p on p.telegram_id = u.telegram_id
  where u.telegram_id = v_queue.telegram_id;

  if v_wallet is null or trim(v_wallet) = '' then
    update public.reward_auto_queue
    set status = 'wallet_required', updated_at = now()
    where id = v_queue.id;
    return query select 'wallet_required'::text, v_queue.id, v_queue.telegram_id,
      v_queue.legend_points, v_queue.usdc_amount, coalesce(v_asset, v_queue.preferred_asset), null::text;
    return;
  end if;

  update public.reward_auto_queue
  set wallet_address = v_wallet,
      preferred_asset = coalesce(v_asset, 'USDC'),
      status = 'approved',
      approved_by = p_approved_by,
      approved_at = now(),
      updated_at = now()
  where id = v_queue.id
  returning * into v_queue;

  select count(*)::integer into v_pending
  from public.reward_auto_queue
  where batch_id = v_queue.batch_id
    and status in ('pending_approval','wallet_required');

  update public.reward_auto_batches
  set status = case when v_pending = 0 then 'approved' else 'partially_approved' end,
      updated_at = now()
  where id = v_queue.batch_id;

  insert into public.mission_history(mission_id, action, actor_telegram_id, details)
  values (
    null,
    'auto_reward_approved',
    p_approved_by,
    jsonb_build_object(
      'queue_id', v_queue.id,
      'batch_id', v_queue.batch_id,
      'telegram_id', v_queue.telegram_id,
      'legend_points', v_queue.legend_points,
      'usdc_amount', v_queue.usdc_amount,
      'preferred_asset', v_queue.preferred_asset
    )
  );

  return query select 'approved'::text, v_queue.id, v_queue.telegram_id,
    v_queue.legend_points, v_queue.usdc_amount, v_queue.preferred_asset, v_queue.wallet_address;
end;
$$;

create or replace function public.mark_auto_reward_paid(
  p_queue_id bigint,
  p_transaction_signature text,
  p_recorded_by bigint
)
returns table(outcome text, queue_id bigint, telegram_id bigint, usdc_amount numeric)
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_queue public.reward_auto_queue%rowtype;
  v_signature text := trim(coalesce(p_transaction_signature, ''));
begin
  if v_signature !~ '^[1-9A-HJ-NP-Za-km-z]{40,100}$' then
    return query select 'invalid_signature'::text, p_queue_id, null::bigint, 0::numeric;
    return;
  end if;

  select * into v_queue
  from public.reward_auto_queue
  where id = p_queue_id
  for update;

  if not found then
    return query select 'not_found'::text, p_queue_id, null::bigint, 0::numeric;
    return;
  end if;
  if v_queue.status = 'paid' then
    return query select 'already_paid'::text, v_queue.id, v_queue.telegram_id, v_queue.usdc_amount;
    return;
  end if;
  if v_queue.status <> 'approved' then
    return query select 'approval_required'::text, v_queue.id, v_queue.telegram_id, v_queue.usdc_amount;
    return;
  end if;
  if exists (
    select 1 from public.reward_auto_queue
    where payout_signature = v_signature and id <> v_queue.id
  ) then
    return query select 'duplicate_signature'::text, v_queue.id, v_queue.telegram_id, v_queue.usdc_amount;
    return;
  end if;

  update public.reward_auto_queue
  set status = 'paid',
      payout_signature = v_signature,
      paid_at = now(),
      updated_at = now()
  where id = v_queue.id;

  insert into public.mission_history(mission_id, action, actor_telegram_id, details)
  values (
    null,
    'auto_reward_paid',
    p_recorded_by,
    jsonb_build_object('queue_id', v_queue.id, 'telegram_id', v_queue.telegram_id, 'usdc_amount', v_queue.usdc_amount)
  );

  return query select 'paid'::text, v_queue.id, v_queue.telegram_id, v_queue.usdc_amount;
end;
$$;

revoke all on function public.prepare_auto_reward_batch(numeric,bigint) from public;
revoke all on function public.get_auto_reward_queue(integer) from public;
revoke all on function public.approve_auto_reward(bigint,bigint) from public;
revoke all on function public.mark_auto_reward_paid(bigint,text,bigint) from public;

grant execute on function public.prepare_auto_reward_batch(numeric,bigint) to service_role;
grant execute on function public.get_auto_reward_queue(integer) to service_role;
grant execute on function public.approve_auto_reward(bigint,bigint) to service_role;
grant execute on function public.mark_auto_reward_paid(bigint,text,bigint) to service_role;
