-- Shared Worldz bot decision ledger.
-- Records automated checks/decisions without bypassing cryptographic or provider security.

create table if not exists public.worldz_bot_decision_ledger (
  id bigint generated by default as identity primary key,
  subject_type text not null,
  subject_key text not null,
  decision text not null check (decision in ('approved','rejected','deferred')),
  rex jsonb not null default '{}'::jsonb,
  zed jsonb not null default '{}'::jsonb,
  auto jsonb not null default '{}'::jsonb,
  grace jsonb not null default '{}'::jsonb,
  dipshit jsonb not null default '{}'::jsonb,
  reason text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(subject_type,subject_key)
);

alter table public.worldz_bot_decision_ledger enable row level security;
revoke all on public.worldz_bot_decision_ledger from public,authenticated;
grant select,insert,update on public.worldz_bot_decision_ledger to service_role;

drop policy if exists worldz_bot_decision_runtime on public.worldz_bot_decision_ledger;
create policy worldz_bot_decision_runtime on public.worldz_bot_decision_ledger
for all to anon
using (public.zed_runtime_authorized())
with check (public.zed_runtime_authorized());

grant select,insert,update on public.worldz_bot_decision_ledger to anon;
grant usage,select on sequence public.worldz_bot_decision_ledger_id_seq to anon,service_role;

create or replace function public.record_worldz_bot_decision(
  p_subject_type text,
  p_subject_key text,
  p_decision text,
  p_rex jsonb default '{}'::jsonb,
  p_zed jsonb default '{}'::jsonb,
  p_auto jsonb default '{}'::jsonb,
  p_grace jsonb default '{}'::jsonb,
  p_dipshit jsonb default '{}'::jsonb,
  p_reason text default ''
)
returns bigint
language plpgsql
security definer
set search_path=''
as $$
declare v_id bigint;
begin
  if coalesce(auth.role(),'') <> 'service_role' and not public.zed_runtime_authorized() then
    raise exception 'not_authorized';
  end if;
  if p_decision not in ('approved','rejected','deferred') then
    raise exception 'invalid_decision';
  end if;

  insert into public.worldz_bot_decision_ledger(
    subject_type,subject_key,decision,rex,zed,auto,grace,dipshit,reason,updated_at
  ) values(
    trim(p_subject_type),trim(p_subject_key),p_decision,
    coalesce(p_rex,'{}'::jsonb),coalesce(p_zed,'{}'::jsonb),coalesce(p_auto,'{}'::jsonb),
    coalesce(p_grace,'{}'::jsonb),coalesce(p_dipshit,'{}'::jsonb),coalesce(p_reason,''),now()
  )
  on conflict(subject_type,subject_key) do update
  set decision=excluded.decision,
      rex=excluded.rex,
      zed=excluded.zed,
      auto=excluded.auto,
      grace=excluded.grace,
      dipshit=excluded.dipshit,
      reason=excluded.reason,
      updated_at=now()
  returning id into v_id;

  return v_id;
end;
$$;

revoke all on function public.record_worldz_bot_decision(text,text,text,jsonb,jsonb,jsonb,jsonb,jsonb,text)
from public,authenticated;
grant execute on function public.record_worldz_bot_decision(text,text,text,jsonb,jsonb,jsonb,jsonb,jsonb,text)
to anon,service_role;
