-- REX SecureGuard foundation for Worldz FullBuild Community Suite.
-- Additive only. SecureGuard is disabled by default per group.

alter table public.zed_chat_settings
  add column if not exists secureguard_enabled boolean not null default false,
  add column if not exists secureguard_number_match_enabled boolean not null default true,
  add column if not exists secureguard_timeout_seconds integer not null default 120
    check (secureguard_timeout_seconds between 30 and 900),
  add column if not exists secureguard_max_attempts integer not null default 3
    check (secureguard_max_attempts between 1 and 10),
  add column if not exists secureguard_antiflood_enabled boolean not null default true,
  add column if not exists secureguard_max_messages_10s integer not null default 8
    check (secureguard_max_messages_10s between 3 and 30),
  add column if not exists secureguard_links_mode text not null default 'blocklist'
    check (secureguard_links_mode in ('allow','blocklist','admins_only')),
  add column if not exists secureguard_impersonation_mode text not null default 'warn'
    check (secureguard_impersonation_mode in ('off','warn','quarantine'));

create table if not exists public.secureguard_challenges (
  id bigint generated by default as identity primary key,
  chat_id bigint not null,
  telegram_id bigint not null,
  challenge_code integer not null check (challenge_code between 10 and 99),
  attempts integer not null default 0 check (attempts >= 0),
  max_attempts integer not null default 3 check (max_attempts between 1 and 10),
  status text not null default 'pending'
    check (status in ('pending','passed','failed','expired')),
  expires_at timestamptz not null,
  message_id bigint,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists secureguard_one_pending_per_member_chat
  on public.secureguard_challenges(chat_id, telegram_id)
  where status='pending';

create index if not exists secureguard_pending_expiry
  on public.secureguard_challenges(status, expires_at asc);

create table if not exists public.secureguard_events (
  id bigint generated by default as identity primary key,
  chat_id bigint not null,
  telegram_id bigint,
  event_type text not null,
  detail text not null default '',
  actor_telegram_id bigint,
  created_at timestamptz not null default now()
);

create index if not exists secureguard_events_chat
  on public.secureguard_events(chat_id, created_at desc);

create table if not exists public.secureguard_domains (
  chat_id bigint not null,
  domain text not null,
  action text not null default 'block' check (action in ('block','allow')),
  reason text not null default '',
  created_by bigint,
  created_at timestamptz not null default now(),
  primary key(chat_id,domain)
);

create table if not exists public.secureguard_trusted_identities (
  chat_id bigint not null,
  telegram_id bigint not null,
  identity_type text not null default 'admin'
    check (identity_type in ('admin','team','bot','channel','partner')),
  label text not null,
  username text,
  created_by bigint,
  created_at timestamptz not null default now(),
  primary key(chat_id,telegram_id)
);
create index if not exists secureguard_trusted_identity_label_idx
  on public.secureguard_trusted_identities(chat_id,lower(label));

alter table public.secureguard_challenges enable row level security;
alter table public.secureguard_events enable row level security;
alter table public.secureguard_domains enable row level security;
alter table public.secureguard_trusted_identities enable row level security;

grant select, insert, update, delete on public.secureguard_challenges, public.secureguard_events, public.secureguard_domains, public.secureguard_trusted_identities to service_role;
grant usage, select on sequence public.secureguard_challenges_id_seq, public.secureguard_events_id_seq to service_role;

drop policy if exists "zed_runtime_bridge" on public.secureguard_challenges;
create policy "zed_runtime_bridge" on public.secureguard_challenges
for all to anon using (public.zed_runtime_authorized()) with check (public.zed_runtime_authorized());

drop policy if exists "zed_runtime_bridge" on public.secureguard_events;
create policy "zed_runtime_bridge" on public.secureguard_events
for all to anon using (public.zed_runtime_authorized()) with check (public.zed_runtime_authorized());

drop policy if exists "zed_runtime_bridge" on public.secureguard_domains;
create policy "zed_runtime_bridge" on public.secureguard_domains
for all to anon using (public.zed_runtime_authorized()) with check (public.zed_runtime_authorized());

drop policy if exists "zed_runtime_bridge" on public.secureguard_trusted_identities;
create policy "zed_runtime_bridge" on public.secureguard_trusted_identities
for all to anon using (public.zed_runtime_authorized()) with check (public.zed_runtime_authorized());

grant select, insert, update, delete on public.secureguard_challenges, public.secureguard_events, public.secureguard_domains, public.secureguard_trusted_identities to anon;
grant usage, select on sequence public.secureguard_challenges_id_seq, public.secureguard_events_id_seq to anon;

revoke all on public.secureguard_challenges, public.secureguard_events, public.secureguard_domains, public.secureguard_trusted_identities from authenticated;
