-- Grace Social Engine Phase One
-- Zed-led approvals, Auto budget controls, queue workers and business-ready workspaces.

create table if not exists public.grace_workspaces (
  id uuid primary key default gen_random_uuid(),
  slug text not null unique check (slug ~ '^[a-z0-9][a-z0-9-]{1,62}$'),
  name text not null check (char_length(name) between 2 and 120),
  owner_telegram_id bigint not null,
  status text not null default 'active' check (status in ('active', 'suspended', 'closed')),
  business_mode boolean not null default true,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.grace_workspace_members (
  id bigint generated by default as identity primary key,
  workspace_id uuid not null references public.grace_workspaces(id) on delete cascade,
  telegram_id bigint not null,
  role text not null default 'editor' check (role in ('owner', 'admin', 'editor', 'analyst', 'viewer')),
  status text not null default 'active' check (status in ('active', 'disabled')),
  permissions jsonb not null default '[]'::jsonb,
  added_by bigint,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (workspace_id, telegram_id)
);

create table if not exists public.grace_settings (
  workspace_id uuid primary key references public.grace_workspaces(id) on delete cascade,
  paused boolean not null default false,
  emergency_stop boolean not null default false,
  posting_enabled boolean not null default false,
  approval_required boolean not null default true,
  timezone text not null default 'Australia/Sydney',
  monthly_api_budget_usd numeric(12,2) not null default 25.00 check (monthly_api_budget_usd >= 0),
  daily_post_limit integer not null default 100 check (daily_post_limit between 1 and 10000),
  max_retry_attempts integer not null default 3 check (max_retry_attempts between 1 and 10),
  worker_interval_seconds integer not null default 60 check (worker_interval_seconds between 15 and 3600),
  cost_model jsonb not null default '{
    "x": {"text": 0.015, "link": 0.200},
    "facebook": {"text": 0, "link": 0},
    "instagram": {"text": 0, "link": 0},
    "youtube": {"text": 0, "link": 0},
    "tiktok": {"text": 0, "link": 0}
  }'::jsonb,
  updated_by bigint,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.grace_social_accounts (
  id bigint generated by default as identity primary key,
  workspace_id uuid not null references public.grace_workspaces(id) on delete cascade,
  platform text not null check (platform in ('x', 'facebook', 'instagram', 'youtube', 'tiktok')),
  account_key text not null check (account_key ~ '^[a-z0-9][a-z0-9_-]{0,49}$'),
  display_name text not null check (char_length(display_name) between 1 and 120),
  handle text,
  external_account_id text,
  credential_secret_ref text not null check (credential_secret_ref ~ '^[A-Z][A-Z0-9_]{4,120}$'),
  status text not null default 'pending_credentials' check (status in ('pending_credentials', 'active', 'paused', 'disabled', 'error')),
  daily_post_limit integer not null default 10 check (daily_post_limit between 1 and 1000),
  monthly_budget_usd numeric(12,2) not null default 0 check (monthly_budget_usd >= 0),
  metadata jsonb not null default '{}'::jsonb,
  created_by bigint,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (workspace_id, platform, account_key)
);

create table if not exists public.grace_posts (
  id uuid primary key default gen_random_uuid(),
  workspace_id uuid not null references public.grace_workspaces(id) on delete cascade,
  title text not null check (char_length(title) between 1 and 160),
  campaign text not null default '',
  body text not null check (char_length(body) between 1 and 4000),
  platform_overrides jsonb not null default '{}'::jsonb,
  media jsonb not null default '{}'::jsonb,
  link_url text,
  status text not null default 'draft' check (status in ('draft', 'pending_approval', 'approved', 'rejected', 'published', 'cancelled')),
  scheduled_for timestamptz,
  created_by bigint not null,
  approved_by bigint,
  approved_at timestamptz,
  rejected_by bigint,
  rejected_at timestamptz,
  rejection_reason text,
  published_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.grace_post_targets (
  id bigint generated by default as identity primary key,
  workspace_id uuid not null references public.grace_workspaces(id) on delete cascade,
  post_id uuid not null references public.grace_posts(id) on delete cascade,
  account_id bigint not null references public.grace_social_accounts(id) on delete cascade,
  caption text not null check (char_length(caption) between 1 and 4000),
  media jsonb not null default '{}'::jsonb,
  scheduled_for timestamptz not null,
  status text not null default 'queued' check (status in ('queued', 'publishing', 'published', 'failed', 'blocked', 'cancelled')),
  estimated_cost_usd numeric(12,6) not null default 0 check (estimated_cost_usd >= 0),
  actual_cost_usd numeric(12,6) not null default 0 check (actual_cost_usd >= 0),
  external_post_id text,
  error_message text,
  attempt_count integer not null default 0 check (attempt_count >= 0),
  next_attempt_at timestamptz,
  last_attempt_at timestamptz,
  published_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (post_id, account_id)
);

create table if not exists public.grace_growth_snapshots (
  id bigint generated by default as identity primary key,
  workspace_id uuid not null references public.grace_workspaces(id) on delete cascade,
  account_id bigint not null references public.grace_social_accounts(id) on delete cascade,
  followers bigint not null default 0 check (followers >= 0),
  following bigint not null default 0 check (following >= 0),
  views bigint not null default 0 check (views >= 0),
  engagements bigint not null default 0 check (engagements >= 0),
  metadata jsonb not null default '{}'::jsonb,
  recorded_by bigint,
  recorded_at timestamptz not null default now()
);

create table if not exists public.grace_audit_log (
  id bigint generated by default as identity primary key,
  workspace_id uuid not null references public.grace_workspaces(id) on delete cascade,
  action text not null check (char_length(action) between 3 and 120),
  actor_telegram_id bigint,
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists grace_workspace_members_telegram_idx
  on public.grace_workspace_members (telegram_id, status);
create index if not exists grace_accounts_workspace_status_idx
  on public.grace_social_accounts (workspace_id, status, platform);
create index if not exists grace_posts_calendar_idx
  on public.grace_posts (workspace_id, scheduled_for, status);
create index if not exists grace_targets_due_idx
  on public.grace_post_targets (workspace_id, status, next_attempt_at, scheduled_for);
create index if not exists grace_targets_account_created_idx
  on public.grace_post_targets (account_id, created_at desc);
create index if not exists grace_growth_account_time_idx
  on public.grace_growth_snapshots (workspace_id, account_id, recorded_at desc);
create index if not exists grace_audit_workspace_time_idx
  on public.grace_audit_log (workspace_id, created_at desc);

insert into public.grace_workspaces (slug, name, owner_telegram_id, business_mode)
values ('cryptoworldz', 'CryptoWorldz Command Centre', 8029135300, true)
on conflict (slug) do update
set name = excluded.name,
    owner_telegram_id = excluded.owner_telegram_id,
    business_mode = true,
    updated_at = now();

insert into public.grace_workspace_members (workspace_id, telegram_id, role, status, added_by)
select id, owner_telegram_id, 'owner', 'active', owner_telegram_id
from public.grace_workspaces
where slug = 'cryptoworldz'
on conflict (workspace_id, telegram_id) do update
set role = 'owner', status = 'active', updated_at = now();

insert into public.grace_settings (workspace_id)
select id from public.grace_workspaces where slug = 'cryptoworldz'
on conflict (workspace_id) do nothing;

create or replace function public.grace_touch_updated_at()
returns trigger
language plpgsql
set search_path = public, pg_temp
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create or replace trigger grace_workspaces_touch_updated_at
before update on public.grace_workspaces
for each row execute function public.grace_touch_updated_at();

create or replace trigger grace_workspace_members_touch_updated_at
before update on public.grace_workspace_members
for each row execute function public.grace_touch_updated_at();

create or replace trigger grace_settings_touch_updated_at
before update on public.grace_settings
for each row execute function public.grace_touch_updated_at();

create or replace trigger grace_social_accounts_touch_updated_at
before update on public.grace_social_accounts
for each row execute function public.grace_touch_updated_at();

create or replace trigger grace_posts_touch_updated_at
before update on public.grace_posts
for each row execute function public.grace_touch_updated_at();

create or replace trigger grace_post_targets_touch_updated_at
before update on public.grace_post_targets
for each row execute function public.grace_touch_updated_at();

create or replace function public.grace_claim_due_targets(
  p_workspace_id uuid,
  p_limit integer default 10
)
returns table (
  target_id bigint,
  post_id uuid,
  account_id bigint,
  platform text,
  account_key text,
  display_name text,
  handle text,
  credential_secret_ref text,
  monthly_budget_usd numeric,
  caption text,
  link_url text,
  media jsonb,
  attempt_count integer
)
language plpgsql
security definer
set search_path = public, pg_temp
as $$
begin
  return query
  with candidates as (
    select target.id
    from public.grace_post_targets target
    join public.grace_posts post on post.id = target.post_id
    join public.grace_social_accounts account on account.id = target.account_id
    join public.grace_settings settings on settings.workspace_id = target.workspace_id
    where target.workspace_id = p_workspace_id
      and target.status = 'queued'
      and target.scheduled_for <= now()
      and coalesce(target.next_attempt_at, target.scheduled_for) <= now()
      and post.status = 'approved'
      and account.status = 'active'
      and settings.posting_enabled = true
      and settings.paused = false
      and settings.emergency_stop = false
    order by target.scheduled_for asc, target.id asc
    for update of target skip locked
    limit greatest(1, least(coalesce(p_limit, 10), 25))
  ), claimed as (
    update public.grace_post_targets target
    set status = 'publishing',
        attempt_count = target.attempt_count + 1,
        last_attempt_at = now(),
        updated_at = now()
    from candidates
    where target.id = candidates.id
    returning target.*
  )
  select
    claimed.id,
    claimed.post_id,
    claimed.account_id,
    account.platform,
    account.account_key,
    account.display_name,
    account.handle,
    account.credential_secret_ref,
    account.monthly_budget_usd,
    claimed.caption,
    post.link_url,
    claimed.media,
    claimed.attempt_count
  from claimed
  join public.grace_posts post on post.id = claimed.post_id
  join public.grace_social_accounts account on account.id = claimed.account_id;
end;
$$;

alter table public.grace_workspaces enable row level security;
alter table public.grace_workspace_members enable row level security;
alter table public.grace_settings enable row level security;
alter table public.grace_social_accounts enable row level security;
alter table public.grace_posts enable row level security;
alter table public.grace_post_targets enable row level security;
alter table public.grace_growth_snapshots enable row level security;
alter table public.grace_audit_log enable row level security;

revoke all on table public.grace_workspaces from anon, authenticated;
revoke all on table public.grace_workspace_members from anon, authenticated;
revoke all on table public.grace_settings from anon, authenticated;
revoke all on table public.grace_social_accounts from anon, authenticated;
revoke all on table public.grace_posts from anon, authenticated;
revoke all on table public.grace_post_targets from anon, authenticated;
revoke all on table public.grace_growth_snapshots from anon, authenticated;
revoke all on table public.grace_audit_log from anon, authenticated;

revoke all on function public.grace_claim_due_targets(uuid, integer) from public, anon, authenticated;
grant execute on function public.grace_claim_due_targets(uuid, integer) to service_role;
