create table if not exists public.community_projects (
  slug text primary key,
  display_name text not null,
  status text not null default 'active' check (status in ('active', 'connecting', 'archived')),
  website_url text,
  primary_telegram_url text,
  match_terms text[] not null default '{}',
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.community_telegram_destinations (
  id bigint generated by default as identity primary key,
  project_slug text references public.community_projects(slug) on update cascade on delete set null,
  chat_id bigint not null,
  thread_id bigint not null default 0,
  chat_type text not null,
  title text not null,
  username text,
  public_url text,
  is_forum boolean not null default false,
  linked_chat_id bigint,
  linked_title text,
  linked_username text,
  linked_public_url text,
  topic_label text,
  status text not null default 'active' check (status in ('active', 'connecting', 'archived')),
  last_seen_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (chat_id, thread_id)
);

create index if not exists community_telegram_destinations_project_idx
  on public.community_telegram_destinations(project_slug, status);

create index if not exists community_telegram_destinations_linked_chat_idx
  on public.community_telegram_destinations(linked_chat_id)
  where linked_chat_id is not null;

create table if not exists public.community_social_accounts (
  id bigint generated by default as identity primary key,
  project_slug text references public.community_projects(slug) on update cascade on delete set null,
  platform text not null,
  display_name text not null,
  handle text not null,
  url text not null,
  status text not null default 'active' check (status in ('active', 'connecting', 'archived')),
  display_order integer not null default 100,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (platform, handle)
);

create index if not exists community_social_accounts_project_idx
  on public.community_social_accounts(project_slug, platform, status, display_order);

create or replace function public.set_community_directory_updated_at()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists community_projects_updated_at on public.community_projects;
create trigger community_projects_updated_at
before update on public.community_projects
for each row execute function public.set_community_directory_updated_at();

drop trigger if exists community_telegram_destinations_updated_at on public.community_telegram_destinations;
create trigger community_telegram_destinations_updated_at
before update on public.community_telegram_destinations
for each row execute function public.set_community_directory_updated_at();

drop trigger if exists community_social_accounts_updated_at on public.community_social_accounts;
create trigger community_social_accounts_updated_at
before update on public.community_social_accounts
for each row execute function public.set_community_directory_updated_at();

alter table public.community_projects enable row level security;
alter table public.community_telegram_destinations enable row level security;
alter table public.community_social_accounts enable row level security;

drop policy if exists "Public can view active community projects" on public.community_projects;
create policy "Public can view active community projects"
on public.community_projects for select
to anon, authenticated
using (status = 'active');

drop policy if exists "Public can view active Telegram destinations" on public.community_telegram_destinations;
create policy "Public can view active Telegram destinations"
on public.community_telegram_destinations for select
to anon, authenticated
using (status = 'active');

drop policy if exists "Public can view active social accounts" on public.community_social_accounts;
create policy "Public can view active social accounts"
on public.community_social_accounts for select
to anon, authenticated
using (status = 'active');

grant select on public.community_projects to anon, authenticated;
grant select on public.community_telegram_destinations to anon, authenticated;
grant select on public.community_social_accounts to anon, authenticated;

insert into public.community_projects
  (slug, display_name, status, website_url, primary_telegram_url, match_terms)
values
  ('cryptoworldz', 'CryptoWorldz', 'active', 'https://CryptoWorldz.xyz', 'https://t.me/CryptoWorldzHQ', array['cryptoworldz', 'crypto worldz', 'command centre', 'hq']),
  ('oneworldz', 'OneWorldz', 'active', 'https://OneWorldz.com', null, array['oneworldz', 'one worldz']),
  ('solworldz', 'SolWorldz', 'active', 'https://SolWorldz.xyz', null, array['solworldz', 'solworld', 'sol world', 'solana world']),
  ('purple-diamond-crew', 'Purple Diamond Crew', 'active', 'https://PurpleDiamondCrew.com', null, array['purple diamond crew', 'diamond crew', 'pdc']),
  ('jayjayteamdev', 'JayJayTeamDev', 'active', null, null, array['jayjayteamdev', 'jay jay team dev']),
  ('black-bud-bull', 'Black Bud Bull', 'active', null, null, array['black bud bull', 'blackbud', 'black bud']),
  ('global-impact-alliance', 'Global Impact Alliance', 'active', null, null, array['global impact alliance', 'gia']),
  ('uganda-unite', 'Uganda Unite', 'active', null, null, array['uganda unite', 'ugandaunitex']),
  ('solmars', 'SolMars', 'active', null, null, array['solmars', 'sol mars', 'muskman']),
  ('recover-your-debt', 'RecoverYourDebt', 'active', 'https://RobinWorldz.xyz', null, array['recoveryourdebt', 'recover your debt', '$debt']),
  ('next-big-coin', 'Next Big Coin', 'active', null, null, array['next big coin', 'bigcoinnext', '$nbc'])
on conflict (slug) do update set
  display_name = excluded.display_name,
  status = excluded.status,
  website_url = coalesce(excluded.website_url, public.community_projects.website_url),
  primary_telegram_url = coalesce(excluded.primary_telegram_url, public.community_projects.primary_telegram_url),
  match_terms = excluded.match_terms;

insert into public.community_social_accounts
  (project_slug, platform, display_name, handle, url, status, display_order)
values
  ('cryptoworldz', 'x', 'CryptoWorldz', 'CryptoWorldzX', 'https://x.com/CryptoWorldzX', 'active', 10),
  ('solworldz', 'x', 'SolWorldz', 'Solworldx', 'https://x.com/Solworldx', 'active', 20),
  ('jayjayteamdev', 'x', 'JayJayTeamDev', 'jayjayteamdev', 'https://x.com/jayjayteamdev', 'active', 30),
  ('black-bud-bull', 'x', 'Black Bud Bull', 'blackbudtoken', 'https://x.com/blackbudtoken', 'active', 40),
  ('global-impact-alliance', 'x', 'Global Impact Alliance', 'gia_token', 'https://x.com/gia_token', 'active', 50),
  ('uganda-unite', 'x', 'Uganda Unite', 'ugandaunitex', 'https://x.com/ugandaunitex', 'active', 60),
  ('solmars', 'x', 'MUSKMAN / SolMars', 'muskmanmars', 'https://x.com/muskmanmars', 'active', 70),
  ('recover-your-debt', 'x', 'RecoverYourDebt', 'recoveryourdebt', 'https://x.com/recoveryourdebt', 'active', 80),
  ('next-big-coin', 'x', 'Next Big Coin', 'bigcoinnext', 'https://x.com/bigcoinnext', 'active', 90)
on conflict (platform, handle) do update set
  project_slug = excluded.project_slug,
  display_name = excluded.display_name,
  url = excluded.url,
  status = excluded.status,
  display_order = excluded.display_order;
