create table if not exists public.reward_budget_settings (
  id text primary key default 'global',
  currency text not null default 'AUD',
  weekly_budget_cents integer not null default 0 check (weekly_budget_cents >= 0),
  points_per_currency_unit integer not null default 100 check (points_per_currency_unit between 1 and 100000),
  utilization_percent integer not null default 70 check (utilization_percent between 1 and 100),
  pilot_weekly_points_cap integer not null default 1000 check (pilot_weekly_points_cap > 0),
  maximum_weekly_points_cap integer not null default 5000 check (maximum_weekly_points_cap >= pilot_weekly_points_cap),
  mission_pool_percent integer not null default 50 check (mission_pool_percent between 0 and 100),
  referral_pool_percent integer not null default 30 check (referral_pool_percent between 0 and 100),
  reserve_pool_percent integer not null default 20 check (reserve_pool_percent between 0 and 100),
  referral_inviter_points integer not null default 20 check (referral_inviter_points between 1 and 1000),
  referral_newcomer_points integer not null default 5 check (referral_newcomer_points between 0 and 1000),
  referral_retention_days integer not null default 7 check (referral_retention_days between 1 and 90),
  inviter_weekly_qualified_cap integer not null default 5 check (inviter_weekly_qualified_cap between 1 and 100),
  enabled boolean not null default true,
  cash_redemption_enabled boolean not null default false,
  updated_by bigint,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint reward_budget_singleton check (id = 'global'),
  constraint reward_budget_pool_total check (
    mission_pool_percent + referral_pool_percent + reserve_pool_percent = 100
  )
);

insert into public.reward_budget_settings (id)
values ('global')
on conflict (id) do nothing;

create table if not exists public.community_referral_targets (
  chat_id bigint primary key,
  project_slug text references public.community_projects(slug) on update cascade on delete set null,
  title text not null,
  enabled boolean not null default true,
  created_by bigint,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.member_referral_links (
  id bigint generated by default as identity primary key,
  telegram_id bigint not null,
  chat_id bigint not null references public.community_referral_targets(chat_id) on update cascade on delete cascade,
  invite_link text not null unique,
  invite_name text not null default '',
  status text not null default 'active' check (status in ('active', 'revoked')),
  joins_recorded integer not null default 0 check (joins_recorded >= 0),
  qualified_joins integer not null default 0 check (qualified_joins >= 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (telegram_id, chat_id)
);

create table if not exists public.member_referrals (
  id bigint generated by default as identity primary key,
  referral_link_id bigint not null references public.member_referral_links(id) on update cascade on delete cascade,
  inviter_telegram_id bigint not null,
  referred_telegram_id bigint not null,
  chat_id bigint not null,
  referred_username text,
  referred_first_name text,
  status text not null default 'pending' check (
    status in ('pending', 'qualified', 'rejected')
  ),
  joined_at timestamptz not null default now(),
  qualifies_at timestamptz not null,
  expires_at timestamptz not null,
  qualified_at timestamptz,
  inviter_points_awarded integer not null default 0 check (inviter_points_awarded >= 0),
  newcomer_points_awarded integer not null default 0 check (newcomer_points_awarded >= 0),
  rejection_reason text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists member_referrals_one_active_referrer
  on public.member_referrals (referred_telegram_id)
  where status in ('pending', 'qualified');

create unique index if not exists member_referrals_chat_member_unique
  on public.member_referrals (chat_id, referred_telegram_id);

create index if not exists member_referrals_pending_qualification
  on public.member_referrals (qualifies_at, status);

create index if not exists member_referrals_inviter_week
  on public.member_referrals (inviter_telegram_id, qualified_at)
  where status = 'qualified';

alter table public.reward_budget_settings enable row level security;
alter table public.community_referral_targets enable row level security;
alter table public.member_referral_links enable row level security;
alter table public.member_referrals enable row level security;

create or replace function public.reward_category_for_type(p_reward_type text)
returns text
language sql
immutable
as $$
  select case
    when coalesce(p_reward_type, '') like 'referral_%' then 'referral'
    when coalesce(p_reward_type, '') in ('mission_points', 'mission') then 'mission'
    else 'reserve'
  end
$$;

create or replace function public.enforce_weekly_reward_budget()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_settings public.reward_budget_settings%rowtype;
  v_week_start timestamptz := date_trunc('week', now());
  v_effective_cap integer;
  v_category text;
  v_category_percent integer;
  v_category_cap integer;
  v_total_used integer;
  v_category_used integer;
begin
  if coalesce(new.points, 0) <= 0 then
    return new;
  end if;

  select * into v_settings
  from public.reward_budget_settings
  where id = 'global'
  for update;

  if not found or not v_settings.enabled then
    return new;
  end if;

  if v_settings.weekly_budget_cents > 0 then
    v_effective_cap := least(
      v_settings.maximum_weekly_points_cap,
      floor(
        (v_settings.weekly_budget_cents::numeric / 100)
        * v_settings.points_per_currency_unit
        * v_settings.utilization_percent
        / 100
      )::integer
    );
  else
    v_effective_cap := v_settings.pilot_weekly_points_cap;
  end if;

  v_effective_cap := greatest(v_effective_cap, 0);
  if v_effective_cap <= 0 then
    raise exception 'weekly_reward_budget_exhausted';
  end if;

  v_category := public.reward_category_for_type(new.reward_type);
  v_category_percent := case v_category
    when 'mission' then v_settings.mission_pool_percent
    when 'referral' then v_settings.referral_pool_percent
    else v_settings.reserve_pool_percent
  end;
  v_category_cap := floor(v_effective_cap * v_category_percent::numeric / 100)::integer;

  select coalesce(sum(greatest(points, 0)), 0)::integer
    into v_total_used
  from public.rewards
  where created_at >= v_week_start;

  select coalesce(sum(greatest(points, 0)), 0)::integer
    into v_category_used
  from public.rewards
  where created_at >= v_week_start
    and public.reward_category_for_type(reward_type) = v_category;

  if v_total_used + new.points > v_effective_cap then
    raise exception 'weekly_reward_budget_exhausted';
  end if;

  if v_category_used + new.points > v_category_cap then
    raise exception 'reward_category_budget_exhausted';
  end if;

  return new;
end;
$$;

drop trigger if exists enforce_weekly_reward_budget_trigger on public.rewards;
create trigger enforce_weekly_reward_budget_trigger
before insert on public.rewards
for each row execute function public.enforce_weekly_reward_budget();

create or replace function public.record_referral_join(
  p_invite_link text,
  p_referred_telegram_id bigint,
  p_referred_username text,
  p_referred_first_name text,
  p_joined_at timestamptz default now()
)
returns table(outcome text, referral_id bigint, inviter_telegram_id bigint, qualifies_at timestamptz)
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_link public.member_referral_links%rowtype;
  v_settings public.reward_budget_settings%rowtype;
  v_referral public.member_referrals%rowtype;
begin
  select l.* into v_link
  from public.member_referral_links l
  join public.community_referral_targets t on t.chat_id = l.chat_id
  where l.invite_link = p_invite_link
    and l.status = 'active'
    and t.enabled = true
  for update of l;

  if not found then
    return query select 'unknown_link'::text, null::bigint, null::bigint, null::timestamptz;
    return;
  end if;

  if v_link.telegram_id = p_referred_telegram_id then
    return query select 'self_referral'::text, null::bigint, v_link.telegram_id, null::timestamptz;
    return;
  end if;

  if exists (
    select 1 from public.users u where u.telegram_id = p_referred_telegram_id
  ) then
    return query select 'existing_member'::text, null::bigint, v_link.telegram_id, null::timestamptz;
    return;
  end if;

  select * into v_settings
  from public.reward_budget_settings
  where id = 'global';

  begin
    insert into public.member_referrals (
      referral_link_id,
      inviter_telegram_id,
      referred_telegram_id,
      chat_id,
      referred_username,
      referred_first_name,
      status,
      joined_at,
      qualifies_at,
      expires_at
    ) values (
      v_link.id,
      v_link.telegram_id,
      p_referred_telegram_id,
      v_link.chat_id,
      nullif(trim(coalesce(p_referred_username, '')), ''),
      nullif(trim(coalesce(p_referred_first_name, '')), ''),
      'pending',
      coalesce(p_joined_at, now()),
      coalesce(p_joined_at, now()) + make_interval(days => coalesce(v_settings.referral_retention_days, 7)),
      coalesce(p_joined_at, now()) + interval '30 days'
    )
    returning * into v_referral;
  exception
    when unique_violation then
      return query select 'duplicate'::text, null::bigint, v_link.telegram_id, null::timestamptz;
      return;
  end;

  update public.member_referral_links
  set joins_recorded = joins_recorded + 1,
      updated_at = now()
  where id = v_link.id;

  return query select 'recorded'::text, v_referral.id, v_link.telegram_id, v_referral.qualifies_at;
end;
$$;

create or replace function public.qualify_referral(
  p_referral_id bigint
)
returns table(
  outcome text,
  inviter_telegram_id bigint,
  referred_telegram_id bigint,
  inviter_points integer,
  newcomer_points integer
)
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_referral public.member_referrals%rowtype;
  v_settings public.reward_budget_settings%rowtype;
  v_week_start timestamptz := date_trunc('week', now());
  v_weekly_count integer;
begin
  select * into v_referral
  from public.member_referrals
  where id = p_referral_id
  for update;

  if not found then
    return query select 'not_found'::text, null::bigint, null::bigint, 0, 0;
    return;
  end if;

  if v_referral.status = 'qualified' then
    return query select
      'already_qualified'::text,
      v_referral.inviter_telegram_id,
      v_referral.referred_telegram_id,
      v_referral.inviter_points_awarded,
      v_referral.newcomer_points_awarded;
    return;
  end if;

  if v_referral.status = 'rejected' then
    return query select 'rejected'::text, v_referral.inviter_telegram_id, v_referral.referred_telegram_id, 0, 0;
    return;
  end if;

  if v_referral.expires_at <= now() then
    update public.member_referrals
    set status = 'rejected',
        rejection_reason = 'qualification_expired',
        updated_at = now()
    where id = v_referral.id;
    return query select 'expired'::text, v_referral.inviter_telegram_id, v_referral.referred_telegram_id, 0, 0;
    return;
  end if;

  if v_referral.qualifies_at > now() then
    return query select 'too_early'::text, v_referral.inviter_telegram_id, v_referral.referred_telegram_id, 0, 0;
    return;
  end if;

  if not exists (
    select 1 from public.users u where u.telegram_id = v_referral.referred_telegram_id
  ) then
    return query select 'awaiting_registration'::text, v_referral.inviter_telegram_id, v_referral.referred_telegram_id, 0, 0;
    return;
  end if;

  if not exists (
    select 1 from public.users u where u.telegram_id = v_referral.inviter_telegram_id
  ) then
    update public.member_referrals
    set status = 'rejected',
        rejection_reason = 'inviter_not_registered',
        updated_at = now()
    where id = v_referral.id;
    return query select 'inviter_not_registered'::text, v_referral.inviter_telegram_id, v_referral.referred_telegram_id, 0, 0;
    return;
  end if;

  select * into v_settings
  from public.reward_budget_settings
  where id = 'global'
  for update;

  select count(*)::integer into v_weekly_count
  from public.member_referrals
  where inviter_telegram_id = v_referral.inviter_telegram_id
    and status = 'qualified'
    and qualified_at >= v_week_start;

  if v_weekly_count >= v_settings.inviter_weekly_qualified_cap then
    return query select 'inviter_cap_deferred'::text, v_referral.inviter_telegram_id, v_referral.referred_telegram_id, 0, 0;
    return;
  end if;

  begin
    update public.users
    set points = coalesce(points, 0) + v_settings.referral_inviter_points,
        updated_at = now()
    where telegram_id = v_referral.inviter_telegram_id;

    insert into public.rewards (
      telegram_id, mission_id, points, reward_type, description
    ) values (
      v_referral.inviter_telegram_id,
      null,
      v_settings.referral_inviter_points,
      'referral_inviter',
      'Qualified CryptoWorldz member referral'
    );

    insert into public.reward_transactions (
      telegram_id, mission_id, submission_id, amount, reward_type, reason, awarded_by
    ) values (
      v_referral.inviter_telegram_id,
      null,
      null,
      v_settings.referral_inviter_points,
      'referral_inviter',
      'Qualified CryptoWorldz member referral',
      null
    );

    if v_settings.referral_newcomer_points > 0 then
      update public.users
      set points = coalesce(points, 0) + v_settings.referral_newcomer_points,
          updated_at = now()
      where telegram_id = v_referral.referred_telegram_id;

      insert into public.rewards (
        telegram_id, mission_id, points, reward_type, description
      ) values (
        v_referral.referred_telegram_id,
        null,
        v_settings.referral_newcomer_points,
        'referral_newcomer',
        'CryptoWorldz referral welcome reward'
      );

      insert into public.reward_transactions (
        telegram_id, mission_id, submission_id, amount, reward_type, reason, awarded_by
      ) values (
        v_referral.referred_telegram_id,
        null,
        null,
        v_settings.referral_newcomer_points,
        'referral_newcomer',
        'CryptoWorldz referral welcome reward',
        null
      );
    end if;
  exception
    when others then
      if sqlerrm in ('weekly_reward_budget_exhausted', 'reward_category_budget_exhausted') then
        return query select 'budget_deferred'::text, v_referral.inviter_telegram_id, v_referral.referred_telegram_id, 0, 0;
        return;
      end if;
      raise;
  end;

  update public.member_referrals
  set status = 'qualified',
      qualified_at = now(),
      inviter_points_awarded = v_settings.referral_inviter_points,
      newcomer_points_awarded = v_settings.referral_newcomer_points,
      updated_at = now()
  where id = v_referral.id;

  update public.member_referral_links
  set qualified_joins = qualified_joins + 1,
      updated_at = now()
  where id = v_referral.referral_link_id;

  return query select
    'qualified'::text,
    v_referral.inviter_telegram_id,
    v_referral.referred_telegram_id,
    v_settings.referral_inviter_points,
    v_settings.referral_newcomer_points;
end;
$$;

create or replace function public.get_reward_budget_status()
returns table(
  currency text,
  weekly_budget_cents integer,
  effective_weekly_points_cap integer,
  total_used integer,
  mission_cap integer,
  mission_used integer,
  referral_cap integer,
  referral_used integer,
  reserve_cap integer,
  reserve_used integer,
  referral_inviter_points integer,
  referral_newcomer_points integer,
  referral_retention_days integer,
  inviter_weekly_qualified_cap integer,
  cash_redemption_enabled boolean
)
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_settings public.reward_budget_settings%rowtype;
  v_cap integer;
  v_week_start timestamptz := date_trunc('week', now());
begin
  select * into v_settings
  from public.reward_budget_settings
  where id = 'global';

  if v_settings.weekly_budget_cents > 0 then
    v_cap := least(
      v_settings.maximum_weekly_points_cap,
      floor(
        (v_settings.weekly_budget_cents::numeric / 100)
        * v_settings.points_per_currency_unit
        * v_settings.utilization_percent
        / 100
      )::integer
    );
  else
    v_cap := v_settings.pilot_weekly_points_cap;
  end if;

  return query
  select
    v_settings.currency,
    v_settings.weekly_budget_cents,
    v_cap,
    coalesce(sum(greatest(r.points, 0)), 0)::integer,
    floor(v_cap * v_settings.mission_pool_percent::numeric / 100)::integer,
    coalesce(sum(greatest(r.points, 0)) filter (
      where public.reward_category_for_type(r.reward_type) = 'mission'
    ), 0)::integer,
    floor(v_cap * v_settings.referral_pool_percent::numeric / 100)::integer,
    coalesce(sum(greatest(r.points, 0)) filter (
      where public.reward_category_for_type(r.reward_type) = 'referral'
    ), 0)::integer,
    floor(v_cap * v_settings.reserve_pool_percent::numeric / 100)::integer,
    coalesce(sum(greatest(r.points, 0)) filter (
      where public.reward_category_for_type(r.reward_type) = 'reserve'
    ), 0)::integer,
    v_settings.referral_inviter_points,
    v_settings.referral_newcomer_points,
    v_settings.referral_retention_days,
    v_settings.inviter_weekly_qualified_cap,
    v_settings.cash_redemption_enabled
  from public.rewards r
  where r.created_at >= v_week_start;
end;
$$;

revoke all on function public.record_referral_join(text, bigint, text, text, timestamptz) from public;
revoke all on function public.qualify_referral(bigint) from public;
revoke all on function public.get_reward_budget_status() from public;
grant execute on function public.record_referral_join(text, bigint, text, text, timestamptz) to service_role;
grant execute on function public.qualify_referral(bigint) to service_role;
grant execute on function public.get_reward_budget_status() to service_role;
