-- Worldz FullBuild™ Community Suite platform foundation.
-- Additive multi-group commercial/runtime tables. Existing ZED data remains authoritative.

alter table public.zed_group_licences
  drop constraint if exists zed_group_licences_plan_check;
alter table public.zed_group_licences
  add constraint zed_group_licences_plan_check
  check (plan in ('pending','trial','rent','rent_to_own','own'));

alter table public.zed_group_licences
  add column if not exists rent_to_own_payments integer not null default 0 check (rent_to_own_payments between 0 and 12),
  add column if not exists product_package text not null default 'full'
    check (product_package in ('operations','ai','full'));

alter table public.zed_group_licence_receipts
  add column if not exists requested_plan text
    check (requested_plan is null or requested_plan in ('trial','rent','rent_to_own','own')),
  add column if not exists requested_package text
    check (requested_package is null or requested_package in ('operations','ai','full'));

create table if not exists public.community_suite_groups (
  chat_id bigint primary key,
  workspace_slug text not null,
  display_name text not null default '',
  product_package text not null default 'full'
    check (product_package in ('operations','ai','full')),
  language_code text not null default 'en',
  emergency_lockdown boolean not null default false,
  owner_telegram_id bigint,
  network_key text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(workspace_slug)
);

create table if not exists public.community_suite_modules (
  chat_id bigint not null references public.community_suite_groups(chat_id) on delete cascade,
  module_key text not null,
  enabled boolean not null default true,
  config jsonb not null default '{}'::jsonb,
  updated_by_telegram_id bigint,
  updated_at timestamptz not null default now(),
  primary key(chat_id,module_key)
);

create table if not exists public.community_suite_branding (
  chat_id bigint primary key references public.community_suite_groups(chat_id) on delete cascade,
  mode text not null default 'worldz_theme' check (mode in ('worldz_theme','customer','premium_custom')),
  theme_key text not null default 'purple_galaxy',
  bot_display_name text,
  ai_display_name text,
  logo_url text,
  banner_url text,
  primary_hex text,
  accent_hex text,
  token_symbol text,
  token_address text,
  website_url text,
  x_url text,
  telegram_url text,
  updated_by_telegram_id bigint,
  updated_at timestamptz not null default now()
);

create table if not exists public.community_suite_tickets (
  id bigint generated by default as identity primary key,
  chat_id bigint not null,
  telegram_id bigint not null,
  subject text not null,
  body text not null,
  status text not null default 'open' check (status in ('open','pending','resolved','closed')),
  priority text not null default 'normal' check (priority in ('low','normal','high','urgent')),
  assigned_to bigint,
  resolution text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  closed_at timestamptz
);
create index if not exists community_suite_tickets_chat_status_idx
  on public.community_suite_tickets(chat_id,status,created_at desc);

create table if not exists public.community_suite_ticket_messages (
  id bigint generated by default as identity primary key,
  ticket_id bigint not null references public.community_suite_tickets(id) on delete cascade,
  author_telegram_id bigint,
  author_role text not null default 'member' check (author_role in ('member','admin','system','ai')),
  body text not null,
  created_at timestamptz not null default now()
);
create index if not exists community_suite_ticket_messages_ticket_idx
  on public.community_suite_ticket_messages(ticket_id,created_at asc);

create table if not exists public.community_suite_calendar_events (
  id bigint generated by default as identity primary key,
  chat_id bigint not null,
  title text not null,
  starts_at timestamptz not null,
  ends_at timestamptz,
  description text not null default '',
  link_url text,
  reminder_minutes integer not null default 60 check (reminder_minutes between 0 and 10080),
  reminder_sent_at timestamptz,
  created_by bigint,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists community_suite_calendar_due_idx
  on public.community_suite_calendar_events(chat_id,starts_at);

create table if not exists public.community_suite_giveaways (
  id bigint generated by default as identity primary key,
  chat_id bigint not null,
  title text not null,
  prize_text text not null,
  status text not null default 'open' check (status in ('draft','open','closed','cancelled')),
  entry_closes_at timestamptz not null,
  max_winners integer not null default 1 check (max_winners between 1 and 25),
  created_by bigint,
  winner_telegram_ids bigint[] not null default '{}',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create table if not exists public.community_suite_giveaway_entries (
  giveaway_id bigint not null references public.community_suite_giveaways(id) on delete cascade,
  telegram_id bigint not null,
  entered_at timestamptz not null default now(),
  primary key(giveaway_id,telegram_id)
);

create table if not exists public.community_suite_wallet_watchlist (
  id bigint generated by default as identity primary key,
  chat_id bigint not null,
  chain text not null default 'solana',
  address text not null,
  label text not null default '',
  enabled boolean not null default true,
  created_by bigint,
  created_at timestamptz not null default now(),
  unique(chat_id,chain,address)
);

create table if not exists public.community_suite_market_alert_rules (
  id bigint generated by default as identity primary key,
  chat_id bigint not null,
  chain text not null default 'solana',
  token_address text not null,
  token_symbol text,
  min_buy_usd numeric(20,4) not null default 100 check (min_buy_usd >= 0),
  whale_buy_usd numeric(20,4) not null default 1000 check (whale_buy_usd >= min_buy_usd),
  enabled boolean not null default true,
  created_by bigint,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(chat_id,chain,token_address)
);

create table if not exists public.community_suite_market_events (
  id bigint generated by default as identity primary key,
  provider text not null,
  event_key text not null unique,
  chat_id bigint,
  chain text not null,
  token_address text not null,
  token_symbol text,
  side text not null check (side in ('buy','sell','transfer','liquidity_add','liquidity_remove')),
  usd_value numeric(24,6),
  native_value numeric(24,9),
  wallet_address text,
  tx_signature text,
  raw jsonb not null default '{}'::jsonb,
  observed_at timestamptz not null,
  created_at timestamptz not null default now()
);
create index if not exists community_suite_market_events_token_idx
  on public.community_suite_market_events(chain,token_address,observed_at desc);

create table if not exists public.community_suite_api_keys (
  id bigint generated by default as identity primary key,
  chat_id bigint not null,
  label text not null default 'API Key',
  token_hash text not null unique,
  token_prefix text not null,
  scopes text[] not null default array['read','events']::text[],
  enabled boolean not null default true,
  created_by bigint,
  created_at timestamptz not null default now(),
  last_used_at timestamptz
);

create table if not exists public.community_suite_webhooks (
  id bigint generated by default as identity primary key,
  chat_id bigint not null,
  endpoint_url text not null,
  event_types text[] not null default array['*']::text[],
  secret_ciphertext text,
  enabled boolean not null default true,
  created_by bigint,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(chat_id,endpoint_url)
);

create table if not exists public.community_suite_analytics_events (
  id bigint generated by default as identity primary key,
  chat_id bigint not null,
  telegram_id bigint,
  event_type text not null,
  source text not null default 'telegram',
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);
create index if not exists community_suite_analytics_chat_event_idx
  on public.community_suite_analytics_events(chat_id,event_type,created_at desc);

create table if not exists public.community_suite_promotions (
  id bigint generated by default as identity primary key,
  chat_id bigint not null,
  token_address text,
  provider text not null,
  product text not null,
  status text not null default 'planned' check (status in ('planned','submitted','active','complete','cancelled')),
  paid boolean not null default false,
  disclosure_text text not null default 'Sponsored / paid promotion',
  provider_reference text,
  created_by bigint,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

do $$
declare
  t text;
begin
  foreach t in array array[
    'community_suite_groups','community_suite_modules','community_suite_branding',
    'community_suite_tickets','community_suite_ticket_messages','community_suite_calendar_events','community_suite_giveaways',
    'community_suite_giveaway_entries','community_suite_wallet_watchlist',
    'community_suite_market_alert_rules','community_suite_market_events',
    'community_suite_api_keys','community_suite_webhooks','community_suite_analytics_events','community_suite_promotions'
  ]
  loop
    execute format('alter table public.%I enable row level security', t);
    execute format('grant select, insert, update, delete on public.%I to service_role', t);
    execute format('drop policy if exists "zed_runtime_bridge" on public.%I', t);
    execute format('create policy "zed_runtime_bridge" on public.%I for all to anon using (public.zed_runtime_authorized()) with check (public.zed_runtime_authorized())', t);
    execute format('grant select, insert, update, delete on public.%I to anon', t);
    execute format('revoke all on public.%I from authenticated', t);
  end loop;
end $$;

grant usage, select on sequence
  public.community_suite_tickets_id_seq,
  public.community_suite_ticket_messages_id_seq,
  public.community_suite_calendar_events_id_seq,
  public.community_suite_giveaways_id_seq,
  public.community_suite_wallet_watchlist_id_seq,
  public.community_suite_market_alert_rules_id_seq,
  public.community_suite_market_events_id_seq,
  public.community_suite_api_keys_id_seq,
  public.community_suite_webhooks_id_seq,
  public.community_suite_analytics_events_id_seq,
  public.community_suite_promotions_id_seq
to anon, service_role;
