-- Ronald Raider, toggle settings, social shill rewards, RECAP AUTO allowlist,
-- and partner-allocation candidates.
-- Additive: no existing allocations or transfers are changed.

create table if not exists public.zed_chat_settings (
  chat_id bigint primary key,
  welcome_enabled boolean not null default true,
  welcome_variations_enabled boolean not null default false,
  welcome_media_enabled boolean not null default false,
  welcome_buttons_enabled boolean not null default true,
  ronald_raider_enabled boolean not null default true,
  shill_rewards_enabled boolean not null default true,
  referral_links_enabled boolean not null default true,
  points_enabled boolean not null default true,
  leaderboard_enabled boolean not null default true,
  notifications_enabled boolean not null default true,
  worldping_enabled boolean not null default true,
  auto_panel_enabled boolean not null default true,
  grace_panel_enabled boolean not null default true,
  dipshit_enabled boolean not null default true,
  updated_by bigint,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.raid_campaigns (
  id bigint generated by default as identity primary key,
  chat_id bigint not null,
  mission_id bigint not null references public.missions(id) on update cascade on delete cascade,
  source_url text not null,
  platform text not null default 'X',
  status text not null default 'queued' check (status in ('active','queued','stopped','completed')),
  likes_goal integer not null default 10 check (likes_goal >= 0),
  reposts_goal integer not null default 5 check (reposts_goal >= 0),
  replies_goal integer not null default 3 check (replies_goal >= 0),
  views_goal integer not null default 0 check (views_goal >= 0),
  likes_current integer not null default 0 check (likes_current >= 0),
  reposts_current integer not null default 0 check (reposts_current >= 0),
  replies_current integer not null default 0 check (replies_current >= 0),
  views_current integer not null default 0 check (views_current >= 0),
  created_by bigint,
  started_at timestamptz,
  stopped_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (mission_id)
);

create unique index if not exists raid_campaigns_one_active_per_chat
  on public.raid_campaigns(chat_id)
  where status = 'active';

create index if not exists raid_campaigns_queue_idx
  on public.raid_campaigns(chat_id, status, created_at asc);

create table if not exists public.shill_reward_tokens (
  symbol text primary key,
  display_name text not null,
  token_mint text,
  enabled boolean not null default true,
  points_per_verified_share integer not null default 5 check (points_per_verified_share between 1 and 100),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

insert into public.shill_reward_tokens(symbol, display_name, token_mint, enabled, points_per_verified_share)
values
  ('WLDZ','WORLDZ',null,true,5),
  ('RVIV','REVIVE',null,true,5),
  ('PNEX','PHENIX',null,true,5),
  ('MRCL','MIRACLE',null,true,5),
  ('HSSC','Hope St Support Coin',null,true,5),
  ('RECAP','RecapThisBot','DF4zASfiDBr3uuAz4s2Sxtsjo7tDFZiQ2nLeKJGfBAGS',true,5)
on conflict (symbol) do update
set display_name = excluded.display_name,
    token_mint = coalesce(excluded.token_mint, public.shill_reward_tokens.token_mint),
    enabled = true,
    updated_at = now();

create table if not exists public.social_shill_submissions (
  id bigint generated by default as identity primary key,
  telegram_id bigint not null,
  token_symbol text not null references public.shill_reward_tokens(symbol) on update cascade on delete restrict,
  platform text not null,
  proof_url text not null unique,
  status text not null default 'pending' check (status in ('pending','approved','rejected')),
  points_awarded integer not null default 0 check (points_awarded >= 0),
  reviewed_by bigint,
  reviewed_at timestamptz,
  rejection_reason text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists social_shill_submissions_member_idx
  on public.social_shill_submissions(telegram_id, created_at desc);
create index if not exists social_shill_submissions_pending_idx
  on public.social_shill_submissions(status, created_at asc);

-- Shill rewards use the existing mission/reward pool so the weekly safety ceiling still applies.
create or replace function public.reward_category_for_type(p_reward_type text)
returns text
language sql
immutable
as $$
  select case
    when coalesce(p_reward_type, '') like 'referral_%' then 'referral'
    when coalesce(p_reward_type, '') in ('mission_points', 'mission')
      or coalesce(p_reward_type, '') like 'shill_%' then 'mission'
    else 'reserve'
  end
$$;

create or replace function public.approve_social_shill_submission(
  p_submission_id bigint,
  p_reviewer_telegram_id bigint
)
returns table(outcome text, telegram_id bigint, token_symbol text, points_awarded integer)
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_submission public.social_shill_submissions%rowtype;
  v_token public.shill_reward_tokens%rowtype;
begin
  select * into v_submission
  from public.social_shill_submissions
  where id = p_submission_id
  for update;

  if not found then
    return query select 'not_found'::text, null::bigint, null::text, 0;
    return;
  end if;

  if v_submission.status <> 'pending' then
    return query select 'already_reviewed'::text, v_submission.telegram_id, v_submission.token_symbol, v_submission.points_awarded;
    return;
  end if;

  select * into v_token
  from public.shill_reward_tokens
  where symbol = v_submission.token_symbol and enabled = true;

  if not found then
    return query select 'token_disabled'::text, v_submission.telegram_id, v_submission.token_symbol, 0;
    return;
  end if;

  if not exists (select 1 from public.users where telegram_id = v_submission.telegram_id) then
    return query select 'unregistered'::text, v_submission.telegram_id, v_submission.token_symbol, 0;
    return;
  end if;

  begin
    update public.users
    set points = coalesce(points,0) + v_token.points_per_verified_share,
        updated_at = now()
    where telegram_id = v_submission.telegram_id;

    insert into public.rewards(telegram_id, mission_id, points, reward_type, description)
    values (
      v_submission.telegram_id,
      null,
      v_token.points_per_verified_share,
      'shill_share',
      'Verified social shill for $' || v_submission.token_symbol || ' on ' || v_submission.platform
    );

    insert into public.reward_transactions(
      telegram_id, mission_id, submission_id, amount, reward_type, reason, awarded_by
    ) values (
      v_submission.telegram_id,
      null,
      null,
      v_token.points_per_verified_share,
      'shill_share',
      'Verified social shill for $' || v_submission.token_symbol || ' on ' || v_submission.platform,
      p_reviewer_telegram_id
    );
  exception
    when others then
      if sqlerrm in ('weekly_reward_budget_exhausted', 'reward_category_budget_exhausted') then
        return query select 'budget_deferred'::text, v_submission.telegram_id, v_submission.token_symbol, 0;
        return;
      end if;
      raise;
  end;

  update public.social_shill_submissions
  set status='approved',
      points_awarded=v_token.points_per_verified_share,
      reviewed_by=p_reviewer_telegram_id,
      reviewed_at=now(),
      updated_at=now()
  where id=v_submission.id;

  return query select 'approved'::text, v_submission.telegram_id, v_submission.token_symbol, v_token.points_per_verified_share;
end;
$$;

revoke all on function public.approve_social_shill_submission(bigint,bigint) from public;
grant execute on function public.approve_social_shill_submission(bigint,bigint) to service_role;

-- One allowlist drives both the public AUTO token list and owner DCA validation.
insert into public.auto_tokens(network, token_mint, symbol, display_name, status, approved_at)
values ('solana','DF4zASfiDBr3uuAz4s2Sxtsjo7tDFZiQ2nLeKJGfBAGS','RECAP','RecapThisBot','allowlisted',now())
on conflict (network, token_mint) do update
set symbol='RECAP',
    display_name='RecapThisBot',
    status='allowlisted',
    approved_at=coalesce(public.auto_tokens.approved_at,now()),
    updated_at=now();

create table if not exists public.partner_allocation_candidates (
  partner_key text primary key,
  display_name text not null,
  partner_asset_symbol text,
  partner_token_mint text,
  allocation_mode text not null default 'revenue_preferred_supply_fallback'
    check (allocation_mode in ('revenue_preferred_supply_fallback','revenue_only','supply_only')),
  source_scope text not null default 'worldz_tokens',
  revenue_percent numeric(8,4),
  supply_percent numeric(8,4),
  recipient_wallet text,
  status text not null default 'pending_terms'
    check (status in ('pending_terms','approved','disabled')),
  notes text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (revenue_percent is null or revenue_percent between 0 and 100),
  check (supply_percent is null or supply_percent between 0 and 100)
);

insert into public.partner_allocation_candidates(
  partner_key, display_name, partner_asset_symbol, partner_token_mint, allocation_mode, status, notes
) values
  ('edison','Edison',null,null,'revenue_preferred_supply_fallback','pending_terms',
   'Requested as a future Worldz revenue-share or supply-allocation recipient. Exact identity, wallet and percentage still require explicit confirmation.'),
  ('pepe','Pepe',null,null,'revenue_preferred_supply_fallback','pending_terms',
   'Requested as a future Worldz revenue-share or supply-allocation recipient. Exact identity, wallet and percentage still require explicit confirmation.'),
  ('recap','RecapThisBot','RECAP','DF4zASfiDBr3uuAz4s2Sxtsjo7tDFZiQ2nLeKJGfBAGS','revenue_preferred_supply_fallback','pending_terms',
   'RECAP token identity verified from the public Recap project site. Percentage and execution route remain unset until explicitly approved.')
on conflict (partner_key) do update
set display_name=excluded.display_name,
    partner_asset_symbol=coalesce(excluded.partner_asset_symbol, public.partner_allocation_candidates.partner_asset_symbol),
    partner_token_mint=coalesce(excluded.partner_token_mint, public.partner_allocation_candidates.partner_token_mint),
    allocation_mode=excluded.allocation_mode,
    notes=excluded.notes,
    updated_at=now();

alter table public.zed_chat_settings enable row level security;
alter table public.raid_campaigns enable row level security;
alter table public.shill_reward_tokens enable row level security;
alter table public.social_shill_submissions enable row level security;
alter table public.partner_allocation_candidates enable row level security;

grant select, insert, update, delete on
  public.zed_chat_settings,
  public.raid_campaigns,
  public.shill_reward_tokens,
  public.social_shill_submissions,
  public.partner_allocation_candidates
to service_role;

grant usage, select on sequence public.raid_campaigns_id_seq to service_role;
grant usage, select on sequence public.social_shill_submissions_id_seq to service_role;
