-- Non-destructive Zed Bot mission and rewards workflow.
-- Existing users, wallets, missions, submissions and rewards are preserved.

create table if not exists public.users (
  id bigint generated by default as identity primary key,
  telegram_id bigint not null unique,
  username text,
  first_name text,
  wallet text,
  points integer not null default 0,
  raids integer not null default 0,
  raids_completed integer default 0,
  registered_at timestamp without time zone default now(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  last_checkin date
);

alter table public.users
  add column if not exists username text,
  add column if not exists first_name text,
  add column if not exists wallet text,
  add column if not exists points integer default 0,
  add column if not exists raids integer default 0,
  add column if not exists raids_completed integer default 0,
  add column if not exists registered_at timestamp without time zone default now(),
  add column if not exists created_at timestamptz default now(),
  add column if not exists updated_at timestamptz default now(),
  add column if not exists last_checkin date;

create table if not exists public.missions (
  id bigint generated by default as identity primary key,
  title text not null,
  platform text not null,
  target_url text not null default '',
  link text not null default '',
  reward_points integer not null default 5,
  status text not null default 'open',
  description text not null default '',
  instructions text not null default '',
  created_by bigint,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  completed_at timestamptz
);

alter table public.missions
  add column if not exists target_url text default '',
  add column if not exists link text default '',
  add column if not exists reward_points integer default 5,
  add column if not exists status text default 'open',
  add column if not exists description text default '',
  add column if not exists instructions text default '',
  add column if not exists created_by bigint,
  add column if not exists created_at timestamptz default now(),
  add column if not exists updated_at timestamptz default now(),
  add column if not exists completed_at timestamptz;

create table if not exists public.mission_submissions (
  id bigint generated by default as identity primary key,
  mission_id bigint not null references public.missions(id) on delete cascade,
  telegram_id bigint not null,
  proof_url text not null default '',
  completion_text text,
  status text not null default 'pending',
  points_awarded integer not null default 0,
  submitted_at timestamptz not null default now(),
  reviewed_at timestamptz,
  reviewer_telegram_id bigint,
  rejection_reason text,
  updated_at timestamptz not null default now()
);

alter table public.mission_submissions
  add column if not exists proof_url text default '',
  add column if not exists completion_text text,
  add column if not exists status text default 'pending',
  add column if not exists points_awarded integer default 0,
  add column if not exists submitted_at timestamptz default now(),
  add column if not exists reviewed_at timestamptz,
  add column if not exists reviewer_telegram_id bigint,
  add column if not exists rejection_reason text,
  add column if not exists updated_at timestamptz default now();

create table if not exists public.rewards (
  id bigint generated by default as identity primary key,
  telegram_id bigint not null,
  mission_id bigint references public.missions(id) on delete set null,
  points integer not null default 0,
  reward_type text not null default 'mission_points',
  description text not null default '',
  created_at timestamptz not null default now()
);

create table if not exists public.mission_history (
  id bigint generated by default as identity primary key,
  mission_id bigint references public.missions(id) on delete cascade,
  action text not null,
  actor_telegram_id bigint,
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conrelid = 'public.users'::regclass and conname = 'users_points_nonnegative'
  ) then
    alter table public.users
      add constraint users_points_nonnegative check (coalesce(points, 0) >= 0);
  end if;

  if not exists (
    select 1 from pg_constraint
    where conrelid = 'public.missions'::regclass and conname = 'missions_reward_points_check'
  ) then
    alter table public.missions
      add constraint missions_reward_points_check check (reward_points >= 0);
  end if;

  if not exists (
    select 1 from pg_constraint
    where conrelid = 'public.missions'::regclass and conname = 'missions_status_check'
  ) then
    alter table public.missions
      add constraint missions_status_check
      check (status in ('active', 'open', 'completed', 'closed', 'cancelled'));
  end if;

  if not exists (
    select 1 from pg_constraint
    where conrelid = 'public.mission_submissions'::regclass
      and conname = 'mission_submissions_mission_id_telegram_id_key'
  ) then
    alter table public.mission_submissions
      add constraint mission_submissions_mission_id_telegram_id_key
      unique (mission_id, telegram_id);
  end if;

  if not exists (
    select 1 from pg_constraint
    where conrelid = 'public.mission_submissions'::regclass
      and conname = 'mission_submissions_status_check'
  ) then
    alter table public.mission_submissions
      add constraint mission_submissions_status_check
      check (status in ('pending', 'approved', 'rejected'));
  end if;

  if not exists (
    select 1 from pg_constraint
    where conrelid = 'public.mission_submissions'::regclass
      and conname = 'mission_submissions_points_awarded_check'
  ) then
    alter table public.mission_submissions
      add constraint mission_submissions_points_awarded_check
      check (points_awarded >= 0);
  end if;

  if not exists (
    select 1 from pg_constraint
    where conrelid = 'public.rewards'::regclass and conname = 'rewards_points_check'
  ) then
    alter table public.rewards
      add constraint rewards_points_check
      check (points >= 0 or reward_type = 'manual_adjustment');
  end if;
end
$$;

create index if not exists missions_status_created_idx
  on public.missions (status, created_at desc, id desc);
create index if not exists mission_submissions_status_idx
  on public.mission_submissions (status, submitted_at);
create index if not exists mission_submissions_user_status_idx
  on public.mission_submissions (telegram_id, status);
create index if not exists rewards_telegram_created_idx
  on public.rewards (telegram_id, created_at desc);
create index if not exists mission_history_mission_created_idx
  on public.mission_history (mission_id, created_at desc);

alter table public.users enable row level security;
alter table public.missions enable row level security;
alter table public.mission_submissions enable row level security;
alter table public.rewards enable row level security;
alter table public.mission_history enable row level security;

-- These tables are server-only. The bot uses the service-role key on Hostinger.
revoke all on table public.users from anon, authenticated;
revoke all on table public.missions from anon, authenticated;
revoke all on table public.mission_submissions from anon, authenticated;
revoke all on table public.rewards from anon, authenticated;
revoke all on table public.mission_history from anon, authenticated;
grant all on table public.users to service_role;
grant all on table public.missions to service_role;
grant all on table public.mission_submissions to service_role;
grant all on table public.rewards to service_role;
grant all on table public.mission_history to service_role;

create or replace function public.approve_mission_completion(
  p_submission_id bigint,
  p_reviewer_telegram_id bigint
)
returns table(
  submission_id bigint,
  telegram_id bigint,
  awarded_points integer,
  total_points integer,
  total_raids integer,
  mission_title text,
  already_awarded boolean
)
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_submission public.mission_submissions%rowtype;
  v_mission public.missions%rowtype;
  v_user public.users%rowtype;
begin
  select * into v_submission
  from public.mission_submissions s
  where s.id = p_submission_id
  for update;

  if not found then raise exception 'submission_not_found'; end if;
  if v_submission.status = 'rejected' then raise exception 'submission_rejected'; end if;

  select * into v_mission
  from public.missions m
  where m.id = v_submission.mission_id;
  if not found then raise exception 'mission_not_found'; end if;

  select * into v_user
  from public.users u
  where u.telegram_id = v_submission.telegram_id
  for update;
  if not found then raise exception 'user_not_registered'; end if;

  if v_submission.status = 'approved' then
    return query select
      v_submission.id,
      v_submission.telegram_id,
      coalesce(v_submission.points_awarded, 0),
      coalesce(v_user.points, 0),
      greatest(coalesce(v_user.raids_completed, 0), coalesce(v_user.raids, 0)),
      v_mission.title,
      true;
    return;
  end if;

  update public.users u
  set points = coalesce(u.points, 0) + v_mission.reward_points,
      raids = coalesce(u.raids, 0) + 1,
      raids_completed = coalesce(u.raids_completed, 0) + 1,
      updated_at = now()
  where u.telegram_id = v_submission.telegram_id
  returning u.* into v_user;

  update public.mission_submissions s
  set status = 'approved',
      points_awarded = v_mission.reward_points,
      reviewer_telegram_id = p_reviewer_telegram_id,
      reviewed_at = now(),
      rejection_reason = null,
      updated_at = now()
  where s.id = v_submission.id;

  insert into public.rewards (
    telegram_id, mission_id, points, reward_type, description
  ) values (
    v_submission.telegram_id,
    v_submission.mission_id,
    v_mission.reward_points,
    'mission_points',
    'Raaiiidd mission completion'
  );

  insert into public.mission_history (
    mission_id, action, actor_telegram_id, details
  ) values (
    v_submission.mission_id,
    'claim_approved',
    p_reviewer_telegram_id,
    jsonb_build_object(
      'submission_id', v_submission.id,
      'telegram_id', v_submission.telegram_id,
      'points', v_mission.reward_points
    )
  );

  return query select
    v_submission.id,
    v_submission.telegram_id,
    v_mission.reward_points,
    coalesce(v_user.points, 0),
    greatest(coalesce(v_user.raids_completed, 0), coalesce(v_user.raids, 0)),
    v_mission.title,
    false;
end;
$$;

revoke all on function public.approve_mission_completion(bigint, bigint)
  from public, anon, authenticated;
grant execute on function public.approve_mission_completion(bigint, bigint)
  to service_role;

create or replace function public.adjust_legend_points(
  p_target_telegram_id bigint,
  p_amount integer,
  p_admin_telegram_id bigint
)
returns table(telegram_id bigint, adjustment integer, total_points integer)
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_user public.users%rowtype;
  v_total integer;
begin
  if p_amount = 0 or p_amount < -10000 or p_amount > 10000 then
    raise exception 'invalid_adjustment';
  end if;

  select * into v_user
  from public.users u
  where u.telegram_id = p_target_telegram_id
  for update;
  if not found then raise exception 'user_not_registered'; end if;

  v_total := coalesce(v_user.points, 0) + p_amount;
  if v_total < 0 then raise exception 'points_cannot_be_negative'; end if;

  update public.users u
  set points = v_total, updated_at = now()
  where u.telegram_id = p_target_telegram_id;

  insert into public.rewards (
    telegram_id, mission_id, points, reward_type, description
  ) values (
    p_target_telegram_id,
    null,
    p_amount,
    'manual_adjustment',
    'Administrator Legend Points adjustment'
  );

  insert into public.mission_history (
    mission_id, action, actor_telegram_id, details
  ) values (
    null,
    'points_adjusted',
    p_admin_telegram_id,
    jsonb_build_object(
      'telegram_id', p_target_telegram_id,
      'amount', p_amount,
      'total_points', v_total
    )
  );

  return query select p_target_telegram_id, p_amount, v_total;
end;
$$;

revoke all on function public.adjust_legend_points(bigint, integer, bigint)
  from public, anon, authenticated;
grant execute on function public.adjust_legend_points(bigint, integer, bigint)
  to service_role;
