-- Worldz Inbox™ private Telegram DM relay. No public RLS policies.
create table if not exists public.worldz_dm_preferences (
  telegram_id bigint primary key,
  enabled boolean not null default true,
  telegram_dm_reachable boolean not null default false,
  username text, first_name text,
  last_private_seen_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create table if not exists public.worldz_dm_messages (
  id bigint generated by default as identity primary key,
  sender_telegram_id bigint not null,
  recipient_telegram_id bigint not null,
  body text not null check (char_length(body) between 1 and 2800),
  style_preset text not null default 'dm' check (style_preset in ('worldz','dm','announcement','update','launch','mission','impact','proof','alert','celebration')),
  style_title text check (style_title is null or char_length(style_title)<=180),
  cta_label text check (cta_label is null or char_length(cta_label)<=80),
  cta_url text check (cta_url is null or cta_url ~ '^https://'),
  status text not null default 'queued' check (status in ('queued','telegram_sent','failed')),
  telegram_message_id bigint, error_code text,
  created_at timestamptz not null default now(), sent_at timestamptz, failed_at timestamptz, read_at timestamptz,
  sender_deleted_at timestamptz, recipient_deleted_at timestamptz,
  expires_at timestamptz not null default (now()+interval '180 days'),
  check (sender_telegram_id<>recipient_telegram_id)
);
create index if not exists worldz_dm_messages_recipient_idx on public.worldz_dm_messages(recipient_telegram_id,created_at desc) where recipient_deleted_at is null;
create index if not exists worldz_dm_messages_unread_idx on public.worldz_dm_messages(recipient_telegram_id,created_at desc) where read_at is null and recipient_deleted_at is null and status='telegram_sent';
create index if not exists worldz_dm_messages_sender_idx on public.worldz_dm_messages(sender_telegram_id,created_at desc) where sender_deleted_at is null;
create table if not exists public.worldz_dm_blocks (
  blocker_telegram_id bigint not null, blocked_telegram_id bigint not null,
  created_at timestamptz not null default now(),
  primary key(blocker_telegram_id,blocked_telegram_id),
  check(blocker_telegram_id<>blocked_telegram_id)
);
alter table public.worldz_dm_preferences enable row level security;
alter table public.worldz_dm_messages enable row level security;
alter table public.worldz_dm_blocks enable row level security;
revoke all on table public.worldz_dm_preferences from anon,authenticated;
revoke all on table public.worldz_dm_messages from anon,authenticated;
revoke all on table public.worldz_dm_blocks from anon,authenticated;
revoke all on sequence public.worldz_dm_messages_id_seq from anon,authenticated;
comment on table public.worldz_dm_messages is 'Private Worldz Inbox relay. telegram_sent means Telegram accepted the bot send; read_at is separate.';
