-- Grace X OAuth connection
-- OAuth 2.0 Authorization Code Flow with PKCE, exact-handle verification and encrypted token storage.

create table if not exists public.grace_oauth_states (
  id uuid primary key default gen_random_uuid(),
  workspace_id uuid not null references public.grace_workspaces(id) on delete cascade,
  account_id bigint not null references public.grace_social_accounts(id) on delete cascade,
  provider text not null check (provider in ('x')),
  state_hash text not null unique check (char_length(state_hash) between 32 and 128),
  verifier_ciphertext text not null check (char_length(verifier_ciphertext) between 40 and 2000),
  expected_handle text not null check (expected_handle ~ '^[A-Za-z0-9_]{1,50}$'),
  requested_by bigint,
  expires_at timestamptz not null,
  used_at timestamptz,
  created_at timestamptz not null default now()
);

create table if not exists public.grace_oauth_connections (
  id bigint generated by default as identity primary key,
  workspace_id uuid not null references public.grace_workspaces(id) on delete cascade,
  account_id bigint not null references public.grace_social_accounts(id) on delete cascade,
  provider text not null check (provider in ('x')),
  external_account_id text not null,
  username text not null check (username ~ '^[A-Za-z0-9_]{1,50}$'),
  access_token_ciphertext text not null check (char_length(access_token_ciphertext) between 40 and 10000),
  refresh_token_ciphertext text,
  token_type text not null default 'bearer',
  scope text not null default '',
  expires_at timestamptz,
  status text not null default 'active' check (status in ('active', 'revoked', 'error')),
  connected_at timestamptz not null default now(),
  last_refreshed_at timestamptz,
  last_error text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (account_id, provider)
);

create index if not exists grace_oauth_states_expiry_idx
  on public.grace_oauth_states (workspace_id, provider, expires_at)
  where used_at is null;

create index if not exists grace_oauth_connections_status_idx
  on public.grace_oauth_connections (workspace_id, provider, status);

create or replace trigger grace_oauth_connections_touch_updated_at
before update on public.grace_oauth_connections
for each row execute function public.grace_touch_updated_at();

create or replace function public.grace_consume_oauth_state(
  p_workspace_id uuid,
  p_provider text,
  p_state_hash text
)
returns table (
  account_id bigint,
  verifier_ciphertext text,
  expected_handle text,
  requested_by bigint
)
language plpgsql
security definer
set search_path = public, pg_temp
as $$
begin
  return query
  update public.grace_oauth_states state
  set used_at = now()
  where state.workspace_id = p_workspace_id
    and state.provider = p_provider
    and state.state_hash = p_state_hash
    and state.used_at is null
    and state.expires_at > now()
  returning
    state.account_id,
    state.verifier_ciphertext,
    state.expected_handle,
    state.requested_by;
end;
$$;

alter table public.grace_oauth_states enable row level security;
alter table public.grace_oauth_connections enable row level security;

revoke all on table public.grace_oauth_states from anon, authenticated;
revoke all on table public.grace_oauth_connections from anon, authenticated;

revoke all on function public.grace_consume_oauth_state(uuid, text, text) from public, anon, authenticated;
grant execute on function public.grace_consume_oauth_state(uuid, text, text) to service_role;
