-- WorldzPay side-rail persistence schema.
-- PREPARED ONLY: this migration is held on the draft worldzpay-side-rail branch.
-- It does not authorize live provider calls, signing, custody, treasury broadcasts, or reserve sweeps.\n-- Current Operations governance is 3-of-5; Reserve is disabled/not deployed.

create table if not exists public.worldzpay_payment_intents (
  intent_id text primary key check (intent_id ~ '^wzp_[a-f0-9]{28}$'),
  checkout_id text,
  source_id text not null,
  provider_id text not null,
  payment_method text not null,
  fiat_currency text not null check (char_length(fiat_currency) between 3 and 8),
  fiat_amount_minor numeric(30,0) not null check (fiat_amount_minor > 0),
  settlement_asset text not null check (settlement_asset in ('SOL','USDC','USDT')),
  customer_ref text not null check (char_length(customer_ref) between 1 and 160),
  idempotency_key_hash text not null check (idempotency_key_hash ~ '^[a-f0-9]{64}$'),
  state text not null default 'quoted'
    check (state in ('draft','quoted','awaiting_payment','paid','cancelled','refunded')),
  execution_mode text not null default 'simulation_only'
    check (execution_mode in ('simulation_only','production')),
  live_funds_enabled boolean not null default false,
  provider_reference text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists worldzpay_intent_idempotency_idx
  on public.worldzpay_payment_intents(source_id, idempotency_key_hash);

create index if not exists worldzpay_intent_state_idx
  on public.worldzpay_payment_intents(state, created_at desc);

create table if not exists public.worldzpay_provider_events (
  id bigint generated by default as identity primary key,
  provider_id text not null,
  provider_event_key text not null unique check (char_length(provider_event_key) between 8 and 220),
  event_type text not null check (char_length(event_type) between 1 and 120),
  payload_sha256 text not null check (payload_sha256 ~ '^[a-f0-9]{64}$'),
  signature_verified boolean not null default false,
  processing_state text not null default 'received'
    check (processing_state in ('received','verified','applied','rejected','duplicate')),
  payment_intent_id text references public.worldzpay_payment_intents(intent_id) on update cascade on delete set null,
  received_at timestamptz not null default now(),
  processed_at timestamptz
);

create index if not exists worldzpay_provider_events_intent_idx
  on public.worldzpay_provider_events(payment_intent_id, received_at desc);

create table if not exists public.worldzpay_treasury_proposals (
  proposal_id text primary key check (proposal_id ~ '^wzt_[a-f0-9]{28}$'),
  checkout_id text not null,
  payment_intent_id text not null references public.worldzpay_payment_intents(intent_id) on update cascade on delete restrict,
  source_id text not null,
  settlement_asset text not null check (settlement_asset in ('SOL','USDC','USDT')),
  net_worldz_controlled_raw numeric(40,0) not null check (net_worldz_controlled_raw >= 0),
  routing_state text not null,
  unsigned_payload_hash text not null unique check (unsigned_payload_hash ~ '^[a-f0-9]{64}$'),
  provider_id text not null,
  provider_settlement_reference text,
  operations_profile_id text not null default 'worldz-operations',
  required_threshold integer not null default 3 check (required_threshold = 3),
  required_signers integer not null default 10 check (required_signers = 10),
  current_governance_verified boolean not null default false,
  destination_verified boolean not null default false,
  execution_state text not null default 'prepared_only'
    check (execution_state in ('prepared_only','approved','settled','cancelled')),
  can_sign boolean not null default false,
  can_broadcast boolean not null default false,
  worldzproof_receipt_id text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (not can_broadcast or (current_governance_verified and destination_verified))
);

create index if not exists worldzpay_treasury_state_idx
  on public.worldzpay_treasury_proposals(execution_state, created_at desc);

create table if not exists public.worldzpay_reconciliation_entries (
  id bigint generated by default as identity primary key,
  payment_intent_id text not null references public.worldzpay_payment_intents(intent_id) on update cascade on delete restrict,
  provider_id text not null,
  settlement_asset text not null check (settlement_asset in ('SOL','USDC','USDT')),
  gross_raw numeric(40,0) not null check (gross_raw >= 0),
  external_fees_raw numeric(40,0) not null default 0 check (external_fees_raw >= 0),
  protected_earmarks_raw numeric(40,0) not null default 0 check (protected_earmarks_raw >= 0),
  net_worldz_controlled_raw numeric(40,0) not null check (net_worldz_controlled_raw >= 0),
  reconciliation_state text not null default 'pending'
    check (reconciliation_state in ('pending','matched','mismatch','rejected')),
  evidence_reference text,
  created_at timestamptz not null default now(),
  reconciled_at timestamptz,
  check (net_worldz_controlled_raw <= gross_raw)
);

create index if not exists worldzpay_reconciliation_intent_idx
  on public.worldzpay_reconciliation_entries(payment_intent_id, created_at desc);

alter table public.worldzpay_payment_intents enable row level security;
alter table public.worldzpay_provider_events enable row level security;
alter table public.worldzpay_treasury_proposals enable row level security;
alter table public.worldzpay_reconciliation_entries enable row level security;

revoke all on table public.worldzpay_payment_intents from anon, authenticated;
revoke all on table public.worldzpay_provider_events from anon, authenticated;
revoke all on table public.worldzpay_treasury_proposals from anon, authenticated;
revoke all on table public.worldzpay_reconciliation_entries from anon, authenticated;

comment on table public.worldzpay_payment_intents is
  'WorldzPay payment intent ledger. Side-rail schema only until explicit production activation.';
comment on table public.worldzpay_provider_events is
  'Hash-only provider event audit ledger; never store payment credentials or private keys.';
comment on table public.worldzpay_treasury_proposals is
  'Unsigned treasury proposal records. Signing and broadcast remain separately gated.';
comment on table public.worldzpay_reconciliation_entries is
  'Gross-to-net provider reconciliation before Worldz-controlled revenue routing.';
