-- DIPSHIT™ paid membership ledger.
-- Stores only the minimum membership/payment data required for access, support and refund/cancellation handling.

create table if not exists public.dipshit_memberships (
  telegram_id bigint primary key check (telegram_id > 0),
  source text not null check (source in ('stars','sol')),
  status text not null default 'active' check (status in ('active','expired')),
  current_period_start timestamptz not null,
  current_period_end timestamptz not null,
  auto_renew boolean not null default false,
  telegram_payment_charge_id text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (current_period_end > current_period_start)
);

create table if not exists public.dipshit_membership_payments (
  id bigint generated by default as identity primary key,
  telegram_id bigint not null check (telegram_id > 0),
  source text not null check (source in ('stars','sol')),
  payment_ref text not null,
  currency text not null check (currency in ('XTR','SOL')),
  amount numeric not null check (amount > 0),
  period_start timestamptz not null,
  period_end timestamptz not null,
  is_recurring boolean not null default false,
  created_at timestamptz not null default now(),
  unique (source, payment_ref),
  check (period_end > period_start)
);

create index if not exists dipshit_membership_payments_telegram_idx
  on public.dipshit_membership_payments(telegram_id, created_at desc);

alter table public.dipshit_memberships enable row level security;
alter table public.dipshit_membership_payments enable row level security;

revoke all on table public.dipshit_memberships from anon, authenticated;
revoke all on table public.dipshit_membership_payments from anon, authenticated;
revoke all on sequence public.dipshit_membership_payments_id_seq from anon, authenticated;

drop policy if exists "zed_runtime_bridge" on public.dipshit_memberships;
create policy "zed_runtime_bridge" on public.dipshit_memberships
for all to anon
using (public.zed_runtime_authorized())
with check (public.zed_runtime_authorized());

drop policy if exists "zed_runtime_bridge" on public.dipshit_membership_payments;
create policy "zed_runtime_bridge" on public.dipshit_membership_payments
for all to anon
using (public.zed_runtime_authorized())
with check (public.zed_runtime_authorized());

grant select, insert, update, delete on public.dipshit_memberships, public.dipshit_membership_payments to service_role;
grant usage, select on sequence public.dipshit_membership_payments_id_seq to service_role;
grant select, insert, update, delete on public.dipshit_memberships, public.dipshit_membership_payments to anon;
grant usage, select on sequence public.dipshit_membership_payments_id_seq to anon;
revoke all on public.dipshit_memberships, public.dipshit_membership_payments from authenticated;

create or replace function public.record_dipshit_membership_payment(
  p_telegram_id bigint,
  p_source text,
  p_payment_ref text,
  p_currency text,
  p_amount numeric,
  p_period_end timestamptz default null,
  p_is_recurring boolean default false,
  p_auto_renew boolean default false
)
returns jsonb
language plpgsql
security definer
set search_path to ''
as $function$
declare
  existing_payment public.dipshit_membership_payments%rowtype;
  current_membership public.dipshit_memberships%rowtype;
  saved_membership public.dipshit_memberships%rowtype;
  period_start timestamptz;
  period_end timestamptz;
begin
  if coalesce(auth.role(), '') <> 'service_role' and not public.zed_runtime_authorized() then
    raise exception 'not_authorized';
  end if;
  if p_telegram_id is null or p_telegram_id <= 0 then raise exception 'invalid_telegram_id'; end if;
  if p_source not in ('stars','sol') then raise exception 'invalid_source'; end if;
  if p_currency not in ('XTR','SOL') then raise exception 'invalid_currency'; end if;
  if p_source = 'stars' and p_currency <> 'XTR' then raise exception 'invalid_stars_currency'; end if;
  if p_source = 'sol' and p_currency <> 'SOL' then raise exception 'invalid_sol_currency'; end if;
  if p_payment_ref is null or char_length(trim(p_payment_ref)) < 8 then raise exception 'invalid_payment_ref'; end if;
  if p_amount is null or p_amount <= 0 then raise exception 'invalid_amount'; end if;

  select * into existing_payment
  from public.dipshit_membership_payments
  where source = p_source and payment_ref = p_payment_ref;

  if found then
    select * into saved_membership from public.dipshit_memberships where telegram_id = p_telegram_id;
    return jsonb_build_object('duplicate', true, 'membership', to_jsonb(saved_membership));
  end if;

  select * into current_membership
  from public.dipshit_memberships
  where telegram_id = p_telegram_id
  for update;

  if p_source = 'sol' then
    period_start := greatest(now(), coalesce(current_membership.current_period_end, now()));
    period_end := period_start + interval '30 days';
  else
    period_start := now();
    period_end := p_period_end;
    if period_end is null or period_end <= period_start then
      raise exception 'invalid_period_end';
    end if;
  end if;

  insert into public.dipshit_membership_payments(
    telegram_id, source, payment_ref, currency, amount,
    period_start, period_end, is_recurring
  ) values (
    p_telegram_id, p_source, trim(p_payment_ref), p_currency, p_amount,
    period_start, period_end, p_is_recurring
  );

  insert into public.dipshit_memberships(
    telegram_id, source, status, current_period_start, current_period_end,
    auto_renew, telegram_payment_charge_id, created_at, updated_at
  ) values (
    p_telegram_id, p_source, 'active', period_start, period_end,
    case when p_source = 'stars' then p_auto_renew else false end,
    case when p_source = 'stars' then trim(p_payment_ref) else null end,
    now(), now()
  )
  on conflict (telegram_id) do update set
    source = excluded.source,
    status = 'active',
    current_period_start = excluded.current_period_start,
    current_period_end = excluded.current_period_end,
    auto_renew = excluded.auto_renew,
    telegram_payment_charge_id = excluded.telegram_payment_charge_id,
    updated_at = now()
  returning * into saved_membership;

  return jsonb_build_object('duplicate', false, 'membership', to_jsonb(saved_membership));
end;
$function$;

revoke all on function public.record_dipshit_membership_payment(bigint,text,text,text,numeric,timestamptz,boolean,boolean) from public, authenticated;
grant execute on function public.record_dipshit_membership_payment(bigint,text,text,text,numeric,timestamptz,boolean,boolean) to anon, service_role;

comment on table public.dipshit_memberships is 'DIPSHIT paid-access state; no seed phrases, private keys or payment-card data.';
comment on table public.dipshit_membership_payments is 'Minimal Stars/SOL payment proof ledger used for idempotent membership activation.';
