-- Zed Community Operations foundation. Additive only: no existing rows are deleted.
alter table public.bot_admins drop constraint if exists bot_admins_role_check;
alter table public.bot_admins add constraint bot_admins_role_check
  check (role in ('owner','admin','moderator','recap_manager','partner_manager','treasury_manager')) not valid;
alter table public.bot_admins validate constraint bot_admins_role_check;

create table if not exists public.bot_admin_permissions (
  id bigint generated by default as identity primary key,
  telegram_id bigint not null,
  permission text not null,
  enabled boolean not null default true,
  set_by bigint,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (telegram_id, permission)
);

create table if not exists public.bot_settings (
  setting_key text primary key,
  setting_value jsonb not null default '{}'::jsonb,
  updated_by bigint,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.treasury_accounts (
  id bigint generated by default as identity primary key,
  label text not null default 'CryptoWorldz Community Kitty',
  network text not null default 'solana' check (network = 'solana'),
  asset text not null check (asset in ('SOL','USDC')),
  public_address text not null,
  status text not null default 'active' check (status in ('active','disabled')),
  created_by bigint,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (network, asset, public_address)
);

create table if not exists public.treasury_contributions (
  id bigint generated by default as identity primary key,
  treasury_account_id bigint references public.treasury_accounts(id) on delete set null,
  transaction_signature text not null unique,
  telegram_id bigint,
  asset text not null check (asset in ('SOL','USDC')),
  amount numeric(30,9) not null check (amount > 0),
  status text not null default 'pending' check (status in ('pending','confirmed','rejected')),
  points_awarded integer not null default 0 check (points_awarded >= 0),
  confirmed_by bigint,
  created_at timestamptz not null default now(),
  confirmed_at timestamptz,
  updated_at timestamptz not null default now()
);

create table if not exists public.auto_approval_rules (
  id bigint generated by default as identity primary key,
  rule_key text not null unique,
  platform text not null,
  verification_type text not null,
  enabled boolean not null default false,
  points_awarded integer not null default 0 check (points_awarded >= 0),
  max_points integer check (max_points is null or max_points >= 0),
  config jsonb not null default '{}'::jsonb,
  set_by bigint,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.partner_profiles (
  id bigint generated by default as identity primary key,
  telegram_id bigint not null unique,
  display_name text not null,
  organization text not null,
  partner_role text not null check (partner_role in ('recap_manager','partner_manager','treasury_manager')),
  status text not null default 'active' check (status in ('active','disabled')),
  created_by bigint,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists bot_admin_permissions_telegram_idx on public.bot_admin_permissions(telegram_id);
create index if not exists treasury_contributions_member_idx on public.treasury_contributions(telegram_id, created_at desc);
create index if not exists treasury_contributions_status_idx on public.treasury_contributions(status, created_at desc);

alter table public.bot_admin_permissions enable row level security;
alter table public.bot_settings enable row level security;
alter table public.treasury_accounts enable row level security;
alter table public.treasury_contributions enable row level security;
alter table public.auto_approval_rules enable row level security;
alter table public.partner_profiles enable row level security;

revoke all on public.bot_admin_permissions, public.bot_settings, public.treasury_accounts,
  public.treasury_contributions, public.auto_approval_rules, public.partner_profiles from anon, authenticated;
grant all on public.bot_admin_permissions, public.bot_settings, public.treasury_accounts,
  public.treasury_contributions, public.auto_approval_rules, public.partner_profiles to service_role;
