import {getWallets} from 'https://esm.sh/@wallet-standard/app@1.1.0?bundle';
import bs58mod from 'https://esm.sh/bs58@6.0.0?bundle';
const bs58=bs58mod.default||bs58mod,$=s=>document.querySelector(s);
const API='https://hknymhhyqldtzmplzuzh.supabase.co/functions/v1/worldz-legacy-proof';
const DEV='Fap54GTCo4ZopkwmHtbSUJZTsjTybftJfN9sPG3MHp4u';
let ctx=null,assets=[];
function status(t,c=''){const e=$('#status');e.textContent=t;e.className='status'+(c?' '+c:'');}
function short(x){return x.slice(0,7)+'…'+x.slice(-7)}
function wallets(){return getWallets().get().filter(w=>w.chains?.some(c=>String(c).startsWith('solana:'))&&w.features?.['standard:connect']&&w.features?.['solana:signMessage']);}
async function load(){const r=await fetch(API,{cache:'no-store'}),o=await r.json();if(!r.ok||!o.ok)throw new Error(o.error||'Registry unavailable');assets=o.legacyAssets||[];$('#assets').innerHTML=assets.map(a=>'<div class="asset" id="asset-'+a.legacy_order+'"><b>#'+String(a.legacy_order).padStart(2,'0')+'</b><div><strong>'+a.token_name+' • '+a.symbol+'</strong><small>'+short(a.mint)+'</small></div><span>'+a.snapshot_status+'</span></div>').join('');const complete=(o.recentBatches||[]).find(b=>b.status==='COMPLETE');if(complete){$('#proof').textContent='Latest snapshot root: '+complete.snapshot_root+'\nBatch: '+complete.batch_id;$('#proof').className='status good';}}
async function connect(){try{const list=wallets(),j=list.find(w=>/jupiter/i.test(w.name))||list[0];if(!j)throw new Error('No compatible Solana Wallet Standard wallet detected.');const out=await j.features['standard:connect'].connect(),account=(out?.accounts||j.accounts||[])[0];if(!account)throw new Error('Wallet returned no account.');ctx={wallet:j,account,address:account.address};if(ctx.address!==DEV)throw new Error('Wrong wallet connected. Use the authorized Worldz Dev Wallet.');$('#wallet').textContent=short(ctx.address);$('#wallet').classList.add('connected');$('#run').disabled=false;status('AUTHORIZED WALLET CONNECTED ✅\nOne harmless message signature will authorize the complete read-only 10-asset snapshot.','good');}catch(e){status('CONNECT FAILED\n'+(e.message||e),'bad');}}
async function signStart(){const issued_at=new Date().toISOString();const msg=['WORLDZ_LEGACY_PROOF_V1','action=START_BATCH','wallet='+ctx.address,'batch=','legacy_order=','issued_at='+issued_at].join('\n');const bytes=new TextEncoder().encode(msg);const out=await ctx.wallet.features['solana:signMessage'].signMessage({account:ctx.account,message:bytes});const signed=out?.[0]?.signature;if(!signed)throw new Error('Wallet returned no message signature.');return {wallet:ctx.address,issued_at,signature:bs58.encode(signed)};}
async function post(body){const r=await fetch(API,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)}),o=await r.json().catch(()=>({}));if(!r.ok||!o.ok)throw new Error(o.error||'Legacy proof request failed');return o;}
async function run(){if(!ctx)return;$('#run').disabled=true;try{status('AUTHORIZE ONE READ-ONLY SNAPSHOT SESSION IN JUPITER…','warn');const auth=await signStart(),start=await post({action:'START_BATCH',...auth}),batch=start.batch.batch_id,token=start.batchToken;for(let i=1;i<=10;i++){status('SNAPSHOTTING LEGACY ASSET '+i+' / 10…\nNo blockchain transaction is being sent.','warn');const x=await post({action:'SNAPSHOT_ASSET',batch_id:batch,batch_token:token,legacy_order:i});const row=$('#asset-'+i);if(row){row.querySelector('span').textContent='SNAPSHOT COMPLETE • '+x.holders+' HOLDERS';row.querySelector('span').className='done';}}status('BUILDING ENTITLEMENT PROOF…','warn');const fin=await post({action:'FINALIZE_BATCH',batch_id:batch,batch_token:token});status('LEGACY PROOF COMPLETE ✅\nAll 10 assets snapshotted.\nUnique legacy wallets: '+fin.uniqueLegacyWallets,'good');$('#proof').textContent='Snapshot hash: '+fin.snapshotHash+'\nBatch: '+fin.batchId+'\nLegacy pool raw units: '+fin.revivePoolRaw;$('#proof').className='status good';}catch(e){status('LEGACY PROOF STOPPED\n'+(e.message||e),'bad');}finally{$('#run').disabled=false;}}
$('#wallet').onclick=connect;$('#run').onclick=run;getWallets().on('register',()=>{});load().catch(e=>status(e.message||e,'bad'));